normalization

diff --git a/sh/tools/backup-remote-rsync b/sh/tools/backup-remote-rsync
--- a/sh/tools/backup-remote-rsync
+++ b/sh/tools/backup-remote-rsync
@@ -150,7 +150,7 @@ _hasdotfiles()
 
 _internetavailable()
 {
-    ping -q -w 1 -c 1 google.com >/dev/null && return 0 || return 1
+    ping -q -w 1 -c 1 google.com >/dev/null 2>&1 && return 0 || return 1
 }
 
 _backup()
@@ -240,22 +240,23 @@ _backup()
 
 _usage()
 {
-    printf "%s\\n" "Usage: $(_basename "${0}") -r DOMAIN:/PATH [-h|-v|-s|-o|-n|-u USER|-p PORT|-i SSH KEY|-l LOGFILE] [LOCAL_DIR ...]" >&2
+    printf "%s\\n" "Usage: $(_basename "${0}") -r domain:/path [options] [local_dir ...]" >&2
+    printf "%s\\n" "Backup directories to a remote system." >&2
     printf "\\n" >&2
-    printf "%s\\n" "required arguments:" >&2
-    printf "%s\\n" "  -r DOMAIN|IP:/PATH    remote server" >&2
+    printf "%s\\n" "Required arguments:" >&2
+    printf "%s\\n" "  -r domain|ip:/path     remote server" >&2
     printf "\\n" >&2
-    printf "%s\\n" "optional arguments:" >&2
-    printf "%s\\n" "  LOCAL_DIR|LOCAL_FILE  dirs|files to backup [${HOME}]" >&2
-    printf "%s\\n" "  -h                    this message" >&2
-    printf "%s\\n" "  -v                    verbose" >&2
-    printf "%s\\n" "  -s                    skip ssh auth pre-tests" >&2
-    printf "%s\\n" "  -o                    omit executing commmands, useful with -v" >&2
-    printf "%s\\n" "  -n                    dry run, list files to be modified" >&2
-    printf "%s\\n" "  -u USER               remote user    [${USER}]" >&2
-    printf "%s\\n" "  -p PORT               remote port    [22]" >&2
-    printf "%s\\n" "  -i SSH KEY            ssh public key [${HOME}/.ssh/id_rsa]" >&2
-    printf "%s\\n" "  -l FILE               log file       [/tmp/$(_basename "${0}").log ]" >&2
+    printf "%s\\n" "Optional arguments:" >&2
+    printf "%s\\n" "  local_dir|local_file   dirs|files to backup [${HOME}]" >&2
+    printf "%s\\n" "  -v                     verbose" >&2
+    printf "%s\\n" "  -s                     skip ssh auth pre-tests" >&2
+    printf "%s\\n" "  -o                     omit executing commmands, useful with -v" >&2
+    printf "%s\\n" "  -n                     dry run, list files to be modified" >&2
+    printf "%s\\n" "  -u user                remote user    [${USER}]" >&2
+    printf "%s\\n" "  -p port                remote port    [22]" >&2
+    printf "%s\\n" "  -i ssh key             ssh public key [${HOME}/.ssh/id_rsa]" >&2
+    printf "%s\\n" "  -l file                log file       [/tmp/$(_basename "${0}").log ]" >&2
+    printf "%s\\n" "  -h, --help             show this help message and exit" >&2
     printf "\\n" >&2
     printf "%s\\n" "NOTE: ssh key authentication must be configured for this script to work" >&2
     exit 1
@@ -268,44 +269,45 @@ fi
 
 [ "${#}" -eq "0" ] && _usage
 
-for var; do #parse options
-    case "${var}" in
-        -h) _usage ;;
-        -v) verbose_flag="true";        shift ;;
-        -n) dryrun_flag="true";         shift ;;
-        -o) ommit_flag="true";          shift ;;
+for arg; do #parse options
+    case "${arg}" in
+        --) shift; break   ;;
+        -h|--help) _usage  ;;
+        -v) verbose_flag="true";   shift ;;
+        -n) dryrun_flag="true";    shift ;;
+        -o) ommit_flag="true";     shift ;;
         -s) skip_ssh_tests="true"; shift ;;
         -u) if [ "${#}" -gt "1" ]; then
                 remote_user="$(printf "%s " "${@}" | awk '{print $2}')"
                 shift 2
             else
-               printf "%s\\n" "Option ${var} requires a parameter" >&2; _usage
+               printf "%s\\n" "Option \`${arg}' requires a parameter" >&2; _usage
             fi ;;
         -p) if [ "${#}" -gt "1" ]; then
                 remote_port="$(printf "%s " "${@}" | awk '{print $2}')"
                 shift 2
             else
-               printf "%s\\n" "Option ${var} requires a parameter" >&2; _usage
+               printf "%s\\n" "Option \`${arg}' requires a parameter" >&2; _usage
             fi ;;
         -r) if [ "${#}" -gt "1" ]; then
                 remote_server="$(printf "%s " "${@}" | awk '{print $2}')"
                 shift 2
             else
-               printf "%s\\n" "Option ${var} requires a parameter" >&2; _usage
+               printf "%s\\n" "Option \`${arg}' requires a parameter" >&2; _usage
             fi ;;
         -i) if [ "${#}" -gt "1" ]; then
                 sshkey="$(printf "%s " "${@}" | awk '{print $2}')"
                 shift 2
             else
-               printf "%s\\n" "Option ${var} requires a parameter" >&2; _usage
+               printf "%s\\n" "Option \`${arg}' requires a parameter" >&2; _usage
             fi ;;
         -l) if [ "${#}" -gt "1" ]; then
                 logfile="$(printf "%s " "${@}" | awk '{print $2}')"
                 shift 2
             else
-               printf "%s\\n" "Option ${var} requires a parameter" >&2; _usage
+               printf "%s\\n" "Option \`${arg}' requires a parameter" >&2; _usage
             fi ;;
-        -*) printf "%s\\n" "Unrecognized option: ${var}" >&2; exit 1 ;;
+        -*) printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): unrecognized option \`${arg}'" >&2; _usage ;;
     esac
 done
 
diff --git a/sh/tools/cat-show b/sh/tools/cat-show
--- a/sh/tools/cat-show
+++ b/sh/tools/cat-show
@@ -12,12 +12,24 @@ if [ ! -t 0 ]; then
     set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
 fi
 
-program="${1}"
+[ "${#}" -eq "0" ] && { printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)'): script" >&2; exit 1; }
 
-[ "${#}" -eq "0" ] && { printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)'): program" >&2; exit 1; }
+for arg; do #parse options
+    case "${arg}" in
+        --) shift; break ;;
+        -h|--help) { printf "Usage: %s\\n" "$(expr "${0}" : '.*/\([^/]*\)') script" >&2; exit 1; } ;;
+        -*) printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): unrecognized option \`${arg}'" >&2
+            printf "Usage: %s\\n" "$(expr "${0}" : '.*/\([^/]*\)') script" >&2
+            exit 1
+            ;;
+    esac
+done
 
-if command -v "${program}" >/dev/null 2>&1; then
-    less "$(command -v "${program}" 2>/dev/null)"
+script="${1}"
+
+if command -v "${script}" >/dev/null 2>&1; then
+    less "$(command -v "${script}" 2>/dev/null)"
 else
-    printf "$(expr "${0}" : '.*/\([^/]*\)'): %s\\n" "program '${program}' was not found in PATH" >&2
+    printf "$(expr "${0}" : '.*/\([^/]*\)'): %s\\n" "script '${script}' was not found in \$PATH" >&2
+    exit 1
 fi
diff --git a/sh/tools/vim-show b/sh/tools/vim-show
--- a/sh/tools/vim-show
+++ b/sh/tools/vim-show
@@ -12,9 +12,24 @@ if [ ! -t 0 ]; then
     set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
 fi
 
-[ "${#}" -eq "0" ] && { printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)'): program" >&2; exit 1; }
+[ "${#}" -eq "0" ] && { printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') script" >&2; exit 1; }
 
-if command -v "${1}" >/dev/null 2>&1; then
+for arg in "${@}"; do #parse options
+    case "${arg}" in
+        --) shift; break  ;;
+        -h|--help)  { printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') script" >&2; exit 1; } ;;
+        -*) printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): unrecognized option \`${arg}'" >&2
+            printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') script" >&2
+            exit 1 ;;
+    esac
+done
+
+script="${1}"
+
+if command -v "${script}" >/dev/null 2>&1; then
     [ -z "${EDITOR}" ] && { printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): variable EDITOR was not found" >&2; exit 1; } 
-    ${EDITOR} "$(command -v "${1}" 2>/dev/null)"
+    ${EDITOR} "$(command -v "${script}" 2>/dev/null)"
+else
+    printf "$(expr "${0}" : '.*/\([^/]*\)'): %s\\n" "script '${script}' was not found in \$PATH" >&2
+    exit 1
 fi
