tools/: --help is considered a valid input

diff --git a/sh/tools/backup-dbs b/sh/tools/backup-dbs
--- a/sh/tools/backup-dbs
+++ b/sh/tools/backup-dbs
@@ -16,22 +16,21 @@ backup_dir=""
 
 _usage()
 {
-    printf "%s\\n" "Usage: ${progname} [options] -u USER -p PASSWD [database]..." >&2
-    printf "%s\\n" "Dump available databases." >&2
-    printf "\\n" >&2
-    printf "%s\\n" "Required arguments:" >&2
-    printf "%s\\n" "  -u user          db user"   >&2
-    printf "%s\\n" "  -p passwd        db passwd" >&2
-    printf "\\n" >&2
-    printf "%s\\n" "Optional arguments:" >&2
-    printf "%s\\n" "  -d [mysql]       database          [mysql]" >&2
-    printf "%s\\n" "  -o dir           dir to save dumps [./]" >&2
-    printf "%s\\n" "  -z [gz,bz2,xz]   compress          [gzip]" >&2
-    printf "%s\\n" "  -c config file   read options from a configuration file" >&2
-    printf "%s\\n" "  -l               list available databases" >&2
-    printf "%s\\n" "  -v               verbose mode" >&2
-    printf "%s\\n" "  -h, --help       show this help message and exit" >&2
-    exit 1
+    printf "%s\\n" "Usage: ${progname} [options] -u USER -p PASSWD [database]..."
+    printf "%s\\n" "Dump available databases."
+    printf "\\n"
+    printf "%s\\n" "Required arguments:"
+    printf "%s\\n" "  -u user          db user"
+    printf "%s\\n" "  -p passwd        db passwd"
+    printf "\\n"
+    printf "%s\\n" "Optional arguments:"
+    printf "%s\\n" "  -d [mysql]       database          [mysql]"
+    printf "%s\\n" "  -o dir           dir to save dumps [./]"
+    printf "%s\\n" "  -z [gz,bz2,xz]   compress          [gzip]"
+    printf "%s\\n" "  -c config file   read options from a configuration file"
+    printf "%s\\n" "  -l               list available databases"
+    printf "%s\\n" "  -v               verbose mode"
+    printf "%s\\n" "  -h, --help       show this help message and exit"
 }
 
 _basename()
@@ -49,9 +48,8 @@ _basename()
 
 _die()
 {
-    [ -z "${1}" ] && return 1
-    printf "%b\\n" "${*}" >&2
-    _usage
+    [ -z "${1}" ] || printf "%s\\n" "${*}" >&2
+    _usage >&2; exit 1
 }
 
 _printtime()
@@ -167,7 +165,7 @@ fi
 
 for arg; do #parse options
     case "${arg}" in
-        -h|--help) _usage  ;;
+        -h|--help) _usage && exit ;;
         -l) list="true"; shift ;;
         -v) verbose="true"; shift ;;
         '-z')
@@ -188,32 +186,30 @@ for arg; do #parse options
             if [ "${#}" -gt "1" ]; then
                 shift; user="${1}"; [ "${1}" ] && shift
             else
-                _die "Option \`${arg}' requires a parameter"
+                _die "Option '${arg}' requires a parameter"
             fi ;;
         -u*) arg=${arg#?}; arg=${arg#?}; user="${arg}"; shift ;;
         '-p')
             if [ "${#}" -gt "1" ]; then
                 shift; passwd="${1}"; [ "${1}" ] && shift
             else
-                _die "Option \`${arg}' requires a parameter"
+                _die "Option '${arg}' requires a parameter"
             fi ;;
         -p*) arg=${arg#?}; arg=${arg#?}; passwd="${arg}"; shift ;;
         -o)
             if [ "${#}" -gt "1" ]; then
                 shift; backup_dir="${1}"; [ "${1}" ] && shift
             else
-                _die "Option \`${arg}' requires a parameter"
+                _die "Option '${arg}' requires a parameter"
             fi ;;
         -c)
             if [ "${#}" -gt "1" ]; then
                 config_file="$(printf "%s " "${@}" | awk '{print $2}')"
                 shift 2
             else
-                _die "Option \`${arg}' requires a parameter"
+                _die "Option '${arg}' requires a parameter"
             fi ;;
-        -*) printf "%s\\n"
-            "${progname}: unrecognized option \`${arg}'" >&2;
-            _usage ;;
+        -*) _die "${progname}: unrecognized option '${arg}'" ;;
     esac
 done
 
@@ -226,14 +222,14 @@ if [ -z "${config_file}" ]; then
         _loadconf /etc/backup-dbs
     fi
 else
-    [ ! -f "${config_file}" ] && _die "couldn't find \`${config_file}'"
+    [ ! -f "${config_file}" ] && _die "Configuration file '${config_file}' doesn't exists"
     _loadconf "${config_file}"
 fi
 
-[ -z "${passwd}" ] && [ -z "${user}" ] && _usage
+[ -z "${passwd}" ] && [ -z "${user}" ] && _die
 case "${database}" in
     ''|mysql) database="mysql" ;;
-    *) _die "database \`${database}' unsupported" ;;
+    *) _die "database '${database}' unsupported" ;;
 esac
 [ -z "${backup_dir}" ] && backup_dir="$(pwd)"
 if ! mkdir -p "${backup_dir}"/.backup-dbs >/dev/null 2>&1; then
@@ -244,7 +240,7 @@ else
 fi
 
 if [ -z "${database}" ] || [ -z "${user}" ] || [ -z "${passwd}" ] || [ -z "${backup_dir}" ]; then
-    _usage
+    _die
 fi
 
 exec 9>/tmp/"${progname}".lock #http://mywiki.wooledge.org/BashFAQ/045
diff --git a/sh/tools/backup-remote-rsync b/sh/tools/backup-remote-rsync
--- a/sh/tools/backup-remote-rsync
+++ b/sh/tools/backup-remote-rsync
@@ -96,6 +96,35 @@ _realpath()
     fi
 }
 
+_usage()
+{
+    printf "%s\\n" "Usage: $(_basename "${0}") -r domain:/path [options] [local_dir ...]"
+    printf "%s\\n" "Backup directories to a remote system."
+    printf "\\n"
+    printf "%s\\n" "Required arguments:"
+    printf "%s\\n" "  -r domain|ip:/path     remote server"
+    printf "\\n"
+    printf "%s\\n" "Optional arguments:"
+    printf "%s\\n" "  local_dir|local_file   dirs|files to backup [${HOME}]"
+    printf "%s\\n" "  -v                     verbose"
+    printf "%s\\n" "  -s                     skip ssh auth pre-tests"
+    printf "%s\\n" "  -o                     omit executing commmands, useful with -v"
+    printf "%s\\n" "  -n                     dry run, list files to be modified"
+    printf "%s\\n" "  -u user                remote user    [${USER}]"
+    printf "%s\\n" "  -p port                remote port    [22]"
+    printf "%s\\n" "  -i ssh key             ssh public key [${HOME}/.ssh/id_rsa]"
+    printf "%s\\n" "  -l file                log file       [/tmp/$(_basename "${0}").log ]"
+    printf "%s\\n" "  -h, --help             show this help message and exit"
+    printf "\\n"
+    printf "%s\\n" "NOTE: ssh key authentication must be configured for this script to work"
+}
+
+_die()
+{
+    [ -z "${1}" ] || printf "%s\\n" "${*}" >&2
+    _usage >&2; exit 1
+}
+
 _logger()
 {
     if [ -n "${logfile}" ]; then
@@ -238,40 +267,16 @@ _backup()
         "${logfile}" "${_backup__remote_user}@${_backup__remote_server}"
 }
 
-_usage()
-{
-    printf "%s\\n" "Usage: $(_basename "${0}") -r domain:/path [options] [local_dir ...]" >&2
-    printf "%s\\n" "Backup directories to a remote system." >&2
-    printf "\\n" >&2
-    printf "%s\\n" "Required arguments:" >&2
-    printf "%s\\n" "  -r domain|ip:/path     remote server" >&2
-    printf "\\n" >&2
-    printf "%s\\n" "Optional arguments:" >&2
-    printf "%s\\n" "  local_dir|local_file   dirs|files to backup [${HOME}]" >&2
-    printf "%s\\n" "  -v                     verbose" >&2
-    printf "%s\\n" "  -s                     skip ssh auth pre-tests" >&2
-    printf "%s\\n" "  -o                     omit executing commmands, useful with -v" >&2
-    printf "%s\\n" "  -n                     dry run, list files to be modified" >&2
-    printf "%s\\n" "  -u user                remote user    [${USER}]" >&2
-    printf "%s\\n" "  -p port                remote port    [22]" >&2
-    printf "%s\\n" "  -i ssh key             ssh public key [${HOME}/.ssh/id_rsa]" >&2
-    printf "%s\\n" "  -l file                log file       [/tmp/$(_basename "${0}").log ]" >&2
-    printf "%s\\n" "  -h, --help             show this help message and exit" >&2
-    printf "\\n" >&2
-    printf "%s\\n" "NOTE: ssh key authentication must be configured for this script to work" >&2
-    exit 1
-}
-
 if [ ! -t 0 ]; then
     #there is input comming from pipe or file, add to the end of $@
     set -- "${@}" $(cat)
 fi
 
-[ "${#}" -eq "0" ] && _usage
+[ "${#}" -eq "0" ] && _die
 
 for arg; do #parse options
     case "${arg}" in
-        -h|--help) _usage  ;;
+        -h|--help) _usage && exit ;;
         -v) verbose_flag="true";   shift ;;
         -n) dryrun_flag="true";    shift ;;
         -o) ommit_flag="true";     shift ;;
@@ -280,33 +285,33 @@ for arg; do #parse options
                 remote_user="$(printf "%s " "${@}" | awk '{print $2}')"
                 shift 2
             else
-               printf "%s\\n" "Option \`${arg}' requires a parameter" >&2; _usage
+               _die "Option '${arg}' requires a parameter"
             fi ;;
         -p) if [ "${#}" -gt "1" ]; then
                 remote_port="$(printf "%s " "${@}" | awk '{print $2}')"
                 shift 2
             else
-               printf "%s\\n" "Option \`${arg}' requires a parameter" >&2; _usage
+                _die "Option '${arg}' requires a parameter"
             fi ;;
         -r) if [ "${#}" -gt "1" ]; then
                 remote_server="$(printf "%s " "${@}" | awk '{print $2}')"
                 shift 2
             else
-               printf "%s\\n" "Option \`${arg}' requires a parameter" >&2; _usage
+                _die "Option '${arg}' requires a parameter"
             fi ;;
         -i) if [ "${#}" -gt "1" ]; then
                 sshkey="$(printf "%s " "${@}" | awk '{print $2}')"
                 shift 2
             else
-               printf "%s\\n" "Option \`${arg}' requires a parameter" >&2; _usage
+                _die "Option '${arg}' requires a parameter"
             fi ;;
         -l) if [ "${#}" -gt "1" ]; then
                 logfile="$(printf "%s " "${@}" | awk '{print $2}')"
                 shift 2
             else
-               printf "%s\\n" "Option \`${arg}' requires a parameter" >&2; _usage
+                _die "Option '${arg}' requires a parameter"
             fi ;;
-        -*) printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): unrecognized option \`${arg}'" >&2; _usage ;;
+        -*) _die "$(_basename "${0}"): unrecognized option '${arg}'" ;;
     esac
 done
 
@@ -318,7 +323,7 @@ fi
 
 exec 9>/tmp/"$(_basename "${0}")".lock #verify that only one instance is running
 [ X"${LOGNAME}" = X"root" ] && chmod 666 /tmp/"$(_basename "${0}")".lock
-if ! flock -n 9  ; then              #http://mywiki.wooledge.org/BashFAQ/045
+if ! flock -n 9; then #http://mywiki.wooledge.org/BashFAQ/045
     printf "%s\\n" "$(_basename "${0}"): another instance is running";
     exit 1
 fi
@@ -328,8 +333,7 @@ fi
 [ -z "${remote_port}" ] && remote_port="22"
 
 if [ -z "${remote_server}" ]; then
-    printf "%s\\n" "$(_basename "${0}"): no remote server specified" >&2
-    _usage
+    _die "$(_basename "${0}"): no remote server specified"
 else
     if [ -z "$(printf "%s" "${remote_server}" | awk -F":" '{print $2}')" ]; then
         if [ X"${remote_user}" = X"${USER}" ]; then
@@ -379,7 +383,9 @@ if [ -z "${sshkey}" ]; then
 fi
 
 if [ -z "${skip_ssh_tests}" ]; then
-    [ -z "${sshkey}" ] && { _logger "[E]: no ssh key found!, you may try options -i or -s"; printf "\\n" >&2; _usage; }
+    [ -z "${sshkey}" ] && {
+        _logger "[E]: no ssh key found!, you may try options -i or -s"
+        printf "\\n" >&2; _usage >&2; exit 1; }
 
     remote_ip="$(printf "%s" "${remote_server}"|cut -d':' -f1)"
     ssh_auth_test="$(printf "%s %s %s %s" "ssh -o PasswordAuthentication=no"      \
@@ -391,7 +397,7 @@ if [ -z "${skip_ssh_tests}" ]; then
     if [ -z "${ommit_flag}" ]; then
         if ! eval "${ssh_auth_test}" >/dev/null 2>&1; then
             _logger "[E]: couldn't connect to remote server, wrong username/ssh key, try options -u or -s"
-            printf "\\n"; _usage
+            printf "\\n" >&2; _usage >&2; exit 1
         fi
     fi
 fi
diff --git a/sh/tools/exec-wrapper b/sh/tools/exec-wrapper
--- a/sh/tools/exec-wrapper
+++ b/sh/tools/exec-wrapper
@@ -68,12 +68,11 @@ _usage()
     printf "\\n"
     printf "%s\\n" "  -q  quiet mode"
     printf "%s\\n" "  -h  show this help message and exit"
-    exit 2
 }
 
 _die()
 {
-    printf "%s\\n" "ERROR: ${1}"
+    printf "%s\\n" "ERROR: ${1}" >&2
     [ "x${tmp}" != "x" ] && rm -rf "${tmp}"
     exit 1
 }
@@ -111,6 +110,34 @@ _seq()
         printf "%s\\n" "${_seq__first}"
         _seq__first="$((_seq__first + _seq__increment))"
     done
+}
+
+_mkdir_p() { #portable mkdir -p function
+    for _mkdir_p__dir; do
+        _mkdir_p__IFS="$IFS"
+        IFS="/"
+        set -- $_mkdir_p__dir
+        IFS="$_mkdir_p__IFS"
+        (
+        case "$_mkdir_p__dir" in
+            /*) cd /; shift ;;
+        esac
+        for _mkdir_p__subdir; do
+            [ -z "${_mkdir_p__subdir}" ] && continue
+            if [ -d "${_mkdir_p__subdir}" ] || mkdir "${_mkdir_p__subdir}"; then
+                if cd "${_mkdir_p__subdir}"; then
+                    :
+                else
+                    printf "%s\\n" "_mkdir_p: Can't enter ${_mkdir_p__subdir} while creating ${_mkdir_p__dir}"
+                    exit 1
+                fi
+            else
+                exit 1
+            fi
+        done
+        )
+    done
+    unset _mkdir_p__dir
 }
 
 #convert string to escaped octal codes
@@ -204,7 +231,7 @@ EOF
             printf "\";\n"
         done
         printf "    for (i = 1; i <= argc; ++i)\n"
-        printf "        tnew_argv[i + %s] = argv[i];\n" "${ARG_NUM}"
+        printf "        new_argv[i + %s] = argv[i];\n" "${ARG_NUM}"
 
         _gsource__argv="new_argv"
     else
@@ -223,7 +250,8 @@ EOF
 _check_utils()
 {
     for _cutils__arg; do
-    command -v "${_cutils__arg}" >/dev/null 2>&1 || _die "\"${_cutils__arg}\" is not available, aborting..."
+        command -v "${_cutils__arg}" >/dev/null 2>&1 || \
+            _die "\"${_cutils__arg}\" is not available, aborting..."
     done
 }
 
@@ -233,15 +261,28 @@ _check_utils rm od sed tr chmod install id "${CC}"
 #default owner and group.
 OWNER="$(id -un)"
 GROUP="$(id -gn)"
-
 #read command line options.
 ARG_NUM="0"
 ENV_NUM="0"
 UENV_NUM="0"
 
-while getopts "hqAEsd:m:o:g:a:e:u:" opt; do
+if [ ! -t 0 ]; then
+    #there is input comming from pipe or file, add to the end of $@
+    set -- "${@}" $(cat)
+fi
+
+[ "${#}" = "0" ] && _usage >&2 && exit 1
+
+for arg; do
+    case "${arg}" in
+        -h|--help) _usage && exit ;;
+        --*) printf "%s\\n" "Illegal option '${arg}'" >&2
+             _die "Try $(expr "${0}" : '.*/\([^/]*\)') -h" ;;
+    esac
+done
+
+while getopts "hqAEsd:m:o:g:a:e:u:" opt >&2; do
     case "${opt}" in
-        "h") _usage;;
         "q") QUIET="X";;
         "A") MODE="${MODE_A}";;
         "E") EMPTY_ENV="X";;
@@ -256,15 +297,15 @@ while getopts "hqAEsd:m:o:g:a:e:u:" opt; do
              eval ENV_$ENV_NUM=\"\${OPTARG}\" ;;
         "u") UENV_NUM="$(($UENV_NUM + 1))"
              eval UENV_$UENV_NUM=\"\${OPTARG}\" ;;
-          *) _die "Try ${0} -h";;
+          *) _die "Try $(expr "${0}" : '.*/\([^/]*\)') -h" ;;
     esac
 done
 
 shift "$(($OPTIND - 1))"
 
 if [ "${#}" -lt "1" ] || [ "${#}" -gt "2" ]; then
-    printf "%s\\n" "Invalid arguments"
-    _usage
+    printf "%s\\n" "Missing arguments" >&2
+    _usage >&2; exit 1
 fi
 
 REAL="${1}"
@@ -279,7 +320,7 @@ WRAPPER="${2}"
 #get full path to script
 real_base=$(_basename "${REAL}")
 [ "x${REAL}" = "x${real_base}" ] && REAL=$(command -v "${REAL}" )
-[ "x${REAL}" = "x" ] && _die "Executable \"${1}\" not found in \$PATH"
+[ "x${REAL}" = "x" ] && _die "Executable '${1}' not found in \$PATH"
 
 #get full path to wrapper binary
 [ "x${WRAPPER}" = "x" ] && WRAPPER=$(_basename "${REAL}" )
@@ -292,7 +333,7 @@ if [ "x${PRINT_SOURCE}" != "x" ]; then
     exit 0
 fi
 
-[ -e "${WRAPPER}" ] && _die "File \"${WRAPPER}\" already exists"
+[ -e "${WRAPPER}" ] && _die "File '${WRAPPER}' already exists"
 
 #create directory for temporary files
 tmp="$(mktemp -d exec-wrapper.XXXXXXXXXX)" || _die "Can't create temporary directory"
@@ -307,6 +348,7 @@ WRAPPER_BIN="${tmp}/wrapper"
 _generate_source "${REAL}" >"${WRAPPER_SRC}"
 ${CC} -o "${WRAPPER_BIN}" "${WRAPPER_SRC}" || _die "Can't compile wrapper"
 
+_mkdir_p "${DEST}" > /dev/null 2>&1
 #install wrapper
 install -o "${OWNER}" -g "${GROUP}" -m "${MODE}" -s \
     "${WRAPPER_BIN}" "${WRAPPER}" || _die "Can't install wrapper binary"
diff --git a/sh/tools/vim-show b/sh/tools/vim-show
--- a/sh/tools/vim-show
+++ b/sh/tools/vim-show
@@ -9,8 +9,13 @@
 
 _usage()
 {
-    printf "Usage: %s\\n" "$(expr "${0}" : '.*/\([^/]*\)') script" >&2
-    exit 1
+    printf "Usage: %s\\n" "$(expr "${0}" : '.*/\([^/]*\)') script"
+}
+
+_die()
+{
+    [ -z "${1}" ] || printf "%s\\n" "${*}" >&2
+    _usage >&2; exit 1
 }
 
 if [ ! -t 0 ]; then
@@ -18,22 +23,20 @@ if [ ! -t 0 ]; then
     set -- "${@}" $(cat)
 fi
 
-[ "${#}" -eq "0" ] && _usage
+[ "${#}" -eq "0" ] && _die
 
 for arg in "${@}"; do #parse options
     case "${arg}" in
-        -h|--help) _usage ;;
-        -*) printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): unrecognized option \`${arg}'" >&2
-            _usage ;;
+        -h|--help) _usage && exit ;;
+        -*) _die "$(expr "${0}" : '.*/\([^/]*\)'): unrecognized option '${arg}'" ;;
     esac
 done
 
 script="${1}"
 
 if command -v "${script}" >/dev/null 2>&1; then
-    [ -z "${EDITOR}" ] && { printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): variable EDITOR was not found" >&2; exit 1; } 
+    [ -z "${EDITOR}" ] && { printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): variable EDITOR was not found" >&2; exit 1; }
     ${EDITOR} "$(command -v "${script}" 2>/dev/null)"
 else
-    printf "$(expr "${0}" : '.*/\([^/]*\)'): %s\\n" "'${script}' was not found in \$PATH" >&2
-    exit 1
+    printf "$(expr "${0}" : '.*/\([^/]*\)'): %s\\n" "'${script}' was not found in \$PATH" >&2; exit 1
 fi
diff --git a/sh/tools/wget-finder b/sh/tools/wget-finder
--- a/sh/tools/wget-finder
+++ b/sh/tools/wget-finder
@@ -183,12 +183,12 @@ _wget_finder()
         _wget_finder__checktype="$(_checksum_type "${_wget_finder__checksum}")"
 
         if [ -z "${_wget_finder__checktype}" ]; then
-            printf "%s\\n" "Warning: '${_wget_finder__archive}' is an invalid FILE:CHECKSUM pair, skipping..."
+            printf "%s\\n" "Warning: '${_wget_finder__archive}' is an invalid FILE:CHECKSUM pair, skipping..." >&2
             [ X"${_wget_finder__archives}" = X"${_wget_finder__archive}" ] &&\
                 _wget_finder__archives='' || _wget_finder__archives="${_wget_finder__archives#*/}"
              _wget_finder__status="1"; continue
         elif ! _checksum "${_wget_finder__checktype}"; then
-            printf "%s\\n" "Warning: there is no way to calculate a '${_wget_finder__checktype}' checksum in your system, skipping..."
+            printf "%s\\n" "Warning: there is no way to calculate a '${_wget_finder__checktype}' checksum in your system, skipping..." >&2
             [ X"${_wget_finder__archives}" = X"${_wget_finder__archive}" ] &&\
                 _wget_finder__archives='' || _wget_finder__archives="${_wget_finder__archives#*/}"
              _wget_finder__status="1"; continue
@@ -246,7 +246,7 @@ if [ ! -t 0 ]; then
     set -- "${@}" $(cat)
 fi
 
-[ "${#}" -eq "0" ] && _usage
+[ "${#}" -eq "0" ] && _usage >&2
 
 if ! command -v "wget" >/dev/null 2>&1; then
     printf "%s\\n" "install 'wget' to run this program" >&2
@@ -266,7 +266,8 @@ for arg; do #parse options
                              exec "${0}" --list-search-engine
                          fi
                          if [ -z "$(printf "%s\\n" "${search_engines}" | tr ' ' '\n' | awk "/^$search_engine\$/")" ]; then
-                            printf "%s\\n" "${progname}: '${search_engine}' is not a recognized search engine"; exit 1
+                            printf "%s\\n" "${progname}: '${search_engine}' is not a recognized search engine" >&2
+                            exit 1
                          fi ;;
         --list-search-engine) printf "%s\\n" "${search_engines}" | tr ' ' '\n'; exit 0; ;;
         --list-checksum) printf "%s\\n" "${checksums}" | tr ' ' '\n'; exit 0; ;;
