add --detect-renamed

diff --git a/sh/tools/backup-remote-rsync b/sh/tools/backup-remote-rsync
--- a/sh/tools/backup-remote-rsync
+++ b/sh/tools/backup-remote-rsync
@@ -1,22 +1,24 @@
 #!/bin/sh
 #description: backup directories to a remote system
-#usage: backup-remote-rsync [-h|-v|-n|-o|-s|-u USER|-r DOMAIN|-i SSH KEY|-l LOGFILE] [LOCAL_DIR ...]
+#usage: backup-remote-rsync -r DOMAIN:PATH [-h|-v|-s|-o|-n|-u USER|-p PORT|-i SSH KEY|-l LOGFILE] [LOCAL_DIR ...]
 
-#example: backup-remote-rsync -v -u admin -i /home/user/.ssh/id_rsa /home/user
+#example: backup-remote-rsync -r b.javier.io:~/backup/$(hostname) -v -u admin -i /home/user/.ssh/id_rsa /home/user
+#creates backup-remote-rsync.log  root-home-user/  root-home-user.dotfiles/ inside b.javier.io:~/backup/$(hostname)
 #==================================
 #Fri May  2 00:27:38 CDT 2013
 #==================================
 #[V]: exec         : ssh -o PasswordAuthentication=no ...
 #[V]: files        : /home/user|
 #[V]: remote user  : admin
-#[V]: remote server: backup.javier.io:/home/admin/backup/sup
+#[V]: remote server: b.javier.io:~/backup/sup
+#[V]: remote port  : 22
 #[V]: ssh key      : /home/user/.ssh/id_rsa
 #[V]: log          : /tmp/backup-remote-rsync.log
 #[V]: exec         : ssh -i /home/user/.ssh/id_rsa ...
-#[V]:  
+#[V]:
 #[V]: realpath     : /home/user
 #[V]: remotepath   : root-home-user
-#[V]: exec         : rsync -avz -e "ssh -i /home/user ...
+#[V]: exec         : rsync -avz ---partial -e "ssh -i /home/user ...
 #sending incremental file list
 #deleting 05b_refusal.pdf
 #code/learn/sh/lib
@@ -106,27 +108,7 @@ _logger()
 _verbose()
 {
     [ -z "${1}" ] && return 1
-    [ -n "${verbose}" ] && _logger "[V]: ${*}"
-}
-
-_usage()
-{
-    printf "%s\\n" "Usage: $(_basename "${0}") [-h|-v|-u USER|-r DOMAIN|-i SSH KEY|-l LOGFILE] [LOCAL_DIR ...]" >&2
-    printf "\\n" >&2
-    printf "%s\\n" "optional arguments:" >&2
-    printf "%s\\n" "  LOCAL_DIR|LOCAL_FILE  dirs|files to backup [${HOME}]" >&2
-    printf "%s\\n" "  -h                    this message" >&2
-    printf "%s\\n" "  -v                    verbose" >&2
-    printf "%s\\n" "  -s                    skip ssh auth pre-tests" >&2
-    printf "%s\\n" "  -o                    omit executing commmands, useful with -v" >&2
-    printf "%s\\n" "  -n                    dry run, list files to be modified" >&2
-    printf "%s\\n" "  -u USER               remote user          [${USER}]" >&2
-    printf "%s\\n" "  -r DOMAIN|IP:/path    remote server        [backup.javier.io:${HOME}/backup/$(hostname)]" >&2
-    printf "%s\\n" "  -i SSH KEY            ssh public key       [${HOME}/.ssh/id_rsa]" >&2
-    printf "%s\\n" "  -l FILE               log file             [/tmp/$(_basename "${0}").log ]" >&2
-    printf "\\n" >&2
-    printf "%s\\n" "NOTE: Ssh key authentication must be configured for this script to work" >&2
-    exit 1
+    [ -n "${verbose_flag}" ] && _logger "[V]: ${*}"
 }
 
 _printtime()
@@ -167,16 +149,8 @@ _hasdotfiles()
 }
 
 _internetavailable()
-{   #check for internet connection, returns 0 on success, 1 otherwise
-    wget --tries=3 --timeout=5 http://www.google.com -O /tmp/index.google > /dev/null 2>&1
-
-    if [ -s /tmp/index.google ]; then
-        rm -rf /tmp/index.google
-        return 0
-    else
-        rm -rf /tmp/index.google
-        return 1
-    fi
+{
+    ping -q -w 1 -c 1 google.com >/dev/null && return 0 || return 1
 }
 
 _backup()
@@ -184,16 +158,21 @@ _backup()
     [ -z "${1}" ] && return 1 || _backup_var_files="${1}"
     [ -z "${2}" ] && return 1 || _backup_var_remote_user="${2}"
     [ -z "${3}" ] && return 1 || _backup_var_remote_server="${3}"
-    [ -z "${4}" ] && return 1 || _backup_var_sshkey="${4}"
-    [ -n "${dry_run}" ] && _backup_var_dry_run="--dry-run "
+    [ -z "${4}" ] && return 1 || _backup_var_remote_port="${4}"
+    [ -z "${5}" ] && return 1 || _backup_var_sshkey="${5}"
+    [ -n "${dryrun_flag}" ]   && _backup_var_dry_run="--dry-run"
+
+    if rsync -h | grep -- --detect-renamed >/dev/null; then
+        _backup_var_extra_flags="--detect-renamed"
+    fi
 
     _backup_var_start="$(date +%s)"
 
-    _backup_var_ssh_mkdir="$(printf "%s %s" "ssh -i ${_backup_var_sshkey}" \
+    _backup_var_ssh_mkdir="$(printf "%s %s" "ssh -p ${_backup_var_remote_port} -i ${_backup_var_sshkey}" \
         "${_backup_var_remote_user}@$(printf "%s" "${_backup_var_remote_server}" | \
-        cut -d':' -f1) mkdir -p backup/$(hostname)")"
+        cut -d':' -f1) \"mkdir backup 2>/dev/null; mkdir backup/$(hostname) 2>/dev/null\"")"
     _verbose "exec         : ${_backup_var_ssh_mkdir}"
-    [ -z "${ommit}" ] && eval "${_backup_var_ssh_mkdir}" | tee -a "${logfile}"
+    [ -z "${ommit_flag}" ] && eval "${_backup_var_ssh_mkdir}" | tee -a "${logfile}"
 
     OLDIFS="${IFS}"
     IFS="|"
@@ -212,35 +191,38 @@ _backup()
         _verbose "remotepath   : ${_backup_var_remotepath}"
 
         if [ -d "${_backup_var_realpath}" ]; then
-            _backup_var_rsync="$(printf "%s %s %s %s" "rsync ${_backup_var_dry_run}-avz"  \
-                "-e \"ssh -i ${_backup_var_sshkey}\" --one-file-system --delete"          \
-                "--exclude=\".*\" ${_backup_var_realpath}/"                               \
+            _backup_var_rsync="$(printf "%s %s %s %s %s" "rsync ${_backup_var_dry_run} -avz"  \
+                "-e \"ssh -p ${_backup_var_remote_port} -i ${_backup_var_sshkey}\" --partial" \
+                "--one-file-system --delete --exclude=.gvfs ${_backup_var_realpath}/"         \
+                "${_backup_var_extra_flags}" \
                 "${_backup_var_remote_user}@${_backup_var_remote_server}/${_backup_var_remotepath}")"
             _verbose "exec         : ${_backup_var_rsync}"
-            [ -z "${ommit}" ] && eval "${_backup_var_rsync}" | tee -a "${logfile}"
+            [ -z "${ommit_flag}" ] && eval "${_backup_var_rsync}" | tee -a "${logfile}"
 
-            if _hasdotfiles "${_backup_var_realpath}"; then
-                _backup_var_dotfiles="${_backup_var_remotepath}.dotfiles"
-                _verbose "dotfiles     : ${_backup_var_dotfiles}"
-                _backup_var_rsync="$(printf "%s %s %s %s %s" "ls ${_backup_var_realpath}"     \
-                    "| rsync ${_backup_var_dry_run}-avz -e \"ssh -i ${_backup_var_sshkey}\""  \
-                    "--one-file-system  --delete --exclude-from=-"                            \
-                    "--exclude=.gvfs ${_backup_var_realpath}/"                                \
-                    "${_backup_var_remote_user}@${_backup_var_remote_server}/${_backup_var_dotfiles}")"
-                    _verbose "exec         : ${_backup_var_rsync}"
-                    [ -z "${ommit}" ] && eval "${_backup_var_rsync}" | tee -a "${logfile}"
-            else
-                _verbose "dotfiles     : no"
-            fi
+            #TODO 07-08-2014 03:03 >> separe dotfiles
+            #if _hasdotfiles "${_backup_var_realpath}"; then
+                #_backup_var_dotfiles="${_backup_var_remotepath}.dotfiles"
+                #_verbose "dotfiles     : ${_backup_var_dotfiles}"
+                #_backup_var_rsync="$(printf "%s %s %s %s %s %s" "ls ${_backup_var_realpath}"  \
+                    #"| rsync ${_backup_var_dry_run} -avz -e "                                 \
+                    #"\"ssh -p ${_backup_var_remote_port} -i ${_backup_var_sshkey}\""          \
+                    #"--one-file-system  --delete --partial --exclude-from=-"                  \
+                    #"--exclude=.gvfs ${_backup_var_extra_flags} ${_backup_var_realpath}/"     \
+                    #"${_backup_var_remote_user}@${_backup_var_remote_server}/${_backup_var_dotfiles}")"
+                    #_verbose "exec         : ${_backup_var_rsync}"
+                    #[ -z "${ommit_flag}" ] && eval "${_backup_var_rsync}" | tee -a "${logfile}"
+            #else
+                #_verbose "dotfiles     : no"
+            #fi
         elif [ -f "${_backup_var_realpath}" ]; then
-            _backup_var_rsync="$(printf "%s %s %s %s" "rsync ${_backup_var_dry_run}-avz"  \
-               "-e \"ssh -i ${_backup_var_sshkey}\" --one-file-system --delete"           \
-               "--exclude=\".*\" ${_backup_var_realpath}"                                 \
+            _backup_var_rsync="$(printf "%s %s %s %s %s" "rsync ${_backup_var_dry_run} -avz"   \
+               "-e \"ssh -p ${_backup_var_remote_port} -i ${_backup_var_sshkey}\" --partial"   \
+               "--one-file-system --delete --partial ${_backup_var_extra_flags}"               \
+               "${_backup_var_realpath}" \
                "${_backup_var_remote_user}@${_backup_var_remote_server}/${_backup_var_remotepath}")"
             _verbose "exec         : ${_backup_var_rsync}"
-            [ -z "${ommit}" ] && eval "${_backup_var_rsync}" | tee -a "${logfile}"
+            [ -z "${ommit_flag}" ] && eval "${_backup_var_rsync}" | tee -a "${logfile}"
         fi
-
     done
 
     IFS="${OLDIFS}"
@@ -249,54 +231,79 @@ _backup()
     _backup_var_diff="$((${_backup_var_end} - ${_backup_var_start}))"
 
     _logger "$(printf "%*s\\n" "34" ''  | tr ' ' =)"
-    _logger "Total time: $(date +"%d-%m-%Y"):$(_printtime "${_backup_var_diff}")"
+    _logger "Total time: $(_printtime "${_backup_var_diff}")"
     _logger "$(printf "%*s\\n" "34" ''  | tr ' ' =)"
 
-    rsync -e "ssh -i ${_backup_var_sshkey}" "${logfile}" \
-        "${_backup_var_remote_user}@${_backup_var_remote_server}"
+    rsync -e "ssh -p ${_backup_var_remote_port} -i ${_backup_var_sshkey}" \
+        "${logfile}" "${_backup_var_remote_user}@${_backup_var_remote_server}"
 }
 
-exec 9>/tmp/"$(_basename "${0}")".lock #verify that only one instance is running
-if ! flock -n 9  ; then              #http://mywiki.wooledge.org/BashFAQ/045
-    printf "%s\\n" "$(_basename "${0}"): another instance is running";
+_usage()
+{
+    printf "%s\\n" "Usage: $(_basename "${0}") -r DOMAIN:/PATH [-h|-v|-s|-o|-n|-u USER|-p PORT|-i SSH KEY|-l LOGFILE] [LOCAL_DIR ...]" >&2
+    printf "\\n" >&2
+    printf "%s\\n" "required arguments:" >&2
+    printf "%s\\n" "  -r DOMAIN|IP:/PATH    remote server" >&2
+    printf "\\n" >&2
+    printf "%s\\n" "optional arguments:" >&2
+    printf "%s\\n" "  LOCAL_DIR|LOCAL_FILE  dirs|files to backup [${HOME}]" >&2
+    printf "%s\\n" "  -h                    this message" >&2
+    printf "%s\\n" "  -v                    verbose" >&2
+    printf "%s\\n" "  -s                    skip ssh auth pre-tests" >&2
+    printf "%s\\n" "  -o                    omit executing commmands, useful with -v" >&2
+    printf "%s\\n" "  -n                    dry run, list files to be modified" >&2
+    printf "%s\\n" "  -u USER               remote user    [${USER}]" >&2
+    printf "%s\\n" "  -p PORT               remote port    [22]" >&2
+    printf "%s\\n" "  -i SSH KEY            ssh public key [${HOME}/.ssh/id_rsa]" >&2
+    printf "%s\\n" "  -l FILE               log file       [/tmp/$(_basename "${0}").log ]" >&2
+    printf "\\n" >&2
+    printf "%s\\n" "NOTE: ssh key authentication must be configured for this script to work" >&2
     exit 1
-fi
+}
 
 if [ ! -t 0 ]; then
     #there is input comming from pipe or file, add to the end of $@
     set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
 fi
 
+[ "${#}" -eq "0" ] && _usage
+
 for var; do #parse options
     case "${var}" in
         -h) _usage ;;
-        -v) verbose="true"; shift ;;
-        -n) dry_run="true"; shift ;;
-        -o) ommit="true";   shift ;;
+        -v) verbose_flag="true";        shift ;;
+        -n) dryrun_flag="true";         shift ;;
+        -o) ommit_flag="true";          shift ;;
         -s) skip_ssh_tests="true"; shift ;;
         -u) if [ "${#}" -gt "1" ]; then
                 remote_user="$(printf "%s " "${@}" | awk '{print $2}')"
                 shift 2
             else
-               printf "%s\\n" "Option ${var} requires a parameter" >&2; exit 1
+               printf "%s\\n" "Option ${var} requires a parameter" >&2; _usage
+            fi ;;
+        -p) if [ "${#}" -gt "1" ]; then
+                remote_port="$(printf "%s " "${@}" | awk '{print $2}')"
+                shift 2
+            else
+               printf "%s\\n" "Option ${var} requires a parameter" >&2; _usage
             fi ;;
         -r) if [ "${#}" -gt "1" ]; then
                 remote_server="$(printf "%s " "${@}" | awk '{print $2}')"
                 shift 2
             else
-               printf "%s\\n" "Option ${var} requires a parameter" >&2; exit 1
+               printf "%s\\n" "Option ${var} requires a parameter" >&2; _usage
             fi ;;
         -i) if [ "${#}" -gt "1" ]; then
                 sshkey="$(printf "%s " "${@}" | awk '{print $2}')"
                 shift 2
             else
-               printf "%s\\n" "Option ${var} requires a parameter" >&2; exit 1
+               printf "%s\\n" "Option ${var} requires a parameter" >&2; _usage
             fi ;;
         -l) if [ "${#}" -gt "1" ]; then
                 logfile="$(printf "%s " "${@}" | awk '{print $2}')"
                 shift 2
             else
-               printf "%s\\n" "Option ${var} requires a parameter" >&2; exit 1
+               printf "%s\\n" "Option ${var} requires a parameter" >&2; _usage
             fi ;;
         -*) printf "%s\\n" "Unrecognized option: ${var}" >&2; exit 1 ;;
     esac
@@ -306,16 +313,34 @@ if ! command -v "rsync" >/dev/null; then
     printf "%s\\n" "you need to install 'rsync' to run this program" >&2; exit 1
 elif ! command -v "ssh" >/dev/null; then
     printf "%s\\n" "you need to install 'ssh' to run this program" >&2; exit 1
-elif ! command -v "wget" >/dev/null; then
-    printf "%s\\n" "you need to install 'wget' to run this program" >&2; exit 1
+fi
+
+exec 9>/tmp/"$(_basename "${0}")".lock #verify that only one instance is running
+if ! flock -n 9  ; then              #http://mywiki.wooledge.org/BashFAQ/045
+    printf "%s\\n" "$(_basename "${0}"): another instance is running";
+    exit 1
 fi
 
 [ -z "${logfile}" ]     && logfile="/tmp/$(_basename "${0}").log"
 [ -z "${remote_user}" ] && remote_user="${USER}"
+[ -z "${remote_port}" ] && remote_port="22"
 
-if [ -z "${ommit}" ]; then
+if [ -z "${remote_server}" ]; then
+    printf "%s\\n" "$(_basename "${0}"): no remote server specified" >&2
+    _usage
+else
+    if [ -z "$(printf "%s" "${remote_server}" | awk -F":" '{print $2}')" ]; then
+        if [ X"${remote_user}" = X"${USER}" ]; then
+            remote_server="${remote_server}:~/backup/$(hostname)"
+        else
+            remote_server="${remote_server}:/home/${remote_user}/backup/$(hostname)"
+        fi
+    fi
+fi
+
+if [ -z "${ommit_flag}" ]; then
     if ! _internetavailable; then
-        printf "%s\\n" "$(_basename "${0}"): no internet access" >&2
+        printf "%s\\n" "$(_basename "${0}"): no internet access, exiting." >&2
         exit 1
     fi
 fi
@@ -324,18 +349,10 @@ _logger "$(printf "%*s\\n" "34" ''  | tr ' ' =)"
 _logger "$(date)"
 _logger "$(printf "%*s\\n" "34" ''  | tr ' ' =)"
 
-if [ -z "${remote_server}" ]; then
-    if [ X"${remote_user}" = X"${USER}" ]; then
-        remote_server="backup.javier.io:${HOME}/backup/$(hostname)"
-    else
-        remote_server="backup.javier.io:/home/${remote_user}/backup/$(hostname)"
-    fi
-fi
-
 if [ -z "${1}" ]; then
     files="${HOME}"
 else
-    for file in "${@}"; do
+    for file; do
         [ ! -r "${file}" ] && { _logger "[W]: ${file} does not exist or is not readable, skipping"; continue; }
         files="${file}""|""${files}"
     done
@@ -360,28 +377,28 @@ if [ -z "${sshkey}" ]; then
 fi
 
 if [ -z "${skip_ssh_tests}" ]; then
-    [ -z "${sshkey}" ] && { _logger "[E]: no ssh key found!, you may try -i|-s"; printf "\\n" >&2; _usage; }
+    [ -z "${sshkey}" ] && { _logger "[E]: no ssh key found!, you may try options -i or -s"; printf "\\n" >&2; _usage; }
 
     remote_ip="$(printf "%s" "${remote_server}"|cut -d':' -f1)"
     ssh_auth_test="$(printf "%s %s %s %s" "ssh -o PasswordAuthentication=no"      \
        "-o ChallengeResponseAuthentication=no -o GSSAPIAuthentication=no"         \
-       "-o KbdInteractiveAuthentication=no -i ${sshkey}"                          \
+       "-o KbdInteractiveAuthentication=no -p ${remote_port} -i ${sshkey}"        \
        "${remote_user}@${remote_ip} ls")"
 
     _verbose "exec         : ${ssh_auth_test}"
-    if [ -z "${ommit}" ]; then
+    if [ -z "${ommit_flag}" ]; then
         if ! eval "${ssh_auth_test}" >/dev/null 2>&1; then
-            _logger "[E]: couldn't connect to remote server, wrong username|ssh key, try -u | -s"
-            printf "\\n"
-            _usage
+            _logger "[E]: couldn't connect to remote server, wrong username/ssh key, try options -u or -s"
+            printf "\\n"; _usage
         fi
     fi
-fi
+fi 
 
 _verbose "files        : ${files}"
 _verbose "remote user  : ${remote_user}"
 _verbose "remote server: ${remote_server}"
+_verbose "remote port  : ${remote_port}"
 _verbose "ssh key      : ${sshkey}"
 _verbose "log          : ${logfile}"
 
-_backup "${files}" "${remote_user}" "${remote_server}" "${sshkey}" "${logfile}"
+_backup "${files}" "${remote_user}" "${remote_server}" "${remote_port}" "${sshkey}" "${logfile}"
