make shell scripts pipe aware

diff --git a/sh/tools/bin-dpkg-rdeps b/sh/tools/bin-dpkg-rdeps
--- a/sh/tools/bin-dpkg-rdeps
+++ b/sh/tools/bin-dpkg-rdeps
@@ -8,14 +8,35 @@
 #libc6-armhf-cross
 #libc6-i386
 
-if ! command -v "apt-file" >/dev/null; then
-    printf "%s\\n" "apt-file not found: $ sudo apt-get install apt-file"
+_rdeps()
+{
+    for _rdeps_var_binary; do
+        fpath="$(command -v "${_rdeps_var_binary}")"
+        if [ -z "${fpath}" ]; then
+            fpath="${_rdeps_var_binary}"
+            [ ! -f "${fpath}" ] && continue
+        fi
+
+        if [ -n "${fpath}" ]; then
+            if ldd "${fpath}" >/dev/null 2>/dev/null; then
+                ldd "${fpath}" | sort -n | uniq | awk '{print $1}' | xargs -i apt-file search {} | cut -d':' -f1 | sort | uniq
+            else
+                printf "$(expr "${0}" : '.*/\([^/]*\)'): %s\\n" "not a dynamic executable '${fpath}'" >&2
+            fi
+        fi
+    done
+}
+
+if [ ! -t 0 ]; then
+    #there is input comming from pipe or file, add to the end of $@
+    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
+fi
+
+[ "${#}" -eq "0" ] && { printf "Usage: %s\\n" "$(expr "${0}" : '.*/\([^/]*\)') binary ..." >&2; exit 1; }
+
+if ! command -v "apt-file" >/dev/null 2>&1; then
+    printf "%s\\n" "apt-file not found: $ sudo apt-get install apt-file" >&2
     exit 1
 fi
 
-if [ "${#}" -lt "1" ]; then
-    printf "%s\\n" "usage: $(expr "${0}" : '.*/\([^/]*\)') binary"
-    exit 1
-fi
-
-ldd "$(command -v "${1}")" | sort -n | uniq | awk '{print $1}' | xargs -i apt-file search {} | cut -d':' -f1 | sort | uniq
+_rdeps "${@}"
diff --git a/sh/tools/cat-show b/sh/tools/cat-show
--- a/sh/tools/cat-show
+++ b/sh/tools/cat-show
@@ -7,16 +7,17 @@
 #code
 #...
 
+if [ ! -t 0 ]; then
+    #there is input comming from pipe or file, add to the end of $@
+    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
+fi
+
 program="${1}"
 
-_usage()
-{
-    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') program"
-    exit 0
-}
+[ "${#}" -eq "0" ] && { printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)'): program" >&2; exit 1; }
 
-[ -n "${program}" ] || _usage
-
-if command -v "${program}" 2>/dev/null; then
+if command -v "${program}" >/dev/null 2>&1; then
     less "$(command -v "${program}" 2>/dev/null)"
+else
+    printf "$(expr "${0}" : '.*/\([^/]*\)'): %s\\n" "program '${program}' was not found in PATH" >&2
 fi
diff --git a/sh/tools/compress b/sh/tools/compress
--- a/sh/tools/compress
+++ b/sh/tools/compress
@@ -9,21 +9,39 @@
 
 _basename()
 {
-    [ -z "${1}" ] && return 1
-    case "${1}" in
-        /*|*/*) expr "${1}" : '.*/\([^/]*\)' ;;
-        *) printf "%s\\n" "${1}";;
+    [ -z "${1}" ] && return 1 || _basename_var_1="${1}"
+    [ -z "${2}" ] || _basename_var_suffix="${2}"
+    case "${_basename_var_1}" in
+        /*|*/*) _basename_var_1="$(expr "${_basename_var_1}" : '.*/\([^/]*\)')" ;;
     esac
+
+    if [ -n "${_basename_var_suffix}" ] && [ "${#_basename_var_1}" -gt "${#2}" ]; then
+        if [ X"$(printf "%s" "${_basename_var_1}" | cut -c"$((${#_basename_var_1} - ${#_basename_var_suffix} + 1))")" \
+           = X"$(printf "%s" "${_basename_var_suffix}" | cut -c1)" ]; then
+            while [ "${#_basename_var_suffix}" -gt "0" ]; do
+                if [ X"$(printf "%s" "${_basename_var_1}" | cut -c"${#_basename_var_1}")" \
+                   = X"$(printf "%s" "${_basename_var_suffix}" | cut -c"${#_basename_var_suffix}")" ]; then
+                    _basename_var_1="$(printf "%s" "${_basename_var_1}" | cut -c1-"$((${#_basename_var_1} - 1))")"
+                    _basename_var_suffix_len="$((${#_basename_var_suffix} - 1))"
+                    if [ "${_basename_var_suffix_len}" -gt "0" ]; then
+                        _basename_var_suffix="$(printf "%s" "${_basename_var_suffix}" | cut -c1-"${_basename_var_suffix_len}")"
+                    else
+                        _basename_var_suffix=""
+                    fi
+                fi
+            done
+        fi
+    fi
+
+    printf "%s\\n" "${_basename_var_1}"
 }
 
 _usage()
 {
-    printf "%s\\n" "Usage: $(_basename ${0}) [-s] FILES ... FILE.[tar.gz,tar.bz2,zip...]"
-    printf "%s\\n" "           -s       quiet mode"
-    exit 0
+    printf "%s\\n" "Usage: $(_basename ${0}) [-s] FILES ... FILE.[tar.gz,tar.bz2,zip...]" >&2
+    printf "%s\\n" "           -s       quiet mode" >&2
+    exit 1
 }
-
-[ "${#}" -lt "2" ] && _usage
 
 _compress()
 {
@@ -32,7 +50,7 @@ _compress()
     for FILE; do
         i="$((${i} + 1))"
         [ "${#}" -eq "${i}" ] && continue
-        [ ! -r "${FILE}" ] && { printf "%s\\n" "$(_basename ${0}): ${FILE} does not exist or is not readable"; exit 1; }
+        [ ! -r "${FILE}" ] && { printf "%s\\n" "$(_basename ${0}): ${FILE} does not exist or is not readable" >&2; exit 1; }
         FILES="${FILE}""|""${FILES}"
     done
 
@@ -63,7 +81,8 @@ _compress()
                 for FILE in ${FILES}; do
                     x="$((${x} + 1))"
                 done
-                [ "${x}" -gt "1" ] && { printf "%s\\n" "$(_basename ${0}): bz2 files can only be compressed one by one, use tar.bz2 if you require to compress several files at the same time"; exit 1; }
+                [ "${x}" -gt "1" ] && { printf "%s\\n" \
+                    "$(_basename ${0}): bz2 files can only be compressed one by one, use tar.bz2 if you require to compress several files at the same time" >&2; exit 1; }
                 true
                 printf "%s " "[+] bzip2 -cv ${FILES_FORMAT} | dd of=${COMPRESS_FILE}"
                 printf "\\n"
@@ -79,7 +98,8 @@ _compress()
                 for FILE in ${FILES}; do
                     x="$((${x} + 1))"
                 done
-                [ "${x}" -gt "1" ] && { printf "%s\\n" "$(_basename ${0}): gz files can only be compressed one by one, use tar.gz if you require to compress several files at the same time"; exit 1; }
+                [ "${x}" -gt "1" ] && { printf "%s\\n" \
+                    "$(_basename ${0}): gz files can only be compressed one by one, use tar.gz if you require to compress several files at the same time" >&2; exit 1; }
                 true
                 printf "%s " "[+] gzip -cv ${FILES_FORMAT} | dd of=${COMPRESS_FILE}"
                 printf "\\n"
@@ -146,7 +166,8 @@ _compress()
                 for FILE in ${FILES}; do
                     x="$((${x} + 1))"
                 done
-                [ "${x}" -gt "1" ] && { printf "%s\\n" "$(_basename ${0}): bz2 files can only be compressed one by one, use tar.bz2 if you require to compress several files at the same time"; exit 1; }
+                [ "${x}" -gt "1" ] && { printf "%s\\n" \
+                    "$(_basename ${0}): bz2 files can only be compressed one by one, use tar.bz2 if you require to compress several files at the same time" >&2; exit 1; }
                 true
                 printf "%s " "[+] bzip2 -c ${FILES_FORMAT} | dd of=${COMPRESS_FILE}"
                 printf "\\n"
@@ -162,7 +183,8 @@ _compress()
                 for FILE in ${FILES}; do
                     x="$((${x} + 1))"
                 done
-                [ "${x}" -gt "1" ] && { printf "%s\\n" "$(_basename ${0}): gz files can only be compressed one by one, use tar.gz if you require to compress several files at the same time"; exit 1; }
+                [ "${x}" -gt "1" ] && { printf "%s\\n" \
+                    "$(_basename ${0}): gz files can only be compressed one by one, use tar.gz if you require to compress several files at the same time" >&2; exit 1; }
                 true
                 printf "%s " "[+] gzip -c ${FILES_FORMAT} | dd of=${COMPRESS_FILE}"
                 printf "\\n"
@@ -204,21 +226,28 @@ _compress()
                 7z a "${COMPRESS_FILE}" ${FILES}
                 ;;
             *)
-                printf "%s\\n" "'${COMPRESS_FILE}' is not a valid compressed file"
+                printf "%s\\n" "'${COMPRESS_FILE}' is not a valid compressed file" >&2
                 ;;
         esac
     fi
     IFS="${OLDIFS}"
 }
 
+if [ ! -t 0 ]; then
+    #there is input comming from pipe or file, add to the end of $@
+    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
+fi
+
+[ "${#}" -lt "2" ] && _usage
+
 while getopts ":s:" option; do
     case "${option}" in
         s) SFLAG="yes"
            shift 1; _compress "${@}"
            exit 0 ;;
-        :) printf "%s\\n" "Option -${OPTARG} requires an argument"
+        :) printf "%s\\n" "Option -${OPTARG} requires an argument" >&2
            _usage ;;
-        \?) printf "%s\\n" "Invalid option: -${OPTARG}"
+        \?) printf "%s\\n" "Invalid option: -${OPTARG}" >&2
            _usage ;;
     esac
 done
diff --git a/sh/tools/dmenu-countdown b/sh/tools/dmenu-countdown
--- a/sh/tools/dmenu-countdown
+++ b/sh/tools/dmenu-countdown
@@ -82,17 +82,37 @@ _arch()
 
 _basename()
 {
-    [ -z "${1}" ] && return 1
-    case "${1}" in
-        /*|*/*) expr "${1}" : '.*/\([^/]*\)' ;;
-        *) printf "%s\\n" "${1}";;
+    [ -z "${1}" ] && return 1 || _basename_var_1="${1}"
+    [ -z "${2}" ] || _basename_var_suffix="${2}"
+    case "${_basename_var_1}" in
+        /*|*/*) _basename_var_1="$(expr "${_basename_var_1}" : '.*/\([^/]*\)')" ;;
     esac
+
+    if [ -n "${_basename_var_suffix}" ] && [ "${#_basename_var_1}" -gt "${#2}" ]; then
+        if [ X"$(printf "%s" "${_basename_var_1}" | cut -c"$((${#_basename_var_1} - ${#_basename_var_suffix} + 1))")" \
+           = X"$(printf "%s" "${_basename_var_suffix}" | cut -c1)" ]; then
+            while [ "${#_basename_var_suffix}" -gt "0" ]; do
+                if [ X"$(printf "%s" "${_basename_var_1}" | cut -c"${#_basename_var_1}")" \
+                   = X"$(printf "%s" "${_basename_var_suffix}" | cut -c"${#_basename_var_suffix}")" ]; then
+                    _basename_var_1="$(printf "%s" "${_basename_var_1}" | cut -c1-"$((${#_basename_var_1} - 1))")"
+                    _basename_var_suffix_len="$((${#_basename_var_suffix} - 1))"
+                    if [ "${_basename_var_suffix_len}" -gt "0" ]; then
+                        _basename_var_suffix="$(printf "%s" "${_basename_var_suffix}" | cut -c1-"${_basename_var_suffix_len}")"
+                    else
+                        _basename_var_suffix=""
+                    fi
+                fi
+            done
+        fi
+    fi
+
+    printf "%s\\n" "${_basename_var_1}"
 }
 
 _isnum()
 {   #look for a number, returns 0 on success, 1 otherwise
     [ -z "${1}" ] && return 1
-    printf "%s\\n" "${@}" | grep -v "[^0-9]" >/dev/null
+    printf "%s\\n" "${@}" | grep -v "[^0-9]" >/dev/null 2>&1
 }
 
 _invalidformat()
@@ -106,13 +126,14 @@ _notify()
     [ -z "${1}" ] && return 1
     [ -z "${2}" ] && return 1
     if [ X"${TERM}" = X"linux" ] || [ -z "${TERM}" ]; then
+        kill -9 $(pgrep notify-osd) >/dev/null 2>&1
         if ! DISPLAY=:0 notify-send -t 1000 "${1}"  "${2}"; then
             if command -v "gxmessage" 2>/dev/null; then
                 font="Monaco 9"
-                gxmessage "${font:+-fn "$font"}" "${1} ${2}" "got it"
+                gxmessage "${font:+-fn "$font"}" "${1} ${2}" "ok"
             else
                 font="fixed"
-                xmessage "${font:+-fn "$font"}" "${1} ${2}" "got it"
+                xmessage "${font:+-fn "$font"}" "${1} ${2}" "ok"
             fi
         fi
     else
@@ -149,6 +170,11 @@ _printtime()
     fi
     printf "%s\\n" "${_printtime_var_hour}:${_printtime_var_min}:${_printtime_var_sec}"
 }
+
+if ! command -v "dmenu" >/dev/null 2>&1; then
+    printf "%s\\n" "dmenu was not found" >&2
+    exit 1
+fi
 
 eval "tune=\$tune_$(_arch)"
 time="$(${DMENU} <&- && printf "\\n")"
@@ -191,7 +217,7 @@ else
     fi
 fi
 
-if mount | grep /tmp | grep noexec >/dev/null; then
+if mount | grep /tmp | grep noexec >/dev/null 2>&1; then
     mkdir "${HOME}"/.dmenu_countdown
     printf "%s" "${tune}" | openssl enc -base64 -d | zcat | tar xf - -C "${HOME}"/.dmenu_countdown
     tune="${HOME}"/.dmenu_countdown/dmenu-countdown.tone
@@ -234,8 +260,8 @@ _notify "[+] ALARM" "countdown done!"
 while :; do
     if [ ! -f /tmp/dmenu-countdown.lock ]; then
         _notify "[+] Stop" "countdown stopped!"
-        killall aplay 2>/dev/null
-        killall dmenu-countdown.tone 2>/dev/null
+        killall aplay >/dev/null 2>&1
+        killall dmenu-countdown.tone >/dev/null 2>&1
         rm -rf "${HOME}"/.dmenu_countdown
         rm -rf "${tune}"
         exit
diff --git a/sh/tools/dmenu-killall b/sh/tools/dmenu-killall
--- a/sh/tools/dmenu-killall
+++ b/sh/tools/dmenu-killall
@@ -8,6 +8,12 @@
 #requires a dmenu version with xft: https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745
 #-sf red
 DMENU="dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #ffffff -sb #000000 -sf #da0000"
+
+if ! command -v "dmenu" >/dev/null 2>&1; then
+    printf "%s\\n" "dmenu was not found" >&2
+    exit 1
+fi
+
 npid="$(printf "%s\\n" "$(command ps axo command= | sed -e "s: .*::; s:.*/::; s/:$//;"  -e "s:^[[(-]::; s:[])]$::"  -e "s:^<defunct>$::")" | ${DMENU})"
 
 [ -n "${npid}" ] || exit 0
diff --git a/sh/tools/dmenu-mpd b/sh/tools/dmenu-mpd
--- a/sh/tools/dmenu-mpd
+++ b/sh/tools/dmenu-mpd
@@ -15,18 +15,18 @@ _die()
     exit 1
 }
 
-if ! command -v "dmenu" >/dev/null; then
-    printf "%s\\n" "dmenu was not found"
+if ! command -v "dmenu" >/dev/null 2>&1; then
+    printf "%s\\n" "dmenu was not found" >&2
     exit 1
 fi
 
-if ! command -v "mpc" >/dev/null; then
+if ! command -v "mpc" >/dev/null 2>&1; then
     _die "mpd was not found, press <Enter> to exit"
 fi
 
-song="$(mkfifo fifo; mpc playlist|nl -s ';' > fifo & sed -n "s@^ *\([0-9]\+\);$(mpc playlist| ${DMENU} ||printf "%s\\n" ";;;")@\1@p" fifo)"
+song="$(mkfifo /tmp/fifo; mpc playlist|nl -s ';' > /tmp/fifo & sed -n "s@^ *\([0-9]\+\);$(mpc playlist| ${DMENU} ||printf "%s\\n" ";;;")@\1@p" /tmp/fifo)"
 song="$(printf "%s\\n" "${song}" | head -1)"
-rm -rf fifo
+rm -rf /tmp/fifo
 
 if [ -z "${song}" ]; then
     exit 0;
diff --git a/sh/tools/dmenu-run b/sh/tools/dmenu-run
--- a/sh/tools/dmenu-run
+++ b/sh/tools/dmenu-run
@@ -17,12 +17,12 @@ _die()
     exit 1
 }
 
-if ! command -v "dmenu" >/dev/null; then
-    printf "%s\\n" "dmenu was not found"
+if ! command -v "dmenu" >/dev/null 2>&1; then
+    printf "%s\\n" "dmenu was not found" >&2
     exit 1
 fi
 
-if ! command -v "dmenu-path" >/dev/null; then
+if ! command -v "dmenu-path" >/dev/null 2>&1; then
     _die "dmenu-path was not found, press <Enter> to exit"
 fi
 
diff --git a/sh/tools/dmenu-tell b/sh/tools/dmenu-tell
--- a/sh/tools/dmenu-tell
+++ b/sh/tools/dmenu-tell
@@ -16,25 +16,25 @@ _die()
     exit 1
 }
 
-if ! command -v "dmenu" >/dev/null; then
-    printf "%s\\n" "dmenu was not found"
+if ! command -v "dmenu" >/dev/null 2>&1; then
+    printf "%s\\n" "dmenu was not found" >&2
     exit 1
 fi
 
-if ! command -v "say" >/dev/null; then
+if ! command -v "say" >/dev/null 2>&1; then
     _die "say script was not found, press <Enter> to exit"
 fi
 
 phrase="$(${DMENU} <&- && printf "\\n")"
 
-[ -n "${phrase}" ] || exit 0;
+[ -z "${phrase}" ] && exit 0;
 
 if [ -f "$(command -v "xclip")" ]; then
-    clipboard="/usr/bin/xclip -o"
+    clipboard="xclip -o"
 elif [ -f "$(command -v "sselp")" ]; then
-    clipboard="/usr/bin/sselp"
+    clipboard="sselp"
 else
-    clipboard="ops"
+    clipboard="echo clipboard not available"
 fi
 
 if [ X"$(printf "%s" "${phrase}" | cut -d' ' -f2)" = X"-" ]; then
diff --git a/sh/tools/dmenu-vbox b/sh/tools/dmenu-vbox
--- a/sh/tools/dmenu-vbox
+++ b/sh/tools/dmenu-vbox
@@ -12,16 +12,16 @@ DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #ffffff -sb #000000 -sf #3B5
 
 _die()
 {
-    printf "%b\\n" "$1" | ${DMENU}
+    printf "%b\\n" "${1}" | ${DMENU}
     exit 1
 }
 
-if ! command -v "dmenu" >/dev/null; then
-    printf "%s\\n" "dmenu was not found"
+if ! command -v "dmenu" >/dev/null 2>&1; then
+    printf "%s\\n" "dmenu was not found" >&2
     exit 1
 fi
 
-if ! command -v "vboxmanage" >/dev/null; then
+if ! command -v "vboxmanage" >/dev/null 2>&1; then
     _die "virtualbox was not found, press <Enter> to exit"
 fi
 
diff --git a/sh/tools/dmenu-xrandr b/sh/tools/dmenu-xrandr
--- a/sh/tools/dmenu-xrandr
+++ b/sh/tools/dmenu-xrandr
@@ -12,28 +12,29 @@ DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #FFFFFF -sb #000000 -sf #999
 
 _die()
 {
-    printf "%b%b\\n" "$1" ", press <Enter> to exit" | ${DMENU}
+    printf "%b%b\\n" "${1}" ", press <Enter> to exit" | ${DMENU}
     exit 1
 }
 
 _reload_barstatus()
 {
-    [ -z "${cmd}" ] && return 1
-    if ! command -v "conky" >/dev/null; then
+    [ -z "${1}" ] && return 1
+    if ! command -v "conky" >/dev/null 2>&1; then
         return 0
     fi
-    if ! command -v "dzen2" >/dev/null; then
+    if ! command -v "dzen2" >/dev/null 2>&1; then
         return 0
     fi
 
-    case "${cmd}" in
+    case "${1}" in
         *same*) return 0; ;;
         *) kill "$(pgrep "conky")" >/dev/null 2>&1
            kill "$(pgrep "dzen")" >/dev/null 2>&1
-           case "${cmd}" in
+           case "${1}" in
                *off*)       _x="350"; _y="749";  ;;
                *1920x1080*) _x="700"; _y="1062"; ;;
                *1600x1200*) _x="400"; _y="1000"; ;;
+               *1366x768*)  _x="350"; _y="749"; ;;
            esac
 
            conky | dzen2 -x "${_x}" -y "${_y}" -fn 'Inconsolata:size=9' -ta r -fg "#999999" -bg "#000000" & 2> /dev/null ;;
@@ -42,9 +43,9 @@ _reload_barstatus()
 
 _reload_wallpaper()
 {
-    if command -v "feh" >/dev/null; then
-        if [ -f "${HOME}"/data/images/wallpapers/sun.jpg ]; then
-            feh --bg-scale "${HOME}"/data/images/wallpapers/sun.jpg
+    if command -v "feh" >/dev/null 2>&1; then
+        if [ -f "${HOME}"/.data/images/wallpapers/sun.jpg ]; then
+            feh --bg-scale "${HOME}"/.data/images/wallpapers/sun.jpg
         fi
     fi
 }
@@ -207,13 +208,13 @@ _gen_mix_opts()
     printf "%s" "${_gen_position_opts_var_string}"
 }
 
-if ! command -v "dmenu" >/dev/null; then
-    printf "%s\\n" "dmenu was not found"
+if ! command -v "dmenu" >/dev/null 2>&1; then
+    printf "%s\\n" "dmenu was not found" >&2
     exit 1
 fi
 
-if ! command -v "xrandr" >/dev/null; then
-    _die "xrandr was not found"
+if ! command -v "xrandr" >/dev/null 2>&1; then
+    _die "xrandr was not found, press <ENTER> to exit"
 fi
 
 xrandr_output="$(xrandr)"
@@ -225,7 +226,7 @@ position="above,below,same-as,left-of,right-of"
 outputs_len="$(_arraylen "${outputs}")"
 activeoutputs_len="$(_arraylen "${activeoutputs}")"
 
-[ -z "${outputs}" ] && _die "unable to detect screen interfaces"
+[ -z "${outputs}" ] && _die "unable to detect screen interfaces, press <ENTER> to exit"
 
 #get supported modes of each output and save it to mode_$output
 outputs_copy="${outputs}"
@@ -285,4 +286,4 @@ esac
 sh -c "${cmd}"
 
 _reload_wallpaper
-_reload_barstatus
+_reload_barstatus "${cmd}"
diff --git a/sh/tools/extract b/sh/tools/extract
--- a/sh/tools/extract
+++ b/sh/tools/extract
@@ -10,12 +10,10 @@
 #http://bashscripts.org/forum/viewtopic.php?f=7&t=367
 _usage()
 {
-    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [-s] FILES ..."
-    printf "%s\\n" "           -s       quiet mode"
-    exit 0
+    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [-s] FILES ..." >&2
+    printf "%s\\n" "           -s       quiet mode" >&2
+    exit 1
 }
-
-[ "${#}" -eq "0" ] && _usage
 
 _exec()
 {
@@ -32,20 +30,20 @@ _extract()
         if [ -z "${SFLAG}" ]; then
             if [ -f "${FILE}" ] ; then
                 case "${FILE}" in
-                    *.deb|*.udeb)           _exec "ar xv '${FILE}'"               ;;
-                    *.tar.bz2|*.tbz|*.tbz2) _exec "bzcat < '${FILE}' | tar xvf -" ;;
-                    *.tar.gz|*.tgz)         _exec "zcat < '${FILE}' | tar xvf -"  ;;
-                    *.bz2)                  _exec "bunzip2 -v '${FILE}'"          ;;
-                    *.rar)                  _exec "rar x '${FILE}'"               ;;
-                    *.gz)                   _exec "gunzip -v '${FILE}'"           ;;
-                    *.tar)                  _exec "tar xvf '${FILE}'"             ;;
-                    *.zip|*.xpi)            _exec "unzip '${FILE}'"               ;;
-                    *.7z)                   _exec "7z x '${FILE}'"                ;;
-                    *.tar.lzma)             _exec "lzcat < '${FILE}' | tar xvf -" ;;
-                    *.tar.xz)               _exec "xzcat < '${FILE}' | tar xvf -" ;;
-                    *.jar)                  _exec "jar xvf '${FILE}'"             ;;
-                    *.iso)                  _exec "7z x '${FILE}'"                ;;
-                    *)  printf "%s\\n" "'${FILE}' is not a valid compressed file" ;;
+                    *.deb|*.udeb)           _exec "ar xv '${FILE}'"                   ;;
+                    *.tar.bz2|*.tbz|*.tbz2) _exec "bzcat < '${FILE}' | tar xvf -"     ;;
+                    *.tar.gz|*.tgz)         _exec "zcat < '${FILE}' | tar xvf -"      ;;
+                    *.bz2)                  _exec "bunzip2 -v '${FILE}'"              ;;
+                    *.rar)                  _exec "rar x '${FILE}'"                   ;;
+                    *.gz)                   _exec "gunzip -v '${FILE}'"               ;;
+                    *.tar)                  _exec "tar xvf '${FILE}'"                 ;;
+                    *.zip|*.xpi)            _exec "unzip '${FILE}'"                   ;;
+                    *.7z)                   _exec "7z x '${FILE}'"                    ;;
+                    *.tar.lzma)             _exec "lzcat < '${FILE}' | tar xvf -"     ;;
+                    *.tar.xz)               _exec "xzcat < '${FILE}' | tar xvf -"     ;;
+                    *.jar)                  _exec "jar xvf '${FILE}'"                 ;;
+                    *.iso)                  _exec "7z x '${FILE}'"                    ;;
+                    *)  printf "%s\\n" "'${FILE}' is not a valid compressed file" >&2 ;;
                 esac
             else
                 _usage
@@ -53,20 +51,20 @@ _extract()
         else
             if [ -f "${FILE}" ] ; then
                 case "${FILE}" in
-                    *.deb|*.udeb)           _exec "ar x '${FILE}'"               ;;
-                    *.tar.bz2|*.tbz|*.tbz2) _exec "bzcat < '${FILE}' | tar xf -" ;;
-                    *.tar.gz|*.tgz)         _exec "zcat < '${FILE}' | tar xf -"  ;;
-                    *.bz2)                  _exec "bzip2 '${FILE}'"              ;;
-                    *.rar)                  _exec "rar x '${FILE}'"              ;;
-                    *.gz)                   _exec "gunzip '${FILE}'"             ;;
-                    *.tar)                  _exec "tar xf '${FILE}'"             ;;
-                    *.zip|*.xpi)            _exec "unzip '${FILE}'"              ;;
-                    *.7z)                   _exec "7z x '${FILE}'"               ;;
-                    *.tar.lzma)             _exec "lzcat < '${FILE}' | tar xf -" ;;
-                    *.tar.xz)               _exec "xzcat < '${FILE}' | tar xf -" ;;
-                    *.jar)                  _exec "jar xf '${FILE}'"             ;;
-                    *.iso)                  _exec "7z x '${FILE}'"               ;;
-                    *) printf "%s\\n" "'${FILE}' is not a valid compressed file" ;;
+                    *.deb|*.udeb)           _exec "ar x '${FILE}'"                   ;;
+                    *.tar.bz2|*.tbz|*.tbz2) _exec "bzcat < '${FILE}' | tar xf -"     ;;
+                    *.tar.gz|*.tgz)         _exec "zcat < '${FILE}' | tar xf -"      ;;
+                    *.bz2)                  _exec "bzip2 '${FILE}'"                  ;;
+                    *.rar)                  _exec "rar x '${FILE}'"                  ;;
+                    *.gz)                   _exec "gunzip '${FILE}'"                 ;;
+                    *.tar)                  _exec "tar xf '${FILE}'"                 ;;
+                    *.zip|*.xpi)            _exec "unzip '${FILE}'"                  ;;
+                    *.7z)                   _exec "7z x '${FILE}'"                   ;;
+                    *.tar.lzma)             _exec "lzcat < '${FILE}' | tar xf -"     ;;
+                    *.tar.xz)               _exec "xzcat < '${FILE}' | tar xf -"     ;;
+                    *.jar)                  _exec "jar xf '${FILE}'"                 ;;
+                    *.iso)                  _exec "7z x '${FILE}'"                   ;;
+                    *) printf "%s\\n" "'${FILE}' is not a valid compressed file" >&2 ;;
                 esac
             else
                 _usage
@@ -75,14 +73,21 @@ _extract()
     done
 }
 
+if [ ! -t 0 ]; then
+    #there is input comming from pipe or file, add to the end of $@
+    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
+fi
+
+[ "${#}" -eq "0" ] && _usage
+
 while getopts ":s:" option; do
     case "${option}" in
         s)  SFLAG=yes
             shift 1; _extract "${@}"
             exit 0 ;;
-        :)  printf "%s\\n" "Option -${OPTARG} requires an argument"
+        :)  printf "%s\\n" "Option -${OPTARG} requires an argument" >&2
             _usage ;;
-        \?) printf "%s\\n" "Invalid option: -${OPTARG}"
+        \?) printf "%s\\n" "Invalid option: -${OPTARG}" >&2
             _usage ;;
     esac
 done
diff --git a/sh/tools/fu-search b/sh/tools/fu-search
--- a/sh/tools/fu-search
+++ b/sh/tools/fu-search
@@ -7,9 +7,6 @@
 #another one liner
 #...
 
-PATTERN="${@}"
-
-# I love colors!
 BLUE="$(printf "\\033[0;34m")"
 DEFAULT="$(printf "\\033[0;39m")"
 RED="$(printf "\\033[0;31m")"
@@ -29,31 +26,36 @@ YELLOW="$(printf "\\033[0;33m")"
 
 _usage()
 {
-    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [-c] pattern"
-    printf "\\n"
-    printf "%s\\n" "          -c     Colorize the output"
+    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [-c] pattern" >&2
+    printf "\\n" >&2
+    printf "%s\\n" "          -c     Colorize the output" >&2
     exit 0
 }
 
-[ -n "${PATTERN}" ] || _usage
+if [ ! -t 0 ]; then
+    #there is input comming from pipe or file, add to the end of $@
+    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
+fi
+
+[ "${#}" -eq "0" ] && _usage
+
+PATTERN="${@}"
 
 while getopts ":c:" option; do
     case "${option}" in
-        c)  CFLAG=yes PATTERN=$OPTARG ;;
-        :)  printf "%s\\n" "Option -$OPTARG requires an argument"
+        c)  CFLAG="yes" PATTERN="${OPTARG}" ;;
+        :)  printf "%s\\n" "Option -${OPTARG} requires an argument" >&2
             _usage ;;
-        \?) printf "%s\\n" "Invalid option: -$OPTARG"
+        \?) printf "%s\\n" "Invalid option: -${OPTARG}" >&2
             _usage ;;
     esac
 done
 
 if [ -z "${CFLAG}" ]; then
     curl -s "http://www.commandlinefu.com/commands/matching/${PATTERN}/$(printf "%s" "${PATTERN}" | base64)/plaintext/sort-by-votes" |\
-    grep --invert-match "commandlinefu.com by David Winterbottom" #I wanna keep the output as clean as possible
+    grep --invert-match "commandlinefu.com by David Winterbottom"
 else
     curl -s "http://www.commandlinefu.com/commands/matching/${PATTERN}/$(printf "%s" "${PATTERN}" | base64)/plaintext/sort-by-votes" |\
-    grep --invert-match "commandlinefu.com by David Winterbottom" | sed -e "
-            s:^#.*:${PURPLE}&${DEFAULT}:g" -e "
-            s:[^#].*:${LIGHT_GREEN}&${DEFAULT}:g" -e "
-            /#/!s/\<${PATTERN}\>/${YELLOW}&${LIGHT_GREEN}/g" #for some reason if I change / for : it doesn't work
+    grep --invert-match "commandlinefu.com by David Winterbottom" | sed -e " s:^#.*:${PURPLE}&${DEFAULT}:g" \
+    -e " s:[^#].*:${LIGHT_GREEN}&${DEFAULT}:g" -e "/#/!s/\<${PATTERN}\>/${YELLOW}&${LIGHT_GREEN}/g"
 fi
diff --git a/sh/tools/howdoi b/sh/tools/howdoi
--- a/sh/tools/howdoi
+++ b/sh/tools/howdoi
@@ -5,36 +5,29 @@
 #example: howdoi format date bash
 #DATE=`date +%Y-%m-%d`
 
-if ! command -v "wget" >/dev/null; then
-    printf "%s\\n" "wget not found: $ sudo apt-get install wget"
-    exit 1
-fi
-
 _usage()
 {
-    printf "%b\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [-h|-p POS|-a|-l|-c|-n NUM_ANSWERS|-C] QUERY ..."
-    printf "\\n"
-    printf "%b\\n" "instant coding answers via the command line"
-    printf "\\n"
-    printf "%b\\n" "positional arguments:"
-    printf "%b\\n" "  QUERY                the question to answer"
-    printf "\\n"
-    printf "%b\\n" "optional arguments:"
-    printf "%b\\n" "  -h                   show this help message and exit"
-    printf "%b\\n" "  -p POS               select answer in specified position (default: 1)"
-    printf "%b\\n" "  -a                   display all the answers in full text"
-    printf "%b\\n" "  -l                   display only the answer link"
-    printf "%b\\n" "  -c                   enable colorized output"
-    printf "%b\\n" "  -C                   clear cache"
-    printf "%b\\n" "  -n NUM_ANSWERS       number of answers to return"
-    exit
+    printf "%b\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [-h|-p POS|-a|-l|-c|-n NUM_ANSWERS|-C] QUERY ..." >&2
+    printf "\\n" >&2
+    printf "%b\\n" "instant coding answers via the command line" >&2
+    printf "\\n" >&2
+    printf "%b\\n" "positional arguments:" >&2
+    printf "%b\\n" "  QUERY                the question to answer" >&2
+    printf "\\n" >&2
+    printf "%b\\n" "optional arguments:" >&2
+    printf "%b\\n" "  -h                   show this help message and exit" >&2
+    printf "%b\\n" "  -p POS               select answer in specified position (default: 1)" >&2
+    printf "%b\\n" "  -a                   display all the answers in full text" >&2
+    printf "%b\\n" "  -l                   display only the answer link" >&2
+    printf "%b\\n" "  -c                   enable colorized output" >&2
+    printf "%b\\n" "  -C                   clear cache" >&2
+    printf "%b\\n" "  -n NUM_ANSWERS       number of answers to return" >&2
+    exit 1
 }
-
-[ "${#}" -eq "0" ] && _usage
 
 _die()
 {
-    printf "%b\\n" "$(expr "${0}" : '.*/\([^/]*\)'): ${*}"
+    printf "%b\\n" "$(expr "${0}" : '.*/\([^/]*\)'): ${*}" >&2
     exit 1
 }
 
@@ -118,18 +111,29 @@ _howdoi()
     fi
 }
 
+if [ ! -t 0 ]; then
+    #there is input comming from pipe or file, add to the end of $@
+    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
+fi
+
+[ "${#}" -eq "0" ] && _usage
+
+if ! command -v "wget" >/dev/null 2>&1; then
+    printf "%s\\n" "wget not found: $ sudo apt-get install wget" >&2
+    exit 1
+fi
+
 while getopts ":hp:alcCn:" options; do
     case "${options}" in
         h) _usage            ;;
-        p) pflag="${OPTARG}"   ;;
+        p) pflag="${OPTARG}" ;;
         a) aflag="yes"       ;;
         l) lflag="yes"       ;;
         c) cflag="yes"       ;;
-        C) rm -rf ~/.cache/howdoi && \
-           printf "%s\\n" "Cache cleared successfully"
+        C) rm -rf ~/.cache/howdoi && printf "%s\\n" "Cache cleared successfully"
            exit 0            ;;
-        n) nflag="${OPTARG}"   ;;
-        *) printf "%s\\n" "Invalid option: -${OPTARG}"
+        n) nflag="${OPTARG}" ;;
+        *) printf "%s\\n" "Invalid option: -${OPTARG}" >&2
            _usage
           ;;
     esac
diff --git a/sh/tools/rm_ b/sh/tools/rm_
--- a/sh/tools/rm_
+++ b/sh/tools/rm_
@@ -15,24 +15,22 @@
 
 trash_dir="${HOME}"/.local/share/Trash
 
-if [ "${#}" -eq "0" ] ; then # let 'rm' ouptut the usage error
-    exec rm  #our shell is replaced by /bin/rm, keeping original status unmodified
-fi
-
 _usage()
 {
-    printf "%b\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [OPTION]... FILE..."
-    printf "%b\\n" "Wrapper for the \`rm' command, compatible with nautilus|pcmanfm file managers\n"
-    printf "%b\\n" "  -l [PATTERN]   list archived files, use -ll and -lll to increase verbosity"
-    printf "%b\\n" "  -c [PATTERN]   remove permanently archived files"
-    printf "%b\\n" "  -u [PATTERN]   recover archived files"
-    printf "%b\\n" "  -y             say yes to all questions"
-    printf "%b\\n" "  -f             remove instead of archive files \`rm' is executed directly"
-    printf "%b\\n" "  -h             shows this message, use --help to obtain \`rm' help"
-    printf "%b\\n" "\n$(expr "${0}" : '.*/\([^/]*\)') deletes directories and files with no distintion therefore no -r option is needed\n"
+    printf "%b\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [OPTION]... FILE..." >&2
+    printf "%b\\n" "Wrapper for the \`rm' command, compatible with nautilus|pcmanfm file managers\n" >&2
+    printf "%b\\n" "  -l [PATTERN]   list archived files, use -ll and -lll to increase verbosity" >&2
+    printf "%b\\n" "  -c [PATTERN]   remove permanently archived files" >&2
+    printf "%b\\n" "  -u [PATTERN]   recover archived files" >&2
+    printf "%b\\n" "  -y             say yes to all questions" >&2
+    printf "%b\\n" "  -f             remove instead of archive files \`rm' is executed directly" >&2
+    printf "%b\\n" "  -h             shows this message, use --help to obtain \`rm' help" >&2
+    printf "%b\\n" "\n$(expr "${0}" : '.*/\([^/]*\)') deletes directories and files with no distintion therefore no -r option is needed\n" >&2
 
-    printf "%b\\n" "Last version is available in: <https://github.com/chilicuil/learn/tree/master/sh/tools/rm_>"
-    printf "%b\\n" "Report bugs to m@javier.io"
+    printf "%b\\n" "Last version is available in: <https://github.com/chilicuil/learn/tree/master/sh/tools/rm_>" >&2
+    printf "%b\\n" "Report bugs to m@javier.io" >&2
+
+    exit 1
 }
 
 #http://www.makkintosshu.com/journal/a-realpath-implementation-in-bash
@@ -154,31 +152,27 @@ _archive()
 {
     #TODO 08-08-2011 01:19 => report nautilus bug: recovering foo/1, foo/bar/1, foo/bar/rar/1
     #                         gives foo/1 foo/bar/1.2 foo/bar/rar/1.3
-
-    mkdir -p "${trash_dir}"/files #ensure directories exist
-    mkdir -p "${trash_dir}"/info #ensure directories exist
-
-    for file; do
-        if [ -e "${file}" ] ; then
-            archive="${trash_dir}/files/${file##*/}"
-            trashinfo="${trash_dir}/info/${file##*/}.trashinfo"
+    for _archive_var_file; do
+        if [ -e "${_archive_var_file}" ] ; then
+            archive="${trash_dir}/files/${_archive_var_file##*/}"
+            trashinfo="${trash_dir}/info/${_archive_var_file##*/}.trashinfo"
 
             num="2"
 
             while [ -e "${archive}" ]; do
-                archive="${trash_dir}/files/${file##*/}.${num}"
-                trashinfo="${trash_dir}/info/${file##*/}.${num}.trashinfo"
+                archive="${trash_dir}/files/${_archive_var_file##*/}.${num}"
+                trashinfo="${trash_dir}/info/${_archive_var_file##*/}.${num}.trashinfo"
                 num="$((${num} + 1))"
             done
 
             #put $file & $trashinfo vars between "" to capture spaces
-            printf "%s\\n" "[Trash Info]"                      >  "${trashinfo}"
-            printf "%s\\n" "Path=$(_realpath "${file}")"       >> "${trashinfo}"
-            printf "%s\\n" "DeletionDate=$(date +%Y-%m-%dT%T)" >> "${trashinfo}"
+            printf "%s\\n" "[Trash Info]"                             >  "${trashinfo}"
+            printf "%s\\n" "Path=$(_realpath "${_archive_var_file}")" >> "${trashinfo}"
+            printf "%s\\n" "DeletionDate=$(date +%Y-%m-%dT%T)"        >> "${trashinfo}"
 
-            mv "${file}" "${archive}" || rm -rf "${archive}" "${trashinfo}"
+            mv "${_archive_var_file}" "${archive}" || rm -rf "${archive}" "${trashinfo}"
         else
-            rm "${file}"
+            rm "${_archive_var_file}"
         fi
     done
 }
@@ -266,15 +260,23 @@ _clean()
     fi
 }
 
+if [ ! -t 0 ]; then
+    #there is input comming from pipe or file, add to the end of $@
+    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
+fi
+
+if [ "${#}" -eq "0" ] ; then # let 'rm' ouptut the usage error
+    exec rm  #our shell is replaced by /bin/rm, keeping original status unmodified
+fi
+
 verboselist="0"
-while getopts ":fluhcry" options
-do
+while getopts ":fluhcry" options; do
     case "${options}" in
         f) exec rm -r "${@}"                              ;;
-        l) verboselist="$((${verboselist} + 1))"     ;;  # list verbose level 1-3
-        u) shift "$((${OPTIND} - 1))"; _recover "${@}" ;;  # remove the -u
+        l) verboselist="$((${verboselist} + 1))"          ;;  # list verbose level 1-3
+        u) shift "$((${OPTIND} - 1))"; _recover "${@}"    ;;  # remove the -u
         h) _usage                                         ;;
-        c) shift "$((${OPTIND} - 1))"; _clean "${@}"   ;;  # remove the -c
+        c) shift "$((${OPTIND} - 1))"; _clean "${@}"      ;;  # remove the -c
         r)                                                ;;
         y) yflag="yes"                                    ;;
         *) exec rm "${@}"                                 ;;  # send the rest to rm
@@ -285,21 +287,18 @@ shift "$((${OPTIND} - 1))"
 
 if [ "${verboselist}" -gt "0" ]; then
     _list "${@}"
-    exit 0
+    exit
 fi
 
 # Make sure that the $trash_dir exists
-if [ ! -d "${trash_dir}" ] ; then
-    if [ ! -w "${HOME}" ] ; then
-        printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)') failed: can't create ${trash_dir} in ${HOME}" >&2
-        exit 1
-    fi
-    mkdir -p "${trash_dir}"/expunged
-    mkdir -p "${trash_dir}"/files
-    mkdir -p "${trash_dir}"/info
-    chmod -R 700 "${trash_dir}"
+if [ ! -w "${HOME}" ]; then
+    printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)') failed: can't create ${trash_dir} in ${HOME}" >&2
+    exit 1
 fi
 
-_archive "${@}"
+mkdir -p "${trash_dir}"/expunged
+mkdir -p "${trash_dir}"/files
+mkdir -p "${trash_dir}"/info
+chmod -R 700 "${trash_dir}"
 
-exit 0
+_archive "${@}"
diff --git a/sh/tools/setup b/sh/tools/setup
--- a/sh/tools/setup
+++ b/sh/tools/setup
@@ -9,12 +9,12 @@
 #Don't forget update this when adding new functions
 _usage()
 {
-  printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): setup my common tasks"
+  printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): setup my common tasks" >&2
+  printf "\\n" >&2
+  printf "%s\\n" "  autocp            cp custom autocomplete file" >&2
+  printf "%s\\n" "  script            cp custom script to the path system" >&2
   printf "\\n"
-  printf "%s\\n" "  autocp            cp custom autocomplete file"
-  printf "%s\\n" "  script            cp custom script to the path system"
-  printf "\\n"
-  exit 0
+  exit 1
 }
 
 _exec()
@@ -36,7 +36,7 @@ _script()
 
     for file; do
         _exec chmod +x "${file}"
-        _exec sudo cp "${file}" /usr/local/bin
+        _exec sudo cp -- "${file}" /usr/local/bin
     done
 
     exit 0
@@ -47,18 +47,22 @@ _autocp()
     [ -n "${1}" ] || (printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): Missing parameter, looking for an .autocp file"; exit 1)
 
     for file; do
-        _exec sudo cp "${file}" /usr/share/bash-completion/completions/
+        _exec sudo cp -- "${file}" /usr/share/bash-completion/completions/
     done
     exit 0
 }
+
+if [ ! -t 0 ]; then
+    #there is input comming from pipe or file, add to the end of $@
+    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
+fi
 
 if [ X"${#}" != X"0" ]; then
     case "${1}" in
         script) shift; _script "${@}" ;;
         autocp) shift; _autocp "${@}" ;;
-        -h | --help)    _usage ;;
-        -v | --version) printf "%s\\n" "${VERSION}" ;;
-        *) printf "%s\\n" "Error, unknown option: ${1}"
+        -h | --help)           _usage ;;
+        *) printf "%s\\n" "Error, unknown option: ${1}" >&2
            _usage ;;
     esac
 else
diff --git a/sh/tools/startx b/sh/tools/startx
--- a/sh/tools/startx
+++ b/sh/tools/startx
@@ -4,10 +4,26 @@
 
 #http://bbs.archlinux.org/viewtopic.php?pid=484915
 
+_isnum()
+{   #look for a number, returns 0 on success, 1 otherwise
+    [ -z "${1}" ] && return 1
+    printf "%s\\n" "${@}" | grep -v "[^0-9]" >/dev/null
+}
+
+if [ ! -t 0 ]; then
+    #there is input comming from pipe or file, add to the end of $@
+    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
+fi
+
 [ "${#}" -eq "0" ] && a="24" || a="${1}"
 
+if ! _isnum "${a}" ; then
+    printf "%s\\n" "Invalid number '${a}'" >&2
+    exit 1
+fi
+
 if [ "${a}" -ne "8" ] && [ "${a}" -ne "16" ] && [ "${a}" -ne "24" ]; then
-    printf "%s\\n" "Invalid color depth. Use 8, 16, or 24."
+    printf "%s\\n" "Invalid color depth. Use 8, 16, or 24." >&2
     exit 1
 fi
 
@@ -19,5 +35,5 @@ for display in 0 1 2 3 4 5; do
     fi
 done
 
-printf "%s\\n" "No displays available."
+printf "%s\\n" "No displays available." >&2
 exit 1
