sh/*: define and use the $progname variable

diff --git a/sh/tools/cat-show b/sh/tools/cat-show
--- a/sh/tools/cat-show
+++ b/sh/tools/cat-show
@@ -7,8 +7,10 @@
 #code
 #...
 
+progname="$(expr "${0}" : '.*/\([^/]*\)')"
+
 _usage() {
-    printf "Usage: %s\\n" "$(expr "${0}" : '.*/\([^/]*\)') script"
+    printf "Usage: %s\\n" "${progname} script"
 }
 
 _die() {
@@ -26,7 +28,7 @@ fi
 for arg; do #parse options
     case "${arg}" in
         -h|--help) _usage && exit ;;
-        -*) _die "$(expr "${0}" : '.*/\([^/]*\)'): unrecognized option '${arg}'" ;;
+        -*) _die "${progname}: unrecognized option '${arg}'" ;;
     esac
 done
 
@@ -35,6 +37,6 @@ script="${1}"
 if command -v "${script}" >/dev/null 2>&1; then
     less "$(command -v "${script}" 2>/dev/null)"
 else
-    printf "$(expr "${0}" : '.*/\([^/]*\)'): %s\\n" "'${script}' was not found in \$PATH" >&2
+    printf "${progname}: %s\\n" "'${script}' was not found in \$PATH" >&2
     exit 1
 fi
diff --git a/sh/tools/cpb64 b/sh/tools/cpb64
--- a/sh/tools/cpb64
+++ b/sh/tools/cpb64
@@ -8,6 +8,7 @@
 #to-a-remote-shell
 #...
 
+progname="$(expr "${0}" : '.*/\([^/]*\)')"
 decodestr="$(
 cat - <<'EOF'
 _decode64() { #decode a base64 string
@@ -77,7 +78,7 @@ EOF
 )" #'
 
 _usage() {
-    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [options] file ..."
+    printf "%s\\n" "Usage: ${progname} [options] file ..."
     printf "%s\\n" "Copy files using base64."
     printf "\\n"
     printf "%s\\n" "  -p, --portable   produce extra portable output, useful"
@@ -94,7 +95,7 @@ _die() {
 _cpb64() {
     for file; do
         [ ! -r "${file}" ] && {
-            printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): '${file}' does not exist or is not readable" >&2; exit 1; }
+            printf "%s\\n" "${progname}: '${file}' does not exist or is not readable" >&2; exit 1; }
     done
 
     if command -v "base64" >/dev/null 2>&1; then
@@ -102,7 +103,7 @@ _cpb64() {
     elif command -v "openssl" >/dev/null 2>&1; then
         str="$(tar cf - "${@}" | gzip | openssl enc -base64)"
     else
-        printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): unable to encode files, install either base64 or openssl to continue" >&2
+        printf "%s\\n" "${progname}: unable to encode files, install either base64 or openssl to continue" >&2
         exit 1
     fi
 
@@ -141,8 +142,8 @@ for arg; do #parse options
     case "${arg}" in
         -h|--help) _usage && exit ;;
         -p|--portable) portable="true"; shift
-            [ -z "${1}" ] && _die "$(expr "${0}" : '.*/\([^/]*\)'): missing parameters" ;;
-        -*) _die "$(expr "${0}" : '.*/\([^/]*\)'): unrecognized option '${arg}'" ;;
+            [ -z "${1}" ] && _die "${progname}: missing parameters" ;;
+        -*) _die "${progname}: unrecognized option '${arg}'" ;;
     esac
 done
 
