formatting

diff --git a/sh/tools/cat-show b/sh/tools/cat-show
--- a/sh/tools/cat-show
+++ b/sh/tools/cat-show
@@ -7,21 +7,25 @@
 #code
 #...
 
+_usage()
+{
+    printf "Usage: %s\\n" "$(expr "${0}" : '.*/\([^/]*\)') script" >&2
+    exit 1
+}
+
 if [ ! -t 0 ]; then
     #there is input comming from pipe or file, add to the end of $@
     set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
 fi
 
-[ "${#}" -eq "0" ] && { printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)'): script" >&2; exit 1; }
+[ "${#}" -eq "0" ] && _usage
 
 for arg; do #parse options
     case "${arg}" in
-        --) shift; break ;;
-        -h|--help) { printf "Usage: %s\\n" "$(expr "${0}" : '.*/\([^/]*\)') script" >&2; exit 1; } ;;
+        --) shift;  break ;;
+        -h|--help) _usage ;;
         -*) printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): unrecognized option \`${arg}'" >&2
-            printf "Usage: %s\\n" "$(expr "${0}" : '.*/\([^/]*\)') script" >&2
-            exit 1
-            ;;
+            _usage ;;
     esac
 done
 
@@ -30,6 +34,6 @@ script="${1}"
 if command -v "${script}" >/dev/null 2>&1; then
     less "$(command -v "${script}" 2>/dev/null)"
 else
-    printf "$(expr "${0}" : '.*/\([^/]*\)'): %s\\n" "script '${script}' was not found in \$PATH" >&2
+    printf "$(expr "${0}" : '.*/\([^/]*\)'): %s\\n" "'${script}' was not found in \$PATH" >&2
     exit 1
 fi
diff --git a/sh/tools/vim-show b/sh/tools/vim-show
--- a/sh/tools/vim-show
+++ b/sh/tools/vim-show
@@ -7,20 +7,25 @@
 #code
 #...
 
+_usage()
+{
+    printf "Usage: %s\\n" "$(expr "${0}" : '.*/\([^/]*\)') script" >&2
+    exit 1
+}
+
 if [ ! -t 0 ]; then
     #there is input comming from pipe or file, add to the end of $@
     set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
 fi
 
-[ "${#}" -eq "0" ] && { printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') script" >&2; exit 1; }
+[ "${#}" -eq "0" ] && _usage
 
 for arg in "${@}"; do #parse options
     case "${arg}" in
         --) shift; break  ;;
-        -h|--help)  { printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') script" >&2; exit 1; } ;;
+        -h|--help) _usage ;;
         -*) printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): unrecognized option \`${arg}'" >&2
-            printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') script" >&2
-            exit 1 ;;
+            _usage ;;
     esac
 done
 
@@ -30,6 +35,6 @@ if command -v "${script}" >/dev/null 2>&1; then
     [ -z "${EDITOR}" ] && { printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): variable EDITOR was not found" >&2; exit 1; } 
     ${EDITOR} "$(command -v "${script}" 2>/dev/null)"
 else
-    printf "$(expr "${0}" : '.*/\([^/]*\)'): %s\\n" "script '${script}' was not found in \$PATH" >&2
+    printf "$(expr "${0}" : '.*/\([^/]*\)'): %s\\n" "'${script}' was not found in \$PATH" >&2
     exit 1
 fi
