*sh: global variables in UPPERCASE

diff --git a/sh/tools/cat-show b/sh/tools/cat-show
--- a/sh/tools/cat-show
+++ b/sh/tools/cat-show
@@ -7,10 +7,10 @@
 #code
 #...
 
-progname="$(expr "${0}" : '.*/\([^/]*\)')"
+PROGNAME="$(expr "${0}" : '.*/\([^/]*\)')"
 
 _usage() {
-    printf "Usage: %s\\n" "${progname} script"
+    printf "Usage: %s\\n" "${PROGNAME} script"
 }
 
 _die() {
@@ -28,7 +28,7 @@ fi
 for arg in "${@}"; do #parse options
     case "${arg}" in
         -h|--help) _usage && exit ;;
-        -*) _die "${progname}: unrecognized option '${arg}'" ;;
+        -*) _die "${PROGNAME}: unrecognized option '${arg}'" ;;
     esac
 done
 
@@ -37,6 +37,6 @@ script="${1}"
 if command -v "${script}" >/dev/null 2>&1; then
     less "$(command -v "${script}" 2>/dev/null)"
 else
-    printf "${progname}: %s\\n" "'${script}' was not found in \$PATH" >&2
+    printf "${PROGNAME}: %s\\n" "'${script}' was not found in \$PATH" >&2
     exit 1
 fi
diff --git a/sh/tools/cpb64 b/sh/tools/cpb64
--- a/sh/tools/cpb64
+++ b/sh/tools/cpb64
@@ -6,8 +6,8 @@
 #example: cpb64 ~/.bashrc
 #H4sIAPzxXlkAA...  #copy and execute output to a remote shell
 
-progname="$(expr "${0}" : '.*/\([^/]*\)')"
-decodestr="$(
+PROGNAME="$(expr "${0}" : '.*/\([^/]*\)')"
+DECODE_STR="$(
 cat - <<'EOF'
 _decode64() { #decode a base64 string
     [ ! -t 0 ] && set -- "${@}" "$(cat)"
@@ -76,7 +76,7 @@ EOF
 )" #'
 
 _usage() {
-    printf "%s\\n" "Usage: ${progname} [options] file ..."
+    printf "%s\\n" "Usage: ${PROGNAME} [options] file ..."
     printf "%s\\n" "Copy files using base64."
     printf "\\n"
     printf "%s\\n" "  -p, --portable   produce extra portable output, useful"
@@ -93,7 +93,7 @@ _die() {
 _cpb64() {
     for file; do
         [ ! -r "${file}" ] && {
-            printf "%s\\n" "${progname}: '${file}' does not exist or is not readable" >&2; exit 1; }
+            printf "%s\\n" "${PROGNAME}: '${file}' does not exist or is not readable" >&2; exit 1; }
     done
 
     if command -v "base64" >/dev/null 2>&1; then
@@ -101,7 +101,7 @@ _cpb64() {
     elif command -v "openssl" >/dev/null 2>&1; then
         str="$(tar cf - "${@}" | gzip | openssl enc -base64)"
     else
-        printf "%s\\n" "${progname}: unable to encode files, install either base64 or openssl to continue" >&2
+        printf "%s\\n" "${PROGNAME}: unable to encode files, install either base64 or openssl to continue" >&2
         exit 1
     fi
 
@@ -112,20 +112,20 @@ _cpb64() {
 
     if [ -z "${portable}" ]; then
         cmd="${line1}"'\n'"${line2}"'\n'"${line3}"'\n'
-        decodestr=""
+        DECODE_STR=""
     else
         cmd='\n'"${line1p}"'\n'"${line2}"'\n'"${line3}"'\n'
     fi
 
     if command -v "xclip" >/dev/null 2>&1; then
         if [ ! -t 1 ] || [ -z "${DISPLAY}" ]; then
-            printf "%s%b" "${decodestr}" "${cmd}"
+            printf "%s%b" "${DECODE_STR}" "${cmd}"
         else
-            printf "%s%b" "${decodestr}" "${cmd}" | xclip -selection clipboard; xclip -o -selection clipboard 2>/dev/null || \
-            printf "%s%b" "${decodestr}" "${cmd}"
+            printf "%s%b" "${DECODE_STR}" "${cmd}" | xclip -selection clipboard; xclip -o -selection clipboard 2>/dev/null || \
+            printf "%s%b" "${DECODE_STR}" "${cmd}"
         fi
     else
-        printf "%s%b" "${decodestr}" "${cmd}"
+        printf "%s%b" "${DECODE_STR}" "${cmd}"
     fi
 }
 
@@ -140,8 +140,8 @@ for arg in "${@}"; do #parse options
     case "${arg}" in
         -h|--help) _usage && exit ;;
         -p|--portable) portable="true"; shift
-            [ -z "${1}" ] && _die "${progname}: missing parameters" ;;
-        -*) _die "${progname}: unrecognized option '${arg}'" ;;
+            [ -z "${1}" ] && _die "${PROGNAME}: missing parameters" ;;
+        -*) _die "${PROGNAME}: unrecognized option '${arg}'" ;;
     esac
 done
 
diff --git a/sh/tools/howdoi b/sh/tools/howdoi
--- a/sh/tools/howdoi
+++ b/sh/tools/howdoi
@@ -5,13 +5,13 @@
 #example: howdoi format date bash
 #DATE=`date +%Y-%m-%d`
 
-progname="$(expr "${0}" : '.*/\([^/]*\)')"
-search_engines="google" #TODO 13-08-2017 02:30 >> add more search engines
+PROGNAME="$(expr "${0}" : '.*/\([^/]*\)')"
+SEARCH_ENGINES="google" #TODO 13-08-2017 02:30 >> add more search engines
 
 VERSION="2017.08.13-04:08"
 
 _usage() {
-    printf "%b\\n" "Usage: ${progname} [options] query ..."
+    printf "%b\\n" "Usage: ${PROGNAME} [options] query ..."
     printf "%b\\n" "Instant coding answers via the command line."
     printf "\\n"
     printf "%b\\n" "Positional arguments:"
@@ -72,21 +72,21 @@ _die() {
 }
 
 _update() {
-    _u__current_file="$(cd "$(dirname "${0}")" && pwd)/${progname}"
+    _u__current_file="$(cd "$(dirname "${0}")" && pwd)/${PROGNAME}"
     _u__current_version_long="$(awk -F\" \
         '/VERSION=/{print $2;exit}' "${_u__current_file}" 2>/dev/null)"
     _u__current_version="$(printf "%s\\n" "${_u__current_version_long}" | \
         awk '{gsub(/[\.:]/,"");gsub(/-/,"");print;exit}' 2>/dev/null)"
     [ -z "${_u__current_version}" ] && printf "%s\\n%s\\n%s\\n"           \
         "ERROR: Failed to detect current version, please update manually" \
-        "${progname}         = ${_u__current_file}"                       \
-        "${progname} version = ${_u__current_version}" >&2 && return 1
+        "${PROGNAME}         = ${_u__current_file}"                       \
+        "${PROGNAME} version = ${_u__current_version}" >&2 && return 1
 
     command -v "wget" >/dev/null 2>&1 || command -v "curl" >/dev/null 2>&1 || \
         { printf "%s\\n" "ERROR: Install either 'wget' or 'curl' to upgrade" >&2; return 1; }
 
-    _u__url="https://raw.githubusercontent.com/javier-lopez/learn/master/sh/tools/${progname}"
-    _u__tmpfile="/tmp/${progname}.${$}.update"
+    _u__url="https://raw.githubusercontent.com/javier-lopez/learn/master/sh/tools/${PROGNAME}"
+    _u__tmpfile="/tmp/${PROGNAME}.${$}.update"
 
     _u__error_msg="$(wget -q -O- --no-check-certificate "${_u__url}" \
         > "${_u__tmpfile}" 2>&1   || curl -s "${_u__url}"  \
@@ -115,10 +115,10 @@ _update() {
                 return 1
             fi
         fi
-        printf "%s %s\\n" "${progname} is up-to-date (${_u__update_version_long})"
+        printf "%s %s\\n" "${PROGNAME} is up-to-date (${_u__update_version_long})"
         return 0
     fi
-    printf "%s %s\\n" "${progname} is up-to-date (${_u__current_version_long})"
+    printf "%s %s\\n" "${PROGNAME} is up-to-date (${_u__current_version_long})"
     rm -rf "${_u__tmpfile}"
 }
 
@@ -148,7 +148,7 @@ _get_links() {
         [ -n "${__links_content}" ] && printf "%s\\n" "${__links_content}" && return
     fi
 
-    for __search_engine in ${search_engines}; do
+    for __search_engine in ${SEARCH_ENGINES}; do
         __links_content="$(_get_links_"${__search_engine}" "${@}")"
           [ -z "${__links_content}" ] || break
     done; [ -z "${__links_content}" ] && return 1
@@ -201,7 +201,7 @@ _howdoi() {
     [ -z "${number_of_answers}" ] && number_of_answers="1"
 
     __links="$(_get_links "${@}")"
-    [ -z "${__links}" ] && { printf "%s\\n" "${progname}: No results" >&2; exit 1; }
+    [ -z "${__links}" ] && { printf "%s\\n" "${PROGNAME}: No results" >&2; exit 1; }
 
     [ "${display_only_links}" ] && printf "%s\\n" "${__links}" && exit
 
@@ -210,7 +210,7 @@ _howdoi() {
     [ -z "${__link}" ] && __link="$(printf "%s\\n" "${__links}" | awk 'END {print}')"
 
     __answers="$(_get_answers "${__link}")"
-    [ -z "${__answers}" ] && { printf "%s\\n" "${progname}: error parsing ${__link}" >&2; exit 1; }
+    [ -z "${__answers}" ] && { printf "%s\\n" "${PROGNAME}: error parsing ${__link}" >&2; exit 1; }
     __answers_len="$(printf "%s" "${__answers}" | awk '/-----/ {i++} END {print i}')"
 
     if [ "${display_all_answers}" ]; then
@@ -271,7 +271,7 @@ for arg in "${@}"; do #parse options
             else
                 _die "Option '${arg}' requires a parameter"
             fi ;;
-        -*) _die "${progname}: unrecognized option '${arg}'" ;;
+        -*) _die "${PROGNAME}: unrecognized option '${arg}'" ;;
     esac
 done
 
diff --git a/sh/tools/share-backup b/sh/tools/share-backup
--- a/sh/tools/share-backup
+++ b/sh/tools/share-backup
@@ -48,7 +48,7 @@ _num() {
 }
 
 _usage() {
-    printf "%b\\n" "Usage: ${progname} [options] [stop] [directory|file]"
+    printf "%b\\n" "Usage: ${PROGNAME} [options] [stop] [directory|file]"
     printf "%s\\n" "Share a directory over http."
     printf "\\n"
     printf "%b\\n" "  stop             stop sharing"
@@ -60,7 +60,7 @@ _usage() {
     printf "%b\\n" "  -h, --help       show this help message and exit"
 }
 
-progname="$(_basename "${0}")"
+PROGNAME="$(_basename "${0}")"
 #because of being used over ssh stdin gets blocked
 #so I'll disable reading from pipes till I figure out a solution
 #if [ ! -t 0 ]; then
@@ -104,7 +104,7 @@ for arg in "${@}"; do #parse options
             else
                 _die "Option '${arg}' requires a parameter"
             fi ;;
-        -*) _die "${progname}: unrecognized option '${arg}'" ;;
+        -*) _die "${PROGNAME}: unrecognized option '${arg}'" ;;
     esac
 done
 
@@ -113,7 +113,7 @@ if ! command -v "simple-httpd" >/dev/null 2>&1; then
     wget -q --no-check-certificate "${upstream_url_httpd}" -O- > /tmp/simple-httpd 2>/dev/null || \
     curl -s -f -L "${upstream_url_httpd}" > /tmp/simple-httpd 2>/dev/null || \
     curl -s -f -L -k "${upstream_url_httpd}" > /tmp/simple-httpd 2>/dev/null || {
-        printf "%s\\n" "${progname}: simple-httpd was not found!" >&2
+        printf "%s\\n" "${PROGNAME}: simple-httpd was not found!" >&2
         printf "%s\\n" "download it from ${upstream_url_httpd}" >&2
         exit 1
     }
@@ -123,10 +123,10 @@ else
     httpd="simple-httpd"
 fi
 
-exec 9> /tmp/"${progname}".lock #verify only one instance is running
-[ X"${LOGNAME}" = X"root" ] && chmod 666 /tmp/"${progname}".lock
+exec 9> /tmp/"${PROGNAME}".lock #verify only one instance is running
+[ X"${LOGNAME}" = X"root" ] && chmod 666 /tmp/"${PROGNAME}".lock
 if ! flock -n 9; then
-    _die "${progname}: another instance is running"
+    _die "${PROGNAME}: another instance is running"
 fi
 
 [ -z "${user}" ]   && user="guest"
@@ -157,7 +157,7 @@ fi
 printf "%s\\n"
 printf "%s\\n" "  serving:  ${files}"
 printf "%s\\n"
-printf "%s\\n" "Run: ${progname} stop, to stop sharing"
+printf "%s\\n" "Run: ${PROGNAME} stop, to stop sharing"
 
 if [ -d "${files}" ]; then
     eval "${httpd}" -p "${port}" --username="${user}" \
diff --git a/sh/tools/vim-show b/sh/tools/vim-show
--- a/sh/tools/vim-show
+++ b/sh/tools/vim-show
@@ -6,10 +6,10 @@
 #this
 #code
 #...
-progname="$(expr "${0}" : '.*/\([^/]*\)')"
+PROGNAME="$(expr "${0}" : '.*/\([^/]*\)')"
 
 _usage() {
-    printf "Usage: %s\\n" "${progname} script"
+    printf "Usage: %s\\n" "${PROGNAME} script"
 }
 
 _die() {
@@ -27,7 +27,7 @@ fi
 for arg in "${@}"; do #parse options
     case "${arg}" in
         -h|--help) _usage && exit ;;
-        -*) _die "${progname}: unrecognized option '${arg}'" ;;
+        -*) _die "${PROGNAME}: unrecognized option '${arg}'" ;;
     esac
 done
 
@@ -35,10 +35,10 @@ script="${1}"
 
 if command -v "${script}" >/dev/null 2>&1; then
     [ -z "${EDITOR}" ] && { printf "%s\\n" \
-        "${progname}: variable EDITOR was not found" >&2
+        "${PROGNAME}: variable EDITOR was not found" >&2
         exit 1; }
     ${EDITOR} "$(command -v "${script}" 2>/dev/null)"
 else
-    printf "${progname}: %s\\n" "'${script}' was not found in \$PATH" >&2
+    printf "${PROGNAME}: %s\\n" "'${script}' was not found in \$PATH" >&2
     exit 1
 fi
