cleanup, echo -> printf

diff --git a/sh/tools/compress b/sh/tools/compress
--- a/sh/tools/compress
+++ b/sh/tools/compress
@@ -9,8 +9,8 @@ _basename()
 
 _usage()
 {
-    echo "Usage: `_basename $0` [-s] FILES ... FILE.[tar.gz,tar.bz2,zip...]"
-    echo "           -s       quiet mode"
+    printf "%s\\n" "Usage: `_basename $0` [-s] FILES ... FILE.[tar.gz,tar.bz2,zip...]"
+    printf "%s\\n" "           -s       quiet mode"
     exit 0
 }
 
@@ -22,16 +22,16 @@ _exec()
     if [ X"$status" != X"0" ]; then
         exit $status
     fi
-    echo "[+] $@"
+    printf "%s\\n" "[+] $@"
     "$@"
 }
 
 _compress()
 {
     for COMPRESS_FILE; do true; done
-    FILES="${@:1:$(($#-1))}"
+    FILES="${@:1:$(expr $# - 1)}"
     for FILE in $FILES; do
-        [ ! -r "$FILE" ] && { echo "$(_basename $0): "$FILE" does not exist or is not readable"; exit 1; }
+        [ ! -r "$FILE" ] && { printf "%s\\n" "$(_basename $0): "$FILE" does not exist or is not readable"; exit 1; }
     done
 
     if [ -z "$SFLAG" ]; then
@@ -48,9 +48,9 @@ _compress()
             *.bz2)
                 local x=0
                 for FILE in $FILES; do
-                    x=$(($x+1))
+                    x=$(expr $x + 1)
                 done
-                [ $x -gt 1 ] && { echo "$(_basename $0): bz2 files can only be compressed one by one, use tar.bz2 if you require to compress several files at the same time"; exit 1; }
+                [ $x -gt 1 ] && { printf "%s\\n" "$(_basename $0): bz2 files can only be compressed one by one, use tar.bz2 if you require to compress several files at the same time"; exit 1; }
                 _exec "bunzip2 -cv \"$FILES\" | dd of=\"$COMPRESS_FILE\""
                 ;;
             *.rar)
@@ -59,9 +59,9 @@ _compress()
             *.gz)
                 local x=0
                 for FILE in $FILES; do
-                    x=$(($x+1))
+                    x=$(expr $x + 1)
                 done
-                [ $x -gt 1 ] && { echo "$(_basename $0): gz files can only be compressed one by one, use tar.gz if you require to compress several files at the same time"; exit 1; }
+                [ $x -gt 1 ] && { printf "%s\\n" "$(_basename $0): gz files can only be compressed one by one, use tar.gz if you require to compress several files at the same time"; exit 1; }
                 _exec "gunzip -cv \"$FILES\" | dd of=\"$COMPRESS_FILE\""
                 ;;
             *.tar)
@@ -86,7 +86,7 @@ _compress()
                 _exec 7z a "$COMPRESS_FILE" "$FILES"
                 ;;
             *)
-                echo "'$COMPRESS_FILE' is not a valid compressed file"
+                printf "%s\\n" "'$COMPRESS_FILE' is not a valid compressed file"
                 ;;
         esac
     else
@@ -103,9 +103,9 @@ _compress()
             *.bz2)
                 local x=0
                 for FILE in $FILES; do
-                    x=$(($x+1))
+                    x=$(expr $x + 1)
                 done
-                [ $x -gt 1 ] && { echo "$(_basename $0): bz2 files can only be compressed one by one, use tar.bz2 if you require to compress several files at the same time"; exit 1; }
+                [ $x -gt 1 ] && { printf "%s\\n" "$(_basename $0): bz2 files can only be compressed one by one, use tar.bz2 if you require to compress several files at the same time"; exit 1; }
                 _exec "bunzip2 -c \"$FILES\" | dd of=\"$COMPRESS_FILE\""
                 ;;
             *.rar)
@@ -114,9 +114,9 @@ _compress()
             *.gz)
                 local x=0
                 for FILE in $FILES; do
-                    x=$(($x+1))
+                    x=$(expr $x + 1)
                 done
-                [ $x -gt 1 ] && { echo "$(_basename $0): gz files can only be compressed one by one, use tar.gz if you require to compress several files at the same time"; exit 1; }
+                [ $x -gt 1 ] && { printf "%s\\n" "$(_basename $0): gz files can only be compressed one by one, use tar.gz if you require to compress several files at the same time"; exit 1; }
                 _exec "gunzip -c \"$FILES\" | dd of=\"$COMPRESS_FILE\""
                 ;;
             *.tar)
@@ -141,7 +141,7 @@ _compress()
                 _exec 7z a "$COMPRESS_FILE" "$FILES"
                 ;;
             *)
-                echo "'$COMPRESS_FILE' is not a valid compressed file"
+                printf "%s\\n" "'$COMPRESS_FILE' is not a valid compressed file"
                 ;;
         esac
     fi
@@ -155,11 +155,11 @@ while getopts ":s:" option; do
           exit 0
           ;;
         :)
-          echo "Option -$OPTARG requires an argument"
+          printf "%s\\n" "Option -$OPTARG requires an argument"
           _usage
           ;;
         \?)
-          echo "Invalid option: -$OPTARG"
+          printf "%s\\n" "Invalid option: -$OPTARG"
           _usage
           ;;
     esac
diff --git a/sh/tools/elastix-cli b/sh/tools/elastix-cli
--- a/sh/tools/elastix-cli
+++ b/sh/tools/elastix-cli
@@ -12,46 +12,46 @@ _basename()
 
 exec 9>/tmp/$(_basename $0).lock #verify only one instance is running
 if ! flock -n 9 ; then #http://mywiki.wooledge.org/BashFAQ/045
-    echo "$(_basename $0): another instance is running";
+    printf "%s\\n" "$(_basename $0): another instance is running";
     exit 1
 fi
 
 _usage()
 {
-    echo "Usage: $(_basename $0) [OPTION] TYPE ARGS..."
-    echo "Control Elastix through a cli interface"
-    echo
-    echo " -c                   credentials, requires a FILE string as a parameter"
-    echo " -h                   host, user@hostname.domain:port (localhost and port 22 by default)"
-    echo " -p                   ssh password (secret by default)"
-    echo " -m                   mysql passwd, (secret by default)"
-    echo " --help               prints this message"
-    echo
-    echo "trunk                 edit trunk options"
-    echo "  add                 add a trunk, requires FILE string as parameter"
-    echo "  remove              removes a trunk on ip basis, requires IP|domain string"
-    echo "  edit                edit on ip basis, requires FILE string as parameter"
-    echo
-    echo "=examples="
-    echo
-    echo "#adds a new trunk in domain.com based on definition FILE[0]"
-    echo "  $(_basename $0) -h admin@domain.com trunk add definition"
-    echo
-    echo "#removes a trunk based on [IP|domain], uses credential FILE [1] to apply changes in several machines"
-    echo "  $(_basename $0) -r credentials trunk remove domain.com"
-    echo
-    echo "#edit the IP field of an existing trunk in localhost, uses <secret> as the mysql password for the root account"
-    echo "  $(_basename $0) -m secret trunk edit x.x.x.x y.y.y.y"
-    echo
-    echo "[0] http://www.voip-info.org/wiki/view/Asterisk+config+sip.conf"
-    echo "[1] remote access is defined as: user@remotehost:port,ssh_passwd,mysql_passwd, and can be defined as many lines as desired"
+    printf "%s\\n" "Usage: $(_basename $0) [OPTION] TYPE ARGS..."
+    printf "%s\\n" "Control Elastix through a cli interface"
+    printf "\\n"
+    printf "%s\\n" " -c                   credentials, requires a FILE string as a parameter"
+    printf "%s\\n" " -h                   host, user@hostname.domain:port (localhost and port 22 by default)"
+    printf "%s\\n" " -p                   ssh password (secret by default)"
+    printf "%s\\n" " -m                   mysql passwd, (secret by default)"
+    printf "%s\\n" " --help               prints this message"
+    printf "\\n"
+    printf "%s\\n" "trunk                 edit trunk options"
+    printf "%s\\n" "  add                 add a trunk, requires FILE string as parameter"
+    printf "%s\\n" "  remove              removes a trunk on ip basis, requires IP|domain string"
+    printf "%s\\n" "  edit                edit on ip basis, requires FILE string as parameter"
+    printf "\\n"
+    printf "%s\\n" "=examples="
+    printf "\\n"
+    printf "%s\\n" "#adds a new trunk in domain.com based on definition FILE[0]"
+    printf "%s\\n" "  $(_basename $0) -h admin@domain.com trunk add definition"
+    printf "\\n"
+    printf "%s\\n" "#removes a trunk based on [IP|domain], uses credential FILE [1] to apply changes in several machines"
+    printf "%s\\n" "  $(_basename $0) -r credentials trunk remove domain.com"
+    printf "\\n"
+    printf "%s\\n" "#edit the IP field of an existing trunk in localhost, uses <secret> as the mysql password for the root account"
+    printf "%s\\n" "  $(_basename $0) -m secret trunk edit x.x.x.x y.y.y.y"
+    printf "\\n"
+    printf "%s\\n" "[0] http://www.voip-info.org/wiki/view/Asterisk+config+sip.conf"
+    printf "%s\\n" "[1] remote access is defined as: user@remotehost:port,ssh_passwd,mysql_passwd, and can be defined as many lines as desired"
     exit 0
 }
 
 _die()
 {
-    echo "$*"
-    echo "See $(_basename $0) --help"
+    printf "%s\\n" "$*"
+    printf "%s\\n" "See $(_basename $0) --help"
     exit 1
 }
 
@@ -70,18 +70,18 @@ _networkup()
 
 _isnum()
 {   #look for a number, returns 0 on success, 1 otherwise
-    echo "$@" | grep -q -v "[^0-9]"
+    printf "%s\\n" "$@" | grep -q -v "[^0-9]"
 }
 
 _haswhitespaces()
 {
-    grep -qs " " "$@"
+    grep " " "$@" >/dev/null
 }
 
 _decode64()
 {
-    [ -z "$1" ] && echo ""
-    echo "$1" | base64 --decode
+    [ -z "$1" ] && printf "\\n"
+    printf "%s\\n" "$1" | base64 --decode
 }
 
 _isip4valid()
@@ -100,7 +100,7 @@ _isip4valid()
 
 _isdomainvalid()
 {   #return 0 if parameter is a valid domain address, non-zero otherwise
-    echo "$@" | grep -Pqs '(?=^.{5,254}$)(^(?:(?!\d+\.)[a-zA-Z0-9_\-]{1,63}\.?)+(?:[a-zA-Z]{2,})$)'
+    printf "%s\\n" "$@" | grep -P '(?=^.{5,254}$)(^(?:(?!\d+\.)[a-zA-Z0-9_\-]{1,63}\.?)+(?:[a-zA-Z]{2,})$)' >/dev/null
 }
 
 _elastixfileformatisvalid()
@@ -193,7 +193,7 @@ _trunk()
         [ ! -f "$elastix_credentials" ] && _die "Not a file: $elastix_credentials"
 
         #we're sendying sensitive data to elastix instances, let's try to verify if our credentials are correct
-        echo "Verifying credentials defined in $elastix_credentials ..."
+        printf "%s\\n" "Verifying credentials defined in $elastix_credentials ..."
         if _haswhitespaces "$elastix_credentials" ; then
             _die "$elastix_credentials doesn't contain a valid format"
         fi
@@ -202,12 +202,12 @@ _trunk()
         while IFS=',' read -r <&3 elastix_ssh_host elastix_ssh_passwd elastix_mysql_passwd JUNK; do
             [ -n "$JUNK" ] && _die "$elastix_credentials doesn't contain a valid format"
 
-            if _isnum $(echo "$elastix_ssh_host" | cut -f2 -d:) ; then
-                elastix_ssh_port=$(echo "$elastix_ssh_host" | cut -f2 -d:)
+            if _isnum $(printf "%s\\n" "$elastix_ssh_host" | cut -f2 -d:) ; then
+                elastix_ssh_port=$(printf "%s\\n" "$elastix_ssh_host" | cut -f2 -d:)
             else
                 elastix_ssh_port=22
             fi
-            elastix_ssh_host=$(echo "$elastix_ssh_host" | cut -f1 -d:)
+            elastix_ssh_host=$(printf "%s\\n" "$elastix_ssh_host" | cut -f1 -d:)
 
             [ -z "$elastix_ssh_passwd" ] && elastix_ssh_passwd=$(_decode64 "$default_ssh_passwd")
             [ -z "$elastix_mysql_passwd" ] && elastix_mysql_passwd=$(_decode64 "$default_mysql_passwd")
@@ -223,12 +223,12 @@ _trunk()
         elastix_mysql_passwd_array=()
 
         while IFS=',' read -r <&4 elastix_ssh_host elastix_ssh_passwd elastix_mysql_passwd; do
-            if _isnum $(echo "$elastix_ssh_host" | cut -f2 -d:) ; then
-                elastix_ssh_port=$(echo "$elastix_ssh_host" | cut -f2 -d:)
+            if _isnum $(printf "%s\\n" "$elastix_ssh_host" | cut -f2 -d:) ; then
+                elastix_ssh_port=$(printf "%s\\n" "$elastix_ssh_host" | cut -f2 -d:)
             else
                 elastix_ssh_port=22
             fi
-            elastix_ssh_host=$(echo "$elastix_ssh_host" | cut -f1 -d:)
+            elastix_ssh_host=$(printf "%s\\n" "$elastix_ssh_host" | cut -f1 -d:)
 
             [ -z "$elastix_ssh_passwd" ] && elastix_ssh_passwd=$(_decode64 "$default_ssh_passwd")
             [ -z "$elastix_mysql_passwd" ] && elastix_mysql_passwd=$(_decode64 "$default_mysql_passwd")
@@ -239,18 +239,18 @@ _trunk()
             elastix_mysql_passwd_array+=("$elastix_mysql_passwd")
         done 4< "$elastix_credentials"
     else
-        echo "Verifying credentials ..."
+        printf "%s\\n" "Verifying credentials ..."
 
         [ -z "$elastix_ssh_host" ] && elastix_ssh_host=localhost
         [ -z "$elastix_ssh_passwd" ] && elastix_ssh_passwd=$(_decode64 "$default_ssh_passwd")
         [ -z "$elastix_mysql_passwd" ] && elastix_mysql_passwd=$(_decode64 "$default_mysql_passwd")
 
-        if _isnum $(echo "$elastix_ssh_host" | cut -f2 -d:) ; then
-            elastix_ssh_port=$(echo "$elastix_ssh_host" | cut -f2 -d:)
+        if _isnum $(printf "%s\\n" "$elastix_ssh_host" | cut -f2 -d:) ; then
+            elastix_ssh_port=$(printf "%s\\n" "$elastix_ssh_host" | cut -f2 -d:)
         else
             elastix_ssh_port=22
         fi
-        elastix_ssh_host=$(echo "$elastix_ssh_host" | cut -f1 -d:)
+        elastix_ssh_host=$(printf "%s\\n" "$elastix_ssh_host" | cut -f1 -d:)
 
         if ! sshpass -p $elastix_ssh_passwd ssh -o StrictHostKeyChecking=no -o Port=$elastix_ssh_port $elastix_ssh_host "mysql -uroot -p$elastix_mysql_passwd -e 'use asterisk'" ; then
             _die "$elastix_credentials: invalid credentials for $elastix_ssh_host"
@@ -268,8 +268,8 @@ _trunk()
             remote_db=""
             remote_db=$(sshpass -p ${elastix_ssh_passwd_array[${i}]} ssh -o StrictHostKeyChecking=no -o Port=${elastix_ssh_port_array[${1}]} ${elastix_ssh_host_array[${i}]} "mysqldump -p${elastix_mysql_passwd_array[${i}]} asterisk --extended=FALSE")
 
-            if $(echo "$remote_db" | grep "$elastix_format_host" | grep -qs "host"); then
-                id=$(echo "$remote_db" | grep "$elastix_format_host" | grep "host" | cut -f1 -d"," | cut -f2 -d"(" | tr -d "'")
+            if $(printf "%s\\n" "$remote_db" | grep "$elastix_format_host" | grep "host" >/dev/null); then
+                id=$(printf "%s\\n" "$remote_db" | grep "$elastix_format_host" | grep "host" | cut -f1 -d"," | cut -f2 -d"(" | tr -d "'")
                 [ -z "$id" ] && _die "internal error: id column wasn't found on -asterisk- db, probably elastix system is broken"
 
                 trunk_name=$(sshpass -p ${elastix_ssh_passwd_array[${i}]} ssh -o StrictHostKeyChecking=no -o Port=${elastix_ssh_port_array[${1}]} ${elastix_ssh_host_array[${i}]} "mysql asterisk -p${elastix_mysql_passwd_array[${i}]} -se \"SELECT data FROM sip WHERE id=\\\"$id\\\" AND flags=\"2\";\"")
@@ -278,17 +278,17 @@ _trunk()
                 trunk_id=$(sshpass -p ${elastix_ssh_passwd_array[${i}]} ssh -o StrictHostKeyChecking=no -o Port=${elastix_ssh_port_array[${1}]} ${elastix_ssh_host_array[${i}]} "mysql asterisk -p${elastix_mysql_passwd_array[${i}]} -se \"SELECT trunkid FROM trunks WHERE name=\\\"$trunk_name\\\";\"")
                 [ -z "$trunk_name" ] && _die "internal error: data column wasn't found on -asterisk- db, probably elastix system is broken"
 
-                echo "$elastix_format_host is already declared in trunk $trunk_name, skipping ..."
+                printf "%s\\n" "$elastix_format_host is already declared in trunk $trunk_name, skipping ..."
             else
-                if $(echo "$remote_db" | grep "$elastix_format_trunk" | grep -qs "account"); then
-                    echo "$elastix_format_trunk is already declared as trunk, use another trunk name, skipping ..."
+                if $(printf "%s\\n" "$remote_db" | grep "$elastix_format_trunk" | grep "account" >/dev/null); then
+                    printf "%s\\n" "$elastix_format_trunk is already declared as trunk, use another trunk name, skipping ..."
                 else
-                    echo "adding new $elastix_format_trunk trunk ..."
+                    printf "%s\\n" "adding new $elastix_format_trunk trunk ..."
 
                     higher_trunk_id=$(sshpass -p ${elastix_ssh_passwd_array[${i}]} ssh -o StrictHostKeyChecking=no -o Port=${elastix_ssh_port_array[${1}]} ${elastix_ssh_host_array[${i}]} "mysql asterisk -p${elastix_mysql_passwd_array[${i}]} -se \"SELECT trunkid FROM trunks;\"")
                     [ -z "$higher_trunk_id" ] && _die "internal error: trunkid column wasn't found on -asterisk- db, probably elastix system is broken"
-                    higher_trunk_id=$(echo "$higher_trunk_id" | tail -1)
-                    higher_trunk_id=$((higher_trunk_id+1)) #define next trunk
+                    higher_trunk_id=$(printf "%s\\n" "$higher_trunk_id" | tail -1)
+                    higher_trunk_id=$(expr higher_trunk_id + 1) #define next trunk
 
                     if ! sshpass -p ${elastix_ssh_passwd_array[${i}]} ssh -o StrictHostKeyChecking=no -o Port=${elastix_ssh_port_array[${1}]} ${elastix_ssh_host_array[${i}]} "mysql asterisk -p${elastix_mysql_passwd_array[${i}]} -se \"
                         INSERT INTO trunks VALUES ($higher_trunk_id,'$elastix_format_trunk','sip','','off','','','','$elastix_format_trunk','','','off');
@@ -333,10 +333,10 @@ _trunk()
             remote_db=""
             remote_db=$(sshpass -p ${elastix_ssh_passwd_array[${i}]} ssh -o StrictHostKeyChecking=no -o Port=${elastix_ssh_port_array[${1}]} ${elastix_ssh_host_array[${i}]} "mysqldump -p${elastix_mysql_passwd_array[${i}]} asterisk --extended=FALSE")
 
-            if ! $(echo "$remote_db" | grep "$2" | grep -qs "host"); then
-                echo "$2 not found, skipping ..."
+            if ! $(printf "%s\\n" "$remote_db" | grep "$2" | grep "host" >/dev/null); then
+                printf "%s\\n" "$2 not found, skipping ..."
             else
-                id=$(echo "$remote_db" | grep "$2" | grep "host" | cut -f1 -d"," | cut -f2 -d"(" | tr -d "'")
+                id=$(printf "%s\\n" "$remote_db" | grep "$2" | grep "host" | cut -f1 -d"," | cut -f2 -d"(" | tr -d "'")
                 [ -z "$id" ] && _die "internal error: id column wasn't found on -asterisk- db, probably elastix system is broken"
 
                 trunk_name=$(sshpass -p ${elastix_ssh_passwd_array[${i}]} ssh -o StrictHostKeyChecking=no -o Port=${elastix_ssh_port_array[${1}]} ${elastix_ssh_host_array[${i}]} "mysql asterisk -p${elastix_mysql_passwd_array[${i}]} -se \"SELECT data FROM sip WHERE id=\\\"$id\\\" AND flags=\"2\";\"")
@@ -345,9 +345,9 @@ _trunk()
                 trunk_id=$(sshpass -p ${elastix_ssh_passwd_array[${i}]} ssh -o StrictHostKeyChecking=no -o Port=${elastix_ssh_port_array[${1}]} ${elastix_ssh_host_array[${i}]} "mysql asterisk -p${elastix_mysql_passwd_array[${i}]} -se \"SELECT trunkid FROM trunks WHERE name=\\\"$trunk_name\\\";\"")
                 [ -z "$trunk_name" ] && _die "internal error: data column wasn't found on -asterisk- db, probably elastix system is broken"
 
-                id_reg=$(echo "$remote_db" | grep "register" | grep "tr-reg-$trunk_id" | cut -f1 -d"," | cut -f2 -d"(" | tr -d "'")
+                id_reg=$(printf "%s\\n" "$remote_db" | grep "register" | grep "tr-reg-$trunk_id" | cut -f1 -d"," | cut -f2 -d"(" | tr -d "'")
 
-                echo "$2 is trunk $trunk_name deleting ..."
+                printf "%s\\n" "$2 is trunk $trunk_name deleting ..."
 
                 if ! sshpass -p ${elastix_ssh_passwd_array[${i}]} ssh -o StrictHostKeyChecking=no -o Port=${elastix_ssh_port_array[${1}]} ${elastix_ssh_host_array[${i}]} "mysql asterisk -p${elastix_mysql_passwd_array[${i}]} -se \"DELETE FROM sip WHERE id=\\\"$id\\\";\"" ; then
                     _die "Error deleting trunk $trunk_name, review manually the -asterisk- database"
@@ -382,10 +382,10 @@ _trunk()
             remote_db=""
             remote_db=$(sshpass -p ${elastix_ssh_passwd_array[${i}]} ssh -o StrictHostKeyChecking=no -o Port=${elastix_ssh_port_array[${1}]} ${elastix_ssh_host_array[${i}]} "mysqldump -p${elastix_mysql_passwd_array[${i}]} asterisk --extended=FALSE")
 
-            if ! $(echo "$remote_db" | grep "$2" | grep -qs "host"); then
-                echo "$2 not found, skipping ..."
+            if ! $(printf "%s\\n" "$remote_db" | grep "$2" | grep "host" >/dev/null); then
+                printf "%s\\n" "$2 not found, skipping ..."
             else
-                id=$(echo "$remote_db" | grep "$2" | grep "host" | cut -f1 -d"," | cut -f2 -d"(" | tr -d "'")
+                id=$(printf "%s\\n" "$remote_db" | grep "$2" | grep "host" | cut -f1 -d"," | cut -f2 -d"(" | tr -d "'")
                 [ -z "$id" ] && _die "internal error: id column wasn't found on -asterisk- db, probably elastix system is broken"
 
                 trunk_name=$(sshpass -p ${elastix_ssh_passwd_array[${i}]} ssh -o StrictHostKeyChecking=no -o Port=${elastix_ssh_port_array[${1}]} ${elastix_ssh_host_array[${i}]} "mysql asterisk -p${elastix_mysql_passwd_array[${i}]} -se \"SELECT data FROM sip WHERE id=\\\"$id\\\" AND flags=\"2\";\"")
@@ -394,7 +394,7 @@ _trunk()
                 trunk_id=$(sshpass -p ${elastix_ssh_passwd_array[${i}]} ssh -o StrictHostKeyChecking=no -o Port=${elastix_ssh_port_array[${1}]} ${elastix_ssh_host_array[${i}]} "mysql asterisk -p${elastix_mysql_passwd_array[${i}]} -se \"SELECT trunkid FROM trunks WHERE name=\\\"$trunk_name\\\";\"")
                 [ -z "$trunk_name" ] && _die "internal error: data column wasn't found on -asterisk- db, probably elastix system is broken"
 
-                echo "$2 is trunk $trunk_name, changing host to $3 ..."
+                printf "%s\\n" "$2 is trunk $trunk_name, changing host to $3 ..."
 
                 if ! sshpass -p ${elastix_ssh_passwd_array[${i}]} ssh -o StrictHostKeyChecking=no -o Port=${elastix_ssh_port_array[${1}]} ${elastix_ssh_host_array[${i}]} "mysql asterisk -p${elastix_mysql_passwd_array[${i}]} -se \"UPDATE sip SET data=\\\"$3\\\" WHERE data=\\\"$2\\\";\"" ; then
                     _die "Error editing trunk $trunk_name, review manually the -asterisk- database"
@@ -458,7 +458,7 @@ for var in "$@"; do #parse options
 done
 
 if ! _networkup; then
-    echo "$(_basename $0): network not detected, exiting..."
+    printf "%s\\n" "$(_basename $0): network not detected, exiting..."
     exit 1
 fi
 
diff --git a/sh/tools/mkpass b/sh/tools/mkpass
--- a/sh/tools/mkpass
+++ b/sh/tools/mkpass
@@ -7,16 +7,16 @@ else
     #isnum?
     #http://stackoverflow.com/questions/806906/how-do-i-test-if-a-variable-is-a-number-in-bash
     case $1 in
-        ''|*[!0-9]*) echo Error, not a number:\"$1\";exit 1;;
+        ''|*[!0-9]*) printf "%s\\n" "Error, not a number: $1"; exit 1;;
         *) mkpasswd_length=$1;;
     esac
 fi
 
 if [ -f /usr/bin/xclip ]; then
     #http://unix.stackexchange.com/questions/28503/how-can-i-send-stdout-to-multiple-commands
-    strings /dev/urandom | grep -o '[[:alnum:]]' | head -n $mkpasswd_length | tr -d '\n' | tee >(xclip); echo
+    strings /dev/urandom | grep -o '[[:alnum:]]' | head -n $mkpasswd_length | tr -d '\n' | tee >(xclip); printf "\\n"
 else
-    strings /dev/urandom | grep -o '[[:alnum:]]' | head -n $mkpasswd_length | tr -d '\n'; echo
+    strings /dev/urandom | grep -o '[[:alnum:]]' | head -n $mkpasswd_length | tr -d '\n'; printf "\\n"
 fi
 
 exit 0
diff --git a/sh/tools/movietime b/sh/tools/movietime
--- a/sh/tools/movietime
+++ b/sh/tools/movietime
@@ -10,24 +10,24 @@ _die()
 {   #print a stacktrace with a msg, exits with 1
     local frame=0
     while caller $frame; do
-        $((frame=frame+1));
+        frame=$(expr $frame + 1);
     done
 
-    echo "$*"
+    printf "%s\\n" "$*"
     exit 1
 }
 
 _ismonitorattached()
 {
-    xrandr | grep "^VGA" | grep -qs " connected" && return 0
-    xrandr | grep "^HDMI" | grep -qs " connected" && return 0
+    xrandr | grep "^VGA" | grep " connected" >/dev/null && return 0
+    xrandr | grep "^HDMI" | grep " connected" >/dev/null && return 0
     return 1
 }
 
 _arch()
 {   #check for system arch, returns [64|32]
     local arch
-    [ -z "$MACHTYPE" ] && arch=$(uname -m) || arch=$(echo $MACHTYPE | cut -d- -f1)
+    [ -z "$MACHTYPE" ] && arch=$(uname -m) || arch=$(printf "%s\\n" "$MACHTYPE" | cut -d- -f1)
 
     case $arch in
         x86_64)
@@ -41,7 +41,7 @@ _arch()
             ;;
     esac
 
-    echo $arch
+    printf "%s\\n" "$arch"
 }
 
 
@@ -55,7 +55,7 @@ fi
 
 # Check that values for 'resumetime' are numbers
 case $resumetime in
-    ''|*[!0-9]*) echo Error, \"$resumetime\" is not a number;exit 1;;
+    ''|*[!0-9]*) printf "%s\\n" "Error, $resumetime is not a number";exit 1;;
 esac
 
 # Name of suspend script
@@ -79,43 +79,43 @@ warn=${bldred}*${txtrst}
 usage()
 {
     # Help message.
-    echo
-    echo "   $prog disables screen blanking and screensaver to allow viewing a video.  Running the program again will enable them.  If the 'resumetime' variable is set after that time $prog will resume normal powersaving values." | fmt -c -w 76
-    echo
+    printf "\\n"
+    printf "%s\\n" "   $prog disables screen blanking and screensaver to allow viewing a video.  Running the program again will enable them.  If the 'resumetime' variable is set after that time $prog will resume normal powersaving values." | fmt -c -w 76
+    printf "\\n"
 
     # Display current values of power management and movietime.
     suspinhtest=$(ps aux | grep -v grep | grep $suspinhscript)
-    suspinhval=$([ -n "$suspinhtest" ] && echo "Disabled" || echo "Desktop settings")
+    suspinhval=$([ -n "$suspinhtest" ] && printf "%s\\n" "Disabled" || printf "%s\\n" "Desktop settings")
 
     # DPMS disabled information
-    echo "   ${txtbld}Current settings ${txtrst}(in minutes, 0 = disabled):"
+    printf "%s\\n" "   ${txtbld}Current settings ${txtrst}(in minutes, 0 = disabled):"
     if [ X"$dispdpms" = X"Disabled" ]; then
-      echo "   DPMS:         $dispdpms"
-      echo "   Suspend:      $suspinhval"
+      printf "%s\\n" "   DPMS:         $dispdpms"
+      printf "%s\\n" "   Suspend:      $suspinhval"
     fi
 
     # DPMS enabled information
     if [ X"$dispdpms" = X"Enabled" ]; then
-      echo "   DPMS:         $dispdpms"
-      echo "   DPMS times:   Blank: ${dispblank}; Standby: ${dispstand}; Suspend: ${dispsusp}; Offtime: ${dispoff}"
-      echo "   Suspend:      $suspinhval"
+      printf "%s\\n" "   DPMS:         $dispdpms"
+      printf "%s\\n" "   DPMS times:   Blank: ${dispblank}; Standby: ${dispstand}; Suspend: ${dispsusp}; Offtime: ${dispoff}"
+      printf "%s\\n" "   Suspend:      $suspinhval"
     fi
-    echo
-    echo "   ${txtbld}$prog settings${txtrst}:"
-    echo "   Resume after: $resumetimehr hours"
-    echo
+    printf "\\n"
+    printf "%s\\n" "   ${txtbld}$prog settings${txtrst}:"
+    printf "%s\\n" "   Resume after: $resumetimehr hours"
+    printf "\\n"
     exit 0
 }
 
 # Check that Xorg server is running
-if [[ -z $(ps aux | grep /usr/bin/X) ]]; then
-  echo "$warn The Xorg server is not running."
+if [ -z "$(ps aux | grep /usr/bin/X)" ]; then
+  printf "%s\\n" "$warn The Xorg server is not running."
   exit
 fi
 
 # Check if user is regular user
 if [ X"$(whoami)" = X"root" ]; then
-  echo "$warn You are the root user, must be a regular user."
+  printf "%s\\n" "$warn You are the root user, must be a regular user."
   exit
 fi
 
@@ -127,7 +127,7 @@ dispoff=$(xset -q | grep "^  Standby: " | awk '{ printf $6/60 }')
 dispblank=$(xset -q | grep "^  timeout:  " | awk '{ printf $2/60 }')
 
 # Resume time in hours
-resumetimehr=$(echo "scale=1;${resumetime}/60" | bc)
+resumetimehr=$(printf "%s\\n" "scale=1;${resumetime}/60" | bc)
 
 # Display help
 case $1 in
@@ -137,7 +137,7 @@ esac
 
 # Suspend inhibit script (must be run as seperate process)
 suspinhibit () {
-    echo '#!/bin/bash
+    printf "%s\\n" '#!/bin/bash
     for time in $(seq 1 '$resumetime'); do
     # Simulate user activity every minute
     xdotool keydown Shift_L keyup Shift_L
@@ -161,12 +161,12 @@ if [ X"$dispdpms" = X"Enabled" ] && [ -z "$suspinhtest" ]; then
       if [ -f /usr/local/bin/lights/$(_arch)/lights ]; then
           /usr/local/bin/lights/$(_arch)/lights > /dev/null 2>&1 &
       else
-          echo "To enjoy fully the movietime experience install: /usr/local/bin/lights/"$_arch"/lights"
-          echo "  https://github.com/chilicuil/learn/tree/master/java"
+          printf "%s\\n" "To enjoy fully the movietime experience install: /usr/local/bin/lights/"$_arch"/lights"
+          printf "%s\\n" "  https://github.com/chilicuil/learn/tree/master/java"
       fi
   fi
 
-  echo "[+] $prog started"
+  printf "%s\\n" "[+] $prog started"
 else
   # Enable blanking, screen power saving
   xset s on; xset +dpms
@@ -174,10 +174,10 @@ else
   if [ -n $suspinhtest ]; then
 
     kill -s 9 $(pgrep movietime-susp) &> /dev/null
-    ps aux | grep -qs [l]ights.jar
+    ps aux | grep [l]ights.jar >/dev/null
     if [ "$?" -eq 0 ]; then
         kill -s 9 $(ps aux | grep [l]ights.jar | awk '{print $2}')
     fi
-    echo "[-] $prog stopped"
+    printf "%s\\n" "[-] $prog stopped"
   fi
 fi
diff --git a/sh/tools/rm_ b/sh/tools/rm_
--- a/sh/tools/rm_
+++ b/sh/tools/rm_
@@ -20,18 +20,18 @@ fi
 
 _usage()
 {
-    echo -e "Usage: "$0" [OPTION]... FILE..."
-    echo -e "Wrapper for the \`rm' command, compatible with nautilus|pcmanfm file managers\n"
-    echo -e "  -l [PATTERN]   list archived files, use -ll and -lll to increase verbosity"
-    echo -e "  -c [PATTERN]   remove permanently archived files"
-    echo -e "  -u [PATTERN]   recover archived files"
-    echo -e "  -y             say yes to all questions"
-    echo -e "  -f             remove instead of archive files \`rm' is executed directly"
-    echo -e "  -h             shows this message, use --help to obtain \`rm' help"
-    echo -e "\n"$0" deletes directories and files with no distintion therefore no -r option is needed\n"
+    printf "%b\\n" "Usage: $(expr "$0" : '.*/\([^/]*\)') [OPTION]... FILE..."
+    printf "%b\\n" "Wrapper for the \`rm' command, compatible with nautilus|pcmanfm file managers\n"
+    printf "%b\\n" "  -l [PATTERN]   list archived files, use -ll and -lll to increase verbosity"
+    printf "%b\\n" "  -c [PATTERN]   remove permanently archived files"
+    printf "%b\\n" "  -u [PATTERN]   recover archived files"
+    printf "%b\\n" "  -y             say yes to all questions"
+    printf "%b\\n" "  -f             remove instead of archive files \`rm' is executed directly"
+    printf "%b\\n" "  -h             shows this message, use --help to obtain \`rm' help"
+    printf "%b\\n" "\n$(expr "$0" : '.*/\([^/]*\)') deletes directories and files with no distintion therefore no -r option is needed\n"
 
-    echo -e "Last version is always available in: <https://github.com/chilicuil/learn/tree/master/sh/rm_>"
-    echo -e "Report bugs to chilicuil@gmail.com"
+    printf "%b\\n" "Last version is always available in: <https://github.com/chilicuil/learn/tree/master/sh/rm_>"
+    printf "%b\\n" "Report bugs to m@javier.io"
 }
 
 #http://www.makkintosshu.com/journal/a-realpath-implementation-in-bash
@@ -71,7 +71,7 @@ _realpath()
         abs_path="${abs_path}/${file_basename}"
 
         # output the absolute path
-        echo "$abs_path"
+        printf "%s\\n" "$abs_path"
     fi
 
     $success
@@ -82,7 +82,7 @@ _dirname()
 {
     local dir="${1%${1##*/}}"
     [ X"${dir:=./}" != X"/" ] && dir="${dir%?}"
-    echo "$dir"
+    printf "%s\\n" "$dir"
 }
 
 _list()
@@ -90,7 +90,7 @@ _list()
     files_in_trash=("$trash_dir"/info/*.trashinfo)
 
     if [ ! -e "${files_in_trash[0]}" ] ; then
-        echo "$(expr "$0" : '.*/\([^/]*\)'): Nothing to list" >&2 ; exit 1
+        printf "%s\\n" "$(expr "$0" : '.*/\([^/]*\)'): Nothing to list" >&2 ; exit 1
     fi
 
     OLDIFS="$IFS"; IFS=$'\n' #fix case where files have spaces
@@ -98,11 +98,11 @@ _list()
         | sed -e 's:^:|:g' -e 's:\.trashinfo.*=:|:g' | tr -d '\n'| sed -e 's:--:\n:g'); do
 
     IFS="$OLDIFS"
-    datetime=$(echo "$data_in_trashinfo" | cut -d\| -f5)
-    general_date=$(echo "$datetime" | cut -dT -f1)
-    detail_date=$(echo "$datetime" | cut -dT -f2)
-    name=$(echo "$data_in_trashinfo" | cut -d\| -f3)
-    real_file=$(echo "$data_in_trashinfo" | cut -d\| -f2 | sed -e 's:\/info\/:\/files\/:g')
+    datetime=$(printf "%s\\n" "$data_in_trashinfo" | cut -d\| -f5)
+    general_date=$(printf "%s\\n" "$datetime" | cut -dT -f1)
+    detail_date=$(printf "%s\\n" "$datetime" | cut -dT -f2)
+    name=$(printf "%s\\n" "$data_in_trashinfo" | cut -d\| -f3)
+    real_file=$(printf "%s\\n" "$data_in_trashinfo" | cut -d\| -f2 | sed -e 's:\/info\/:\/files\/:g')
     if [ -e "$real_file" ]; then
         size=$(du -sh "$real_file" | awk '{print $1}')
     else
@@ -112,19 +112,19 @@ _list()
     if [ -d "$real_file" ] ; then
         if [ "$verboselist" -gt 1 ]; then
             some="$(ls "$real_file" | wc -l | sed 's/[^[:digit:]]//g')"
-            echo -e "$some\t$size\t$general_date $detail_date $name/"
+            printf "%b\\n" "$some\t$size\t$general_date $detail_date $name/"
             if [ "$verboselist" -gt 2 ]; then
                 find "$real_file" | sed -e "s:$trash_dir/files::g" | sed -e 's:^:\t\t|_ ..:g'
             fi
         else
-            echo "$name/"
+            printf "%s\\n" "$name/"
         fi
     else
         if [ "$verboselist" -gt 1 ]; then
             some=1
-            echo -e "$some\t$size\t$general_date $detail_date $name"
+            printf "%b\\n" "$some\t$size\t$general_date $detail_date $name"
         else
-            echo "$name"
+            printf "%s\\n" "$name"
         fi
     fi
 done
@@ -151,13 +151,13 @@ _archive()
                 archive="$trash_dir/files/$(basename "$file")".$num
                 trashinfo="$trash_dir/info/$(basename "$file").$num.trashinfo"
                 #num+=1
-                num=$(($num+ 1))
+                num=$(expr $num + 1)
             done
 
             #put $file & $trashinfo vars between "" to capture spaces
-            echo "[Trash Info]"                         >  "$trashinfo"
-            echo "Path=$(_realpath "$file")"             >> "$trashinfo"
-            echo "DeletionDate=$(date +%Y-%m-%dT%T)"    >> "$trashinfo"
+            printf "%s\\n" "[Trash Info]"                         >  "$trashinfo"
+            printf "%s\\n" "Path=$(_realpath "$file")"             >> "$trashinfo"
+            printf "%s\\n" "DeletionDate=$(date +%Y-%m-%dT%T)"    >> "$trashinfo"
 
             mv "$file" "$archive"
         else
@@ -173,7 +173,7 @@ _recover()
     _list "$1"
 
     if [ -z "$yflag" ]; then
-        echo -n "Recover this items from trash? (Y/n) "
+        printf "%s" "Recover this items from trash? (Y/n) "
         answer=y
         read answer
     else
@@ -181,25 +181,25 @@ _recover()
     fi
 
     if [ ! X"$answer" = X"y" ]; then
-        echo "Nothing done" && exit 0
+        printf "%s\\n" "Nothing done" && exit 0
     else
         OLDIFS="$IFS"; IFS=$'\n' #fix case where files have spaces
         for data_in_trashinfo in $(find "$trash_dir"/info -name "*.trashinfo" -print0 | sort -z | xargs -0 grep -A 1 -Hri "path.*$1" \
             | sed -e 's:^:|:g' -e 's:\.trashinfo.*=:|:g' | tr -d '\n'| sed -e 's:--:\n:g'); do
         IFS="$OLDIFS"
 
-        datetime=$(echo "$data_in_trashinfo" | cut -d\| -f5)
-        general_date=$(echo "$datetime" | cut -dT -f1)
-        detail_date=$(echo "$datetime" | cut -dT -f2)
+        datetime=$(printf "%s\\n" "$data_in_trashinfo" | cut -d\| -f5)
+        general_date=$(printf "%s\\n" "$datetime" | cut -dT -f1)
+        detail_date=$(printf "%s\\n" "$datetime" | cut -dT -f2)
 
-        real_file=$(echo "$data_in_trashinfo" | cut -d\| -f2)
+        real_file=$(printf "%s\\n" "$data_in_trashinfo" | cut -d\| -f2)
         info_file="$trash_dir/info/$(basename "$real_file").trashinfo"
         file_file="$trash_dir/files/$(basename "$real_file")"
 
-        name=$(echo "$data_in_trashinfo" | cut -d\| -f3)
+        name=$(printf "%s\\n" "$data_in_trashinfo" | cut -d\| -f3)
 
         if [ ! -d $(_dirname "$name") ]; then
-            echo "mkdir -p $(_dirname $name)"
+            printf "%s\\n" "mkdir -p $(_dirname $name)"
         fi
 
         if [ -e "$name" ]; then
@@ -219,7 +219,7 @@ _clean()
     _list "$1"
 
     if [ -z "$yflag" ]; then
-        echo -n "Empty this items from trash? (Y/n) "
+        printf "%s" "Empty this items from trash? (Y/n) "
         answer=y
         read answer
     else
@@ -227,21 +227,21 @@ _clean()
     fi
 
     if [ ! X"$answer" = X"y" ]; then
-        echo "Nothing done" && exit 0
+        printf "%s\\n" "Nothing done" && exit 0
     else
         OLDIFS="$IFS"; IFS=$'\n' #fix case where files have spaces
         for data_in_trashinfo in $(find "$trash_dir"/info -name "*.trashinfo" -print0 | sort -z | xargs -0 grep -A 1 -Hri "path.*$1" \
             | sed -e 's:^:|:g' -e 's:\.trashinfo.*=:|:g' | tr -d '\n'| sed -e 's:--:\n:g'); do
         IFS="$OLDIFS"
 
-        real_file=$(echo "$data_in_trashinfo" | cut -d\| -f2)
+        real_file=$(printf "%s\\n" "$data_in_trashinfo" | cut -d\| -f2)
         info_file="$trash_dir/info/$(basename "$real_file").trashinfo"
         file_file="$trash_dir/files/$(basename "$real_file")"
 
         rm -rf "$info_file"
         rm -rf "$file_file"
-        #echo "rm: $info_file"
-        #echo "rm: $file_file"
+        #printf "%s\\n" "rm: $info_file"
+        #printf "%s\\n" "rm: $file_file"
     done
 fi
 }
@@ -251,17 +251,17 @@ while getopts ":fluhcry" options
 do
     case $options in
         f) exec rm -r "$@"                       ;;
-        l) verboselist=$(($verboselist+1))       ;;  # list verbose level 1-3
-        u) shift $(($OPTIND - 1)); _recover "$@" ;;  # remove the -u
+        l) verboselist=$(expr $verboselist + 1)       ;;  # list verbose level 1-3
+        u) shift $(expr $OPTIND - 1); _recover "$@" ;;  # remove the -u
         h) _usage                                ;;
-        c) shift $(($OPTIND - 1)); _clean "$@"   ;;  # remove the -c
+        c) shift $(expr $OPTIND - 1); _clean "$@"   ;;  # remove the -c
         r)                                       ;;
         y) yflag=yes                             ;;
         *) exec rm "$@"                          ;;  # send the rest to rm
     esac
 done
 
-shift $(($OPTIND - 1))
+shift $(expr $OPTIND - 1)
 
 if [ $verboselist -gt 0 ]; then
     _list "$@"
@@ -271,7 +271,7 @@ fi
 # Make sure that the $trash_dir exists
 if [ ! -d "$trash_dir" ] ; then
     if [ ! -w "$HOME" ] ; then
-        echo "$0 failed: can't create $trash_dir in $HOME" >&2
+        printf "%s\\n" "$(expr "$0" : '.*/\([^/]*\)') failed: can't create $trash_dir in $HOME" >&2
         exit 1
     fi
     mkdir -p "$trash_dir"/{expunged,files,info}
diff --git a/sh/tools/say b/sh/tools/say
--- a/sh/tools/say
+++ b/sh/tools/say
@@ -3,16 +3,16 @@
 #$ cat file_english | say -e
 #$ say -e "something"
 
-[ -f /usr/bin/mplayer ] || { echo -e "$0: You need vim & mplayer to run this script\n$ sudo apt-get install vim-nox mplayer"; exit 1; }
-[ -f /usr/bin/vim ] || { echo -e "$0: You need vim to run this script\n$ sudo apt-get install vim-nox"; exit 1; }
+[ -f /usr/bin/mplayer ] || { printf "%b\\n" "$(expr "$0" : '.*/\([^/]*\)'): You need vim & mplayer to run this script\n$ sudo apt-get install vim-nox mplayer"; exit 1; }
+[ -f /usr/bin/vim ] || { printf "%b\\n" "$(expr "$0" : '.*/\([^/]*\)'): You need vim to run this script\n$ sudo apt-get install vim-nox"; exit 1; }
 
 _usage()
 {
-    echo "Usage: `expr "$0" : '.*/\([^/]*\)'` [-s|-p|-e] phrase"
-    echo
-    echo "          -s     Spanish (default)"
-    echo "          -p     Portuguese"
-    echo "          -e     English"
+    printf "%s\\n" "Usage: `expr "$0" : '.*/\([^/]*\)'` [-s|-p|-e] phrase"
+    printf "\\n"
+    printf "%s\\n" "          -s     Spanish (default)"
+    printf "%s\\n" "          -p     Portuguese"
+    printf "%s\\n" "          -e     English"
     exit 1
 }
 
@@ -45,12 +45,12 @@ while getopts ":spe" option; do
           ;;
         :)
           if [ -z "$PHRASE" ]; then
-              echo "Option -$OPTARG requires an argument"
+              printf "%s\\n" "Option -$OPTARG requires an argument"
               _usage
           fi
           ;;
         \?)
-          echo "Invalid option: -$OPTARG"
+          printf "%s\\n" "Invalid option: -$OPTARG"
           _usage
           ;;
     esac
@@ -64,13 +64,13 @@ if [ -z "$lang" ]; then
 fi
 
 while [ ${#PHRASE} -gt 100 ]; do
-    tmp=$(echo -ne ${PHRASE:0:100} | xxd -plain | tr -d '\n' | sed 's/\(..\)/%\1/g')
+    tmp=$(printf "%b" "${PHRASE:0:100}" | xxd -plain | tr -d '\n' | sed 's/\(..\)/%\1/g')
     mplayer -really-quiet "http://translate.google.com/translate_tts?ie=UTF-8&tl=$lang&q=$tmp" > /dev/null 2>&1
     PHRASE=${PHRASE:100:${#PHRASE}}
     #http://stackoverflow.com/questions/4988155/is-there-a-bash-command-that-can-tell-the-size-of-a-shell-variable
 done
 
 #http://stackoverflow.com/questions/296536/urlencode-from-a-bash-script
-PHRASE=$(echo -ne $PHRASE | xxd -plain | tr -d '\n' | sed 's/\(..\)/%\1/g')
+PHRASE=$(printf "%b" "$PHRASE" | xxd -plain | tr -d '\n' | sed 's/\(..\)/%\1/g')
 shift;shift;
 mplayer -really-quiet "http://translate.google.com/translate_tts?ie=UTF-8&tl=$lang&q=$PHRASE" > /dev/null 2>&1
diff --git a/sh/tools/screencast-encode b/sh/tools/screencast-encode
--- a/sh/tools/screencast-encode
+++ b/sh/tools/screencast-encode
@@ -9,11 +9,11 @@ _basename()
 
 _usage()
 {
-    echo "Usage: $(_basename $0) [-v 0-2048][-s soundtrack.mp3][-k] screencast.mkv" >&2
-    echo >&2
-    echo "          -v     Change the volume from the screencast [0-2048] (ffmpeg -vol)" >&2
-    echo "          -s     Add soundtrack" >&2
-    echo "          -k     Keep tmp files" >&2
+    printf "%s\\n" "Usage: $(_basename $0) [-v 0-2048][-s soundtrack.mp3][-k] screencast.mkv" >&2
+    printf "\\n" >&2
+    printf "%s\\n" "          -v     Change the volume from the screencast [0-2048] (ffmpeg -vol)" >&2
+    printf "%s\\n" "          -s     Add soundtrack" >&2
+    printf "%s\\n" "          -k     Keep tmp files" >&2
     exit 1
 }
 
@@ -26,8 +26,8 @@ _notify()
     if [ X"$TERM" = X"linux" ]; then
         notify-send -t 3000 "${@}"
     else
-        echo "${@}"
-        echo
+        printf "%s\\n" "${@}"
+        printf "\\n"
     fi
 }
 
@@ -55,11 +55,11 @@ while getopts ":v:s:k" option; do
           KFLAG=yes
           ;;
         :)
-          echo "Option -$OPTARG requires an argument"
+          printf "%s\\n" "Option -$OPTARG requires an argument"
           _usage
           ;;
         \?)
-          echo "Invalid option: -$OPTARG"
+          printf "%s\\n" "Invalid option: -$OPTARG"
           _usage
           ;;
     esac
diff --git a/sh/tools/setup b/sh/tools/setup
--- a/sh/tools/setup
+++ b/sh/tools/setup
@@ -6,11 +6,11 @@
 #Don't forget update this when adding new functions
 _usage()
 {
-  echo "$(expr "$0" : '.*/\([^/]*\)'): setup my common tasks"
-  echo
-  echo "  autocp            cp custom autocomplete file"
-  echo "  script            cp custom script to the path system"
-  echo
+  printf "%s\\n" "$(expr "$0" : '.*/\([^/]*\)'): setup my common tasks"
+  printf "\\n"
+  printf "%s\\n" "  autocp            cp custom autocomplete file"
+  printf "%s\\n" "  script            cp custom script to the path system"
+  printf "\\n"
   exit 0
 }
 
@@ -18,7 +18,7 @@ _exec()
 {   #print current command, exits on fail
     [ -z "$1" ] && return 0
 
-    echo "[+] $@"
+    printf "%s\\n" "[+] $@"
     $@
 
     local status=$?
@@ -28,7 +28,7 @@ _exec()
 _script()
 {
 
-    [ -z "$1" ] && (echo "$0: Missing argument, looking for a .sh|.py|.rb|etc script"; exit 1)
+    [ -z "$1" ] && (printf "%s\\n" "$(expr "$0" : '.*/\([^/]*\)'): Missing argument, looking for a .sh|.py|.rb|etc script"; exit 1)
 
     for file
     do
@@ -41,7 +41,7 @@ _script()
 
 _autocp()
 {
-    [ -n "$1" ] || (echo "$0: Missing parameter, looking for an .autocp file"; exit 1)
+    [ -n "$1" ] || (printf "%s\\n" "$(expr "$0" : '.*/\([^/]*\)'): Missing parameter, looking for an .autocp file"; exit 1)
 
     for file
     do
@@ -62,10 +62,10 @@ if [ X"$#" != X"0" ]; then
         _usage
         ;;
         -v | --version)
-        echo $VERSION
+        printf "%s\\n" "$VERSION"
         ;;
         *)
-        echo -e "Error, unknown option: \"$1\""
+        printf "%s\\n" "Error, unknown option: $1"
         _usage
         ;;
     esac
diff --git a/sh/tools/shellshock b/sh/tools/shellshock
--- a/sh/tools/shellshock
+++ b/sh/tools/shellshock
@@ -70,8 +70,8 @@ function rm_process { local file; for file in "${_rm_queue[@]}"; do rm "$file"; 
 
 # check if tput actually outputs something useful for this terminal
 if [[ -z "$(tput sgr0)" ]] || [[ -z "$(tput bold)" ]]; then
-	echo 'Error: tput is not working as expected with your current terminal settings!' >&2
-	echo 'Try setting your $TERM to something more standard?' >&2
+	printf "%s\\n" "Error: tput is not working as expected with your current terminal settings!" >&2
+	printf "%s\\n" "Try setting your $TERM to something more standard?" >&2
 	exit 1
 fi
 
@@ -116,7 +116,7 @@ esac
 if [[ -n "$comm" ]]; then
 	rm_queue "$comm"
 else
-	echo "Error: Communications file creation failed!" >&2
+	printf "%s\\n" "Error: Communications file creation failed!" >&2
 	exit 1
 fi
 
@@ -144,12 +144,12 @@ tput civis						# hide the cursor
 		shift 2
 
 		# running this in a loop with 2>/dev/null to avoid "interrupted system call" messages
-		while { ! builtin echo -n "${posarray[$((y*cols+x))]}$@"; } 2>/dev/null; do testparent; done
+		while { ! printf "%s" "${posarray[$((y*cols+x))]}$@"; } 2>/dev/null; do testparent; done
 	}
 	function safeecho
 	{
 		# running this in a loop with 2>/dev/null to avoid "interrupted system call" messages
-		while { ! builtin echo -n "${posarray[$((y*cols+x))]}$@"; } 2>/dev/null; do testparent; done
+		while { ! printf "%s" "${posarray[$((y*cols+x))]}$@"; } 2>/dev/null; do testparent; done
 	}
 	function xyprintf
 	{
@@ -473,13 +473,13 @@ EOF
 			# this is slow. very slow.
 			function microtime {
 				local time=$(python <<<"import time; print \"%.6f\" % time.time();")
-				echo -n ${time/./}
+				printf "%s" ${time/./}
 			}
 		;;
 		*)
 			function microtime {
 				local time=$(date +%s%N)
-				echo -n ${time:0:((${#time}-3))}
+				printf "%s" ${time:0:((${#time}-3))}
 			}
 		;;
 	esac
@@ -500,7 +500,7 @@ EOF
 		posarray=()
 
 		local q=false
-		local e=$(echo -e "\e")
+		local e=$(printf "%b\\n" "\e")
 		if [ X"$(tput cup 0 0)" = X"${e}[1;1H" ]; then
 			# standard terminal movement commands - quick generation
 			q=true
@@ -516,7 +516,7 @@ EOF
 				buildposarray
 				return $?
 			fi
-			echo -n "${pos}$((x*100/cols))%"
+			printf "%s" "${pos}$((x*100/cols))%"
 			for ((y=0; y < rows; y++)); do
 				if $q; then
 					posarray[$((y*cols+x))]="${e}[$((y+1));$((x+1))H"
@@ -1097,7 +1097,7 @@ EOF
 					# reading and writing this high score is sensitive to signal interruption and is somewhat error prone
 					highscore=$(command cat "${HOME}/.shellshock" 2>/dev/null)
 					if ((score_current > highscore)); then
-						echo -n "$score_current" >"${HOME}/.shellshock"
+						printf "%s" "$score_current" >"${HOME}/.shellshock"
 					fi
 					safeecho $color_score_result
 					if ((score_current >= highscore)); then
@@ -1376,13 +1376,13 @@ while true; do
 			readc
 			case "$c" in
 				A|B|C|D)
-					builtin echo "$c" >"$comm"
+					printf "%s\\n" "$c" >"$comm"
 					kill -USR1 "$gamepid"
 				;;
 			esac
 		;;
 		' '|p|q|z)
-			builtin echo "$c" >"$comm"
+			printf "%s\\n" "$c" >"$comm"
 			kill -USR1 "$gamepid"
 		;;
 	esac
diff --git a/sh/tools/startx b/sh/tools/startx
--- a/sh/tools/startx
+++ b/sh/tools/startx
@@ -7,10 +7,9 @@ if [ $# -eq 0 ]      # check to see if arguements are given (color depth)
         else a=$1    # use given arguement
 fi
 
-if [ $a -ne 8 ] && [ $a -ne 16 ] && [ $a -ne 24 ]
-        then
-                echo "Invalid color depth. Use 8, 16, or 24."
-        exit 1
+if [ $a -ne 8 ] && [ $a -ne 16 ] && [ $a -ne 24 ]; then
+    printf "%s\\n" "Invalid color depth. Use 8, 16, or 24."
+    exit 1
 fi
 
 for display in 0 1 2 3 4 5
@@ -18,9 +17,9 @@ do   # checks for open display, starts X on next available
     if [ ! -f "/tmp/.X$display-lock" ]
     then
         exec startx -- :$display #-depth $a
-        exit0
+        exit 0
     fi
 done
 
-echo "No displays available."
+printf "%s\\n" "No displays available."
 exit 1
diff --git a/sh/tools/whats b/sh/tools/whats
--- a/sh/tools/whats
+++ b/sh/tools/whats
@@ -6,7 +6,7 @@ word="$1"
 
 _usage()
 {
-    echo "Usage: `expr "$0" : '.*/\([^/]*\)'` word" >&2
+    printf "%s\\n" "Usage: `expr "$0" : '.*/\([^/]*\)'` word" >&2
     exit 0
 }
 
@@ -14,18 +14,18 @@ _usage()
 
 _whats()
 {
-    [ -z "$1" ] && (echo "$0: Missing argument"; exit 1)
+    [ -z "$1" ] && (printf "%s\\n" "$0: Missing argument"; exit 1)
 
     [ -n "$2" ] || more_than_one=1
 
     for word
     do
         response=$(dig +short txt $word.wp.dg.cx)
-        echo "$response"
+        printf "%s\\n" "$response"
         if [ -z "$more_than_one" ]; then
-            echo
-            echo ":::::::::::::::::::::::::::::::::::::::::::::::::"
-            echo
+            printf "\\n"
+            printf "%s\\n" ":::::::::::::::::::::::::::::::::::::::::::::::::"
+            printf "\\n"
         fi
     done
 }
