add pre-tests

diff --git a/sh/tools/dmenu-mpd b/sh/tools/dmenu-mpd
--- a/sh/tools/dmenu-mpd
+++ b/sh/tools/dmenu-mpd
@@ -8,7 +8,22 @@
 #requires a dmenu version with xft: https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745
 #-sf yellow
 DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #ffffff -sb #000000 -sf #cfd000'
-#song=$(sed -n "s@^ *\([0-9]\+\);$(mpc playlist| $DMENU ||printf "%s\\n" ";;;")@\1@p" < <(mpc playlist|nl -s ';'))
+
+_die()
+{
+    choice=$(printf "%b\\n" "$1" | $DMENU)
+    exit 1
+}
+
+if ! command -v "dmenu" >/dev/null; then
+    printf "%s\\n" "dmenu was not found"
+    exit 1
+fi
+
+if ! command -v "mpc" >/dev/null; then
+    _die "mpd was not found, press <Enter> to exit"
+fi
+
 song=$(mkfifo fifo; mpc playlist|nl -s ';' > fifo & sed -n "s@^ *\([0-9]\+\);$(mpc playlist| $DMENU ||printf "%s\\n" ";;;")@\1@p" fifo)
 song=$(printf "%s\\n" "$song" | head -1)
 rm -rf fifo
diff --git a/sh/tools/dmenu-run b/sh/tools/dmenu-run
--- a/sh/tools/dmenu-run
+++ b/sh/tools/dmenu-run
@@ -11,4 +11,19 @@ DMENU="dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #ffffff -sb #000000 -sf #754
 #DMENU="dmenu -p > -i -fn Sawasdee-9 -nb #000000 -nf #ffffff -sb #000000 -sf #7541b9"
 #DMENU="dmenu -p > -i -fn TlwgTypewriter-9 -nb #000000 -nf #ffffff -sb #000000 -sf #7541b9"
 
+_die()
+{
+    choice=$(printf "%b\\n" "$1" | $DMENU)
+    exit 1
+}
+
+if ! command -v "dmenu" >/dev/null; then
+    printf "%s\\n" "dmenu was not found"
+    exit 1
+fi
+
+if ! command -v "dmenu-path" >/dev/null; then
+    _die "dmenu-path was not found, press <Enter> to exit"
+fi
+
 exe=$(dmenu-path | $DMENU) && exec $exe
diff --git a/sh/tools/dmenu-session b/sh/tools/dmenu-session
--- a/sh/tools/dmenu-session
+++ b/sh/tools/dmenu-session
@@ -7,6 +7,12 @@
 
 #requires a dmenu version with xft: https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745
 DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #FFFFFF -sb #000000 -sf #999999'
+
+if ! command -v "dmenu" >/dev/null; then
+    printf "%s\\n" "dmenu was not found"
+    exit 1
+fi
+
 choice=$(printf "%b\\n" "lock\nlogout\nrestart\nshutdown\nreboot\nsuspend\nhibernate" | $DMENU)
 
 case "$choice" in
diff --git a/sh/tools/dmenu-tell b/sh/tools/dmenu-tell
--- a/sh/tools/dmenu-tell
+++ b/sh/tools/dmenu-tell
@@ -9,6 +9,22 @@
 #requires a dmenu version with xft: https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745
 #-sf blue
 DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #ffffff -sb #000000 -sf #aaffaf'
+
+_die()
+{
+    choice=$(printf "%b\\n" "$1" | $DMENU)
+    exit 1
+}
+
+if ! command -v "dmenu" >/dev/null; then
+    printf "%s\\n" "dmenu was not found"
+    exit 1
+fi
+
+if ! command -v "say" >/dev/null; then
+    _die "say script was not found, press <Enter> to exit"
+fi
+
 phrase=$($DMENU <&- && printf "\\n")
 
 [ -n "${phrase}" ] || exit 0;
diff --git a/sh/tools/dmenu-vbox b/sh/tools/dmenu-vbox
--- a/sh/tools/dmenu-vbox
+++ b/sh/tools/dmenu-vbox
@@ -8,6 +8,22 @@
 #requires a dmenu version with xft: https://bugs.launchpad.net/ubuntu/+source/suckless-tools/+bug/1093745
 #-sf blue
 DMENU='dmenu -p > -i -fn Bahamas-10 -nb #000000 -nf #ffffff -sb #000000 -sf #3B5998'
+
+_die()
+{
+    choice=$(printf "%b\\n" "$1" | $DMENU)
+    exit 1
+}
+
+if ! command -v "dmenu" >/dev/null; then
+    printf "%s\\n" "dmenu was not found"
+    exit 1
+fi
+
+if ! command -v "vboxmanage" >/dev/null; then
+    _die "virtualbox was not found, press <Enter> to exit"
+fi
+
 vboxmachine=$(vboxmanage list vms | cut -d\" -f2 | $DMENU)
 
 if [ -z "${vboxmachine}" ]; then
