general cleanup

diff --git a/sh/tools/dump-dbs b/sh/tools/dump-dbs
--- a/sh/tools/dump-dbs
+++ b/sh/tools/dump-dbs
@@ -1,44 +1,40 @@
 #!/bin/sh
-#set -e
+#description: dump all available databases
+#usage: dump-dbs [-u USER|-p PASSWD|-o DIR|-c CONFIG|-z|-h] module
 
-BACKUPDIR="/path"
-DBUSER="user"
-DBPASSWD="passwd"
+#example: dump-dbs -u root -p passwd
+#dump-dbs: there is no mysql dbs on this host
 
-_basename()
+#this vars can be specified at ./.dump-dbs, ~/.dump-dbs or /etc/dump-dbs
+module=""
+user=""
+passwd=""
+compression=""
+backup_dir=""
+
+_usage()
 {
-    [ -z "${1}" ] && return 1 || _basename_var_1="${1}"
-    [ -z "${2}" ] || _basename_var_suffix="${2}"
-    case "${_basename_var_1}" in
-        /*|*/*) _basename_var_1="$(expr "${_basename_var_1}" : '.*/\([^/]*\)')" ;;
-    esac
-
-    if [ -n "${_basename_var_suffix}" ] && [ "${#_basename_var_1}" -gt "${#2}" ]; then
-        if [ X"$(printf "%s" "${_basename_var_1}" | cut -c"$((${#_basename_var_1} - ${#_basename_var_suffix} + 1))")" \
-           = X"$(printf "%s" "${_basename_var_suffix}" | cut -c1)" ]; then
-            while [ "${#_basename_var_suffix}" -gt "0" ]; do
-                if [ X"$(printf "%s" "${_basename_var_1}" | cut -c"${#_basename_var_1}")" \
-                   = X"$(printf "%s" "${_basename_var_suffix}" | cut -c"${#_basename_var_suffix}")" ]; then
-                    _basename_var_1="$(printf "%s" "${_basename_var_1}" | cut -c1-"$((${#_basename_var_1} - 1))")"
-                    _basename_var_suffix_len="$((${#_basename_var_suffix} - 1))"
-                    if [ "${_basename_var_suffix_len}" -gt "0" ]; then
-                        _basename_var_suffix="$(printf "%s" "${_basename_var_suffix}" | cut -c1-"${_basename_var_suffix_len}")"
-                    else
-                        _basename_var_suffix=""
-                    fi
-                fi
-            done
-        fi
-    fi
-
-    printf "%s\\n" "${_basename_var_1}"
+    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [-u USER|-p PASSWD|-o DIR|-c] module" >&2
+    printf "\\n" >&2
+    printf "%s\\n" "modules:" >&2
+    printf "%s\\n" "  mysql" >&2
+    printf "\\n" >&2
+    printf "%s\\n" "options:" >&2
+    printf "%s\\n" "  -h              show help (this text)" >&2
+    printf "%s\\n" "  -z              activate compression (gzip)" >&2
+    printf "%s\\n" "  -u USER         configure db user" >&2
+    printf "%s\\n" "  -p PASSWD       configure db passwd" >&2
+    printf "%s\\n" "  -o DIR          configure dir to save dumps" >&2
+    printf "%s\\n" "  -c CONFIG FILE  read options from a configuration file" >&2
+    exit 1
 }
 
-exec 9>/var/run/$(_basename ${0}).lock    #verify only one instance is running
-if ! flock -n 9  ; then                #http://mywiki.wooledge.org/BashFAQ/045
-    printf "%s\\n" "$(_basename ${0}): another instance is running";
+_die()
+{
+    [ -z "${1}" ] && return 1
+    printf "%b\\n" "$(expr "${0}" : '.*/\([^/]*\)'): ${*}" >&2
     exit 1
-fi
+}
 
 _printtime()
 {  #format seconds to a pretty string
@@ -71,29 +67,130 @@ _printtime()
     ""${_printtime_var_day}"d "${_printtime_var_hour}"h "${_printtime_var_min}"m "${_printtime_var_sec}"s"
 }
 
-sleep "$(tr -cd 0-9 </dev/urandom | head -c 3)"m #wait random minutes to run the backup [0-1000]
-START="$(date +%s)"
+_loadconf()
+{
+    [ -z "${1}" ]   && return 1
+    [ ! -f "${1}" ] && return 1
+    _loadconf_var_options=$(awk '! /export/ {if ($0 ~ "^.*=[^;&]*" && $0 !~ "&&" && $1 !~ "^#") print }' "${1}")
+    eval "${_loadconf_var_options}"
+}
 
-[ ! -d "${BACKUPDIR}" ] && mkdir -p "${BACKUPDIR}"
+_mysql()
+{
+    if ! command -v "mysql" >/dev/null; then
+        printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): there is no mysql dbs on this host" >&2; return 1
+    elif ! command -v "mysqldump" >/dev/null; then
+        printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): mysqldump is not available!" >&2; return 1
+    fi
 
-#http://dba.stackexchange.com/questions/19532/safest-way-to-perform-mysqldump-on-a-live-system-with-active-reads-and-writes
-mysql -u"${DBUSER}" -p"${DBPASSWD}" -Ae"FLUSH TABLES WITH READ LOCK; SELECT SLEEP(86400)" &
-sleep 5
-mysql -u"${DBUSER}" -p"${DBPASSWD}" -ANe"SHOW PROCESSLIST" | grep "SELECT SLEEP(86400)" > "${BACKUPDIR}"/proclist.txt
-SLEEP_ID="$(cat "${BACKUPDIR}"/proclist.txt | awk '{print $1}')"
-printf "%s\\n" "KILL ${SLEEP_ID};" > "${BACKUPDIR}"/kill_sleep.sql
+    if ! mysql -u"${user}" -p${passwd} -ANe"SHOW PROCESSLIST" > /dev/null 2>&1; then
+        printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): invalid db credentials (user=${user}, passwd=${passwd}" >&2; return 1
+    fi
 
-DBS="$(mysql -u"${DBUSER}" -p"${DBPASSWD}" -Bse 'show databases')"
-for DB in ${DBS}; do
-    mysqldump -u "${DBUSER}" -p"${DBPASSWD}" --single-transaction --routines --triggers "${DB}" > "${BACKUPDIR}"/"${DB}".sql
+    start="$(date +%s)"
+    #http://dba.stackexchange.com/questions/19532/safest-way-to-perform-mysqldump-on-a-live-system-with-active-reads-and-writes
+    mysql -u"${user}" -p"${passwd}" -Ae"FLUSH TABLES WITH READ LOCK; SELECT SLEEP(86400)" &
+    sleep 5
+
+    sleep_id="$(mysql -u"${user}" -p"${passwd}" -ANe"SHOW PROCESSLIST" | awk '/SELECT SLEEP(86400)/ {print $1}')"
+    printf "%s\\n" "KILL ${sleep_id};" > "${backup_dir}"/kill_sleep.sql
+
+    dbs="$(mysql -u"${user}" -p"${passwd}" -Bse 'show databases')"
+    for db in ${dbs}; do
+        if [ -z "${compress}" ]; then
+            mysqldump -u "${user}" -p"${passwd}" --single-transaction --routines --triggers "${db}" > "${backup_dir}"/"${db}".sql
+        else
+            mysqldump -u "${user}" -p"${passwd}" --single-transaction --routines --triggers "${db}" | gzip > "${backup_dir}"/"${db}".sql.gz
+        fi
+    done
+
+    mysql -u"${user}" -p"${passwd}" -A < "${backup_dir}"/kill_sleep.sql
+    mysql -u"${user}" -p"${passwd}" -Ae"UNLOCK TABLES;"
+    rm -- "${backup_dir}"/kill_sleep.sql
+
+    end="$(date +%s)"
+    diff="$((${END} - ${start}))"
+
+    printf "%s\\n" "$(date +"%d-%m-%Y"):$(_printtime ${diff})" | tee -a "${backup_dir}"/time.txt
+}
+
+if [ ! -t 0 ]; then
+    #there is input comming from pipe or file, add to the end of $@
+    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
+fi
+
+for arg; do #parse options
+    case "${arg}" in
+        -h) _usage ;;
+        -z) compression="seen"; shift;;
+        -u) if [ "${#}" -gt "1" ]; then
+                user="$(printf "%s " "${@}" | awk '{print $2}')"
+                shift 2
+            else
+                _die "Option ${arg} requires a parameter"
+            fi ;;
+        -p) if [ "${#}" -gt "1" ]; then
+                passwd="$(printf "%s " "${@}" | awk '{print $2}')"
+                shift 2
+            else
+                _die "Option ${arg} requires a parameter"
+            fi ;;
+        -o) if [ "${#}" -gt "1" ]; then
+                backup_dir="$(printf "%s " "${@}" | awk '{print $2}')"
+                shift 2
+            else
+                _die "Option ${arg} requires a parameter"
+            fi ;;
+        -c) if [ "${#}" -gt "1" ]; then
+                _var_config_file="$(printf "%s " "${@}" | awk '{print $2}')"
+                shift 2
+            else
+                _die "Option ${arg} requires a parameter"
+            fi ;;
+        -*) printf "%s\\n" "Unrecognized option: ${arg}" >&2; _usage ;;
+    esac
 done
 
-mysql -u"${DBUSER}" -p"${DBPASSWD}" -A < "${BACKUPDIR}"/kill_sleep.sql
-mysql -u"${DBUSER}" -p"${DBPASSWD}" -Ae"UNLOCK TABLES;"
+if [ -z "${1}" ]; then
+    module="mysql"
+else
+    case "${1}" in
+        mysql) module="${1}"; shift; ;;
+        *)     _die "module \`${arg}' unsupported" ;;
+    esac
+fi
 
-tar cvf - "$(find "${BACKUPDIR}" -type f -iname "*sql")" | gzip > "${BACKUPDIR}"/dbs.tar.gz
+[ -z "${backup_dir}" ] && backup_dir="$(pwd)"
+if ! mkdir -p "${backup_dir}"/.dump-dbs >/dev/null 2>&1; then
+    printf "%s\\n" "\`${backup_dir}' is not writable, using \`/tmp' as base instead" >&2
+    backup_dir="/tmp"
+else
+    rm -rf -- "${backup_dir}"/.dump-dbs
+fi
 
-END="$(date +%s)"
-DIFF="$((${END} - ${START}))"
+if [ -z "${_var_config_file}" ]; then
+    if [ -f ./.dump-dbs ]; then
+        _loadconf ./.dump-dbs
+    elif [ -f ~/.dump-dbs ]; then
+        _loadconf ~/.dump-dbs
+    elif [ -f /etc/dump-dbs ]; then
+        _loadconf /etc/dump-dbs
+    fi
+else
+    [ ! -f "${_var_config_file}" ] && _die "couldn't find \`${_var_config_file}'"
+    _loadconf "${_var_config_file}"
+fi
 
-printf "%s\\n" "$(date +"%d-%m-%Y"):$(_printtime ${DIFF})" | tee -a "${BACKUPDIR}"/time.txt
+if [ -z "${module}" ] || [ -z "${user}" ] || [ -z "${passwd}" ] || [ -z "${backup_dir}" ]; then
+    _usage
+fi
+
+exec 9>/tmp/$(expr "${0}" : '.*/\([^/]*\)').lock #http://mywiki.wooledge.org/BashFAQ/045
+if ! flock -n 9  ; then
+    printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): another instance is running";
+    exit 1
+fi
+
+case "${module}" in
+    mysql) _mysql ;;
+esac
diff --git a/sh/tools/lp-g9n-team b/sh/tools/lp-g9n-team
--- a/sh/tools/lp-g9n-team
+++ b/sh/tools/lp-g9n-team
@@ -1,54 +1,35 @@
 #!/bin/sh
+#description: create cvs files with geolocalization data of launchpad groups
+#http://viajemotu.wordpress.com/2013/11/14/launchpad-maps/
+#usage: lp-g9n-team [lp group]
 
-_basename()
-{
-    [ -z "${1}" ] && return 1 || _basename_var_1="${1}"
-    [ -z "${2}" ] || _basename_var_suffix="${2}"
-    case "${_basename_var_1}" in
-        /*|*/*) _basename_var_1="$(expr "${_basename_var_1}" : '.*/\([^/]*\)')" ;;
-    esac
-
-    if [ -n "${_basename_var_suffix}" ] && [ "${#_basename_var_1}" -gt "${#2}" ]; then
-        if [ X"$(printf "%s" "${_basename_var_1}" | cut -c"$((${#_basename_var_1} - ${#_basename_var_suffix} + 1))")" \
-           = X"$(printf "%s" "${_basename_var_suffix}" | cut -c1)" ]; then
-            while [ "${#_basename_var_suffix}" -gt "0" ]; do
-                if [ X"$(printf "%s" "${_basename_var_1}" | cut -c"${#_basename_var_1}")" \
-                   = X"$(printf "%s" "${_basename_var_suffix}" | cut -c"${#_basename_var_suffix}")" ]; then
-                    _basename_var_1="$(printf "%s" "${_basename_var_1}" | cut -c1-"$((${#_basename_var_1} - 1))")"
-                    _basename_var_suffix_len="$((${#_basename_var_suffix} - 1))"
-                    if [ "${_basename_var_suffix_len}" -gt "0" ]; then
-                        _basename_var_suffix="$(printf "%s" "${_basename_var_suffix}" | cut -c1-"${_basename_var_suffix_len}")"
-                    else
-                        _basename_var_suffix=""
-                    fi
-                fi
-            done
-        fi
-    fi
-
-    printf "%s\\n" "${_basename_var_1}"
-}
+#example: lp-g9n-team ubuntumembers
+#Outputing data to "lp-g9n-team.csv"
+#Member,City,Latitude,Longitude
+#ivarela,Madrid,40.4167754,-3.7037902
+#..
 
 _usage()
 {
-    printf "%s\\n" "Usage: $(_basename ${0}) [lp-group]"
-    printf "%s\\n" "       lp-group   launchpad group to query, ubuntumembers by default"
-    exit 0
+    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [lp-group]" >&2
+    printf "%s\\n" "       lp-group   launchpad group to query, ubuntumembers by default" >&2
+    exit 1
 }
 
 _whereis()
 {
     [ -z "${1}" ] && return 1
     [ -n "${2}" ] && return 1
-    if ! command -v "${1}" 2>/dev/null; then
+    if ! command -v "${1}" >/dev/null 2>&1; then
         return 1
     fi
 }
 
 _die()
-{   #print a stacktrace with a msg, exits with 1
-    printf "%s\\n" "${*}"
-    exit
+{
+    [ -z "${1}" ] && return 1
+    printf "%b\\n" "$(expr "${0}" : '.*/\([^/]*\)'): ${*}" >&2
+    exit 1
 }
 
 _internetavailable()
@@ -64,29 +45,28 @@ _internetavailable()
     fi
 }
 
-_deps()
-{
-    _whereis python >/dev/null || _die "$(_basename ${0}): python not found!, $ sudo apt-get install python"
-    _whereis wget   >/dev/null || _die "$(_basename ${0}): wget not found!, $ sudo apt-get install wget"
-
-    if ! _internetavailable; then
-        _die "$(_basename ${0}): You must have an internet connection to run this script"
-        exit 1
-    fi
-
-    if ! $(printf "%s" "from launchpadlib.launchpad import Launchpad" | python >/dev/null 2>/dev/null); then
-        _die "$(_basename ${0}): launchpadlib not found!, $ sudo apt-get install python-launchpadlib"
-    fi
-
-    if ! $(printf "%s" "from geopy import geocoders" | python >/dev/null 2>/dev/null ); then
-        _die "$(_basename ${0}): geopy not found!, $ sudo apt-get install python-pip && sudo pip install geopy"
-    fi
-}
+if [ ! -t 0 ]; then
+    #there is input comming from pipe or file, add to the end of $@
+    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
+fi
 
 [ -n "${1}" ] && team="${1}" || team="ubuntumembers"
 
-_deps
+_whereis python || _die "$(expr "${0}" : '.*/\([^/]*\)'): python was not found!, $ sudo apt-get install python"
+_whereis wget   || _die "$(expr "${0}" : '.*/\([^/]*\)'): wget was not found!, $ sudo apt-get install wget"
 
-[ -f lp-g9n.py ] || wget https://raw.github.com/chilicuil/learn/master/python/lp-g9n -O lp-g9n.py >/dev/null 2>/dev/null
-[ -f lp-g9n.py ] && printf "%s\\n" "Outputing data to \"lp-g9n-team.csv\"" || _die "lp-g9n-team: failed to connect to launchpad, verify your connection"
-python lp-g9n.py "${team}" | tee lp-g9n-team.csv
+if ! $(printf "%s" "from launchpadlib.launchpad import Launchpad" | python >/dev/null 2>&1); then
+    _die "$(expr "${0}" : '.*/\([^/]*\)'): launchpadlib was not found!, $ sudo apt-get install python-launchpadlib"
+fi
+
+if ! $(printf "%s" "from geopy import geocoders" | python >/dev/null 2>&1); then
+    _die "$(expr "${0}" : '.*/\([^/]*\)'): geopy was not found!, $ sudo apt-get install python-pip && sudo pip install geopy"
+fi
+
+if ! _internetavailable; then
+    _die "$(expr "${0}" : '.*/\([^/]*\)'): you must have an active internet connection to run this script"
+fi
+
+[ -f /tmp/lp-g9n.py ] || wget https://raw.github.com/chilicuil/learn/master/python/lp-g9n -O /tmp/lp-g9n.py >/dev/null 2>&1
+[ -f /tmp/lp-g9n.py ] && printf "%s\\n" "Outputing data to \"lp-g9n-team.csv\"" || _die "lp-g9n-team: failed to connect to launchpad, verify your connection"
+python /tmp/lp-g9n.py "${team}" | tee lp-g9n-team.csv
diff --git a/sh/tools/setup b/sh/tools/setup
--- a/sh/tools/setup
+++ b/sh/tools/setup
@@ -38,8 +38,6 @@ _script()
         _exec chmod +x "${file}"
         _exec sudo cp -- "${file}" /usr/local/bin
     done
-
-    exit 0
 }
 
 _autocp()
@@ -47,9 +45,12 @@ _autocp()
     [ -n "${1}" ] || (printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): Missing parameter, looking for an .autocp file"; exit 1)
 
     for file; do
-        _exec sudo cp -- "${file}" /usr/share/bash-completion/completions/
+        if [ -d /usr/share/bash-completion/completions/ ]; then
+            _exec sudo cp -- "${file}" /usr/share/bash-completion/completions/
+        elif [ -d /etc/bash_completion.d/ ]; then
+            _exec sudo cp -- "${file}" /etc/bash_completion.d/
+        fi
     done
-    exit 0
 }
 
 if [ ! -t 0 ]; then
@@ -59,11 +60,10 @@ fi
 
 if [ X"${#}" != X"0" ]; then
     case "${1}" in
-        script) shift; _script "${@}" ;;
-        autocp) shift; _autocp "${@}" ;;
-        -h | --help)           _usage ;;
-        *) printf "%s\\n" "Error, unknown option: ${1}" >&2
-           _usage ;;
+        script)    shift; _script "${@}" ;;
+        autocp)    shift; _autocp "${@}" ;;
+        -h|--help) _usage ;;
+        *)         printf "%s\\n" "Error, unknown option: ${1}" >&2; _usage ;;
     esac
 else
     _usage
diff --git a/sh/tools/share-backup b/sh/tools/share-backup
--- a/sh/tools/share-backup
+++ b/sh/tools/share-backup
@@ -1,16 +1,21 @@
 #!/bin/sh
+#description: share a directory over http
+#usage: share-backup [-u USER|-p PORT|-P PASSWD|-c CERT|-h] [stop] [directory|file]
 
-PASSWD="$(date +%s | sha256sum | base64 | head -c 8)"
-USER="guest"
-PORT="$(($(tr -cd 0-9 </dev/urandom | head -c 4) + 1025))"
-BACKUP_DIR="$HOME/recovery"
-CERT="/path/server.pem"
-
-if [ X"${1}" = X"stop" ]; then
-    ID="$(pgrep -f simple-httpd)"
-    [ -n "$ID" ] && { kill -9 "${ID}"; printf "%s\\n" "Stopped"; } || printf "%s\\n" "No instance found"
-    exit
-fi
+#example: share-backup backup
+#Starting server ..."
+#  address   : http://127.0.0.1:2232
+#  address   : http://192.168.1.2:2232
+#  address   : http://203.212.2.34:2232
+#  address   : http://f.javier.io:2232
+#
+#  username: guest
+#  password: Ni3k8alskk2
+#  ssl     : yes
+#
+#  serving:  backup"
+#
+#Run: share-backup stop, to stop sharing"
 
 _basename()
 {
@@ -41,29 +46,110 @@ _basename()
     printf "%s\\n" "${_basename_var_1}"
 }
 
-exec 9> /tmp/$(_basename ${0}).lock #verify only one instance is running
-if ! flock -n 9; then               #http://mywiki.wooledge.org/BashFAQ/045
-    printf "%s\\n" "$(_basename ${0}): another instance is running";
+_usage()
+{
+    printf "%b\\n" "Usage: $(_basename "${0}") [OPTION]... [DIRECTORY|FILE]" >&2
+    printf "\\n" >&2
+    printf "%b\\n" "  stop            stop sharing" >&2
+    printf "\\n" >&2
+    printf "%b\\n" "  -h              show this text" >&2
+    printf "%b\\n" "  -u [USER]       set user (guest by default)" >&2
+    printf "%b\\n" "  -p [PORT]       set port (random above 1025 by default)" >&2
+    printf "%b\\n" "  -P [PASSWORD]   recover archived files" >&2
+    printf "%b\\n" "  -c [CERT_FILE]  set certificate.pem" >&2
+    printf "\\n" >&2
+
+    exit 1
+}
+
+#because of being used over ssh stdin get connected to the remote shell and stay waiting for input
+#so I'll disable reading from pipes till I figure out a solution
+#if [ ! -t 0 ]; then
+    ##there is input comming from pipe or file, add to the end of $@
+    #set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
+#fi
+
+if [ X"${1}" = X"stop" ]; then
+    ID="$(pgrep -f simple-httpd)"
+    [ -n "$ID" ] && { kill -9 "${ID}"; printf "%s\\n" "Stopped"; } || printf "%s\\n" "No instance found" >&2
+    exit
+fi
+
+if ! command -v "simple-httpd" >/dev/null 2>&1; then
+    printf "%s\\n" "$(_basename "${0}"): simple-httpd was not found!" >&2
+    printf "%s\\n" "download it at: https://raw.github.com/chilicuil/learn/master/python/simple-httpd" >&2
     exit 1
 fi
 
-[ -f "${CERT}" ] && SSL_OPTS="--ssl --certificate=${CERT}"
+for var; do #parse options
+    case "${var}" in
+        -h) _usage ;;
+        -u) if [ "${#}" -gt "1" ]; then
+                user="$(printf "%s " "${@}" | awk '{print $2}')"
+                shift 2
+            else
+               printf "%s\\n" "Option ${var} requires a parameter" >&2; exit 1
+            fi ;;
+        -p) if [ "${#}" -gt "1" ]; then
+                port="$(printf "%s " "${@}" | awk '{print $2}')"
+                shift 2
+            else
+               printf "%s\\n" "Option ${var} requires a parameter" >&2; exit 1
+            fi ;;
+        -P) if [ "${#}" -gt "1" ]; then
+                passwd="$(printf "%s " "${@}" | awk '{print $2}')"
+                shift 2
+            else
+               printf "%s\\n" "Option ${var} requires a parameter" >&2; exit 1
+            fi ;;
+        -c) if [ "${#}" -gt "1" ]; then
+                cert="$(printf "%s " "${@}" | awk '{print $2}')"
+                shift 2
+            else
+               printf "%s\\n" "Option ${var} requires a parameter" >&2; exit 1
+            fi ;;
+        -*) printf "%s\\n" "Unrecognized option: ${var}" >&2; _usage ;;
+    esac
+done
 
-#TODO 29-03-2014 18:09 >> remote fixed path
-if command -v "simple-httpd" >/dev/null 2>&1; then
-    printf "%s\\n" "Starting server ..."
-    printf "%s\\n" "  address   : http://b.javier.io:${PORT}"
-    printf "%s\\n"
-    printf "%s\\n" "  username: ${USER}"
-    printf "%s\\n" "  password: ${PASSWD}"
-    printf "%s\\n" "  ssl     : ${SSL_OPTS}"
-    printf "%s\\n"
-    printf "%s\\n" "  serving:  ${BACKUP_DIR}"
-    printf "%s\\n"
-    printf "%s\\n" "Run: $(_basename ${0}) stop, to stop sharing"
-    eval simple-httpd -p "${PORT}" --username="${USER}" --password="${PASSWD}" "${SSL_OPTS}" "${BACKUP_DIR}"/* >/dev/null 2>&1 &
+exec 9> /tmp/$(_basename ${0}).lock #verify only one instance is running
+if ! flock -n 9; then               #http://mywiki.wooledge.org/BashFAQ/045
+    printf "%s\\n" "$(_basename ${0}): another instance is running"; >&2
+    _usage
+fi
+
+[ -z "${user}" ]   && user="guest"
+[ -z "${port}" ]   && port="$(($(tr -cd 0-9 </dev/urandom | head -c 4) + 1025))"
+[ -z "${passwd}" ] && passwd="$(date +%s | sha256sum | base64 | head -c 8)"
+[ -f "${cert}" ]   && ssl_opts="--ssl --certificate=${CERT}"
+
+if [ -z "${@}" ]; then
+    [ -d recovery ] && files="recovery" || files="$(pwd)"
 else
-    printf "%s\\n" "Error: simple-httpd was not found!"
-    printf "%s\\n" "Info : download it at: https://raw.github.com/chilicuil/learn/master/python/simple-httpd"
-    exit 1
+    files="${@}"
+fi
+
+ips="$(ifconfig | grep "inet " | cut -d: -f2 | cut -d " " -f1)"
+ip="$(dig -4 +short myip.opendns.com @resolver1.opendns.com 2>/dev/null)"
+ips="${ips} ${ip} $(dig -4 -x "${ip}" | awk '/\.$/ {gsub(/\.$/,""); print $NF; exit;}')"
+
+printf "%s\\n" "Starting server ..."
+for addr in ${ips}; do
+    printf "%s\\n" "  address : http://${addr}:${port}"
+done
+printf "%s\\n"
+printf "%s\\n" "  username: ${user}"
+printf "%s\\n" "  password: ${passwd}"
+if [ -n "${ssl_opts}" ]; then
+    printf "%s\\n" "  ssl     : ${ssl_opts}"
+fi
+printf "%s\\n"
+printf "%s\\n" "  serving:  ${files}"
+printf "%s\\n"
+printf "%s\\n" "Run: $(_basename ${0}) stop, to stop sharing"
+
+if [ -d "${files}" ]; then
+    eval simple-httpd -p "${port}" --username="${user}" --password="${passwd}" "${ssl_opts}" "${files}"/* >/dev/null 2>&1 &
+else
+    eval simple-httpd -p "${port}" --username="${user}" --password="${passwd}" "${ssl_opts}" "${files}" >/dev/null 2>&1 &
 fi
