improve notification integration

diff --git a/sh/tools/mkpass b/sh/tools/mkpass
--- a/sh/tools/mkpass
+++ b/sh/tools/mkpass
@@ -2,6 +2,8 @@
 #description: create a secure password with 8 chars by default
 #usage: mkpass [LENGTH]
 
+#exec >/home/chilicuil/log 2>&1
+#set -x
 _usage()
 {
     printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [length]" >&2
@@ -14,6 +16,36 @@ _die()
     [ -z "${1}" ] && return 1
     printf "%s\\n" "${*}" >&2
     _usage
+}
+
+_notify() {
+    #output messages through the notification system, prints to
+    #stdout in the worst escenario
+    [ -z "${1}" ] && return 1
+    if [ X"${TERM}" = X"linux" ] || [ -z "${TERM}" ]; then
+        kill -9 $(pgrep notify-osd) >/dev/null 2>&1
+        if ! DISPLAY=:0 notify-send -t 1000 "${1}" "${3}"; then
+            if command -v "gxmessage" 2>/dev/null; then
+                font="Monaco 9"
+                DISPLAY=:0 gxmessage "${font:+-fn "$font"}" "${1}" "ok"
+            else
+                font="fixed"
+                DISPLAY=:0 xmessage "${font:+-fn "$font"}" "${1}" "ok"
+            fi
+        fi
+    else
+        printf "%s\\n" "${2}"
+    fi
+    case "${3}" in
+        *clipboard*)
+            #dumping xclip's stdout to the bitbucket works around xclip's
+            #failure to properly daemonize
+            #https://sourceforge.net/p/xclip/patches/9/
+            printf "%s" "${2}" | xclip -selection clipboard -i >/dev/null 2>&1 || \
+            printf "%s" "${2}" | xsel -bi 2>/dev/null || \
+            printf "%s" "${2}" | pbcopy 2>/dev/null   || :
+            ;;
+    esac
 }
 
 if [ ! -t 0 ]; then
@@ -39,14 +71,14 @@ else
     esac
 fi
 
-if command -v "xclip" >/dev/null 2>&1; then
-    if [ ! -t 1 ] || [ -z "${DISPLAY}" ]; then
-        printf "%b" "$(strings /dev/urandom | grep -o '[[:alnum:]]' | head -n "${mkpasswd_length}" | tr -d '\n')"
-    else
-    #http://unix.stackexchange.com/questions/28503/how-can-i-send-stdout-to-multiple-commands
-        strings /dev/urandom | grep -o '[0-9a-Z_./~:,;()!?%*#$%&+=@-]' | head -n "${mkpasswd_length}" \
-            | tr -d '\n' | xclip -selection clipboard; xclip -o -selection clipboard; printf "\\n"
-    fi
+#http://unix.stackexchange.com/questions/28503/how-can-i-send-stdout-to-multiple-commands
+passwd="$(strings /dev/urandom | grep -o '[0-9a-Z_./~:,;()!?%*#$%&+=@-]' | \
+          head -n "${mkpasswd_length}" | tr -d '\n' 2>/dev/null)"
+
+if [ -z "${passwd}" ];then
+    _die "$(expr "${0}" : '.*/\([^/]*\)'): couldn't generate password"
 else
-    strings /dev/urandom | grep -o '[0-9a-Z_./~:,;()!?%*#$%&+=@-]' | head -n "${mkpasswd_length}" | tr -d '\n'; printf "\\n"
+    clipboard_text="Copied to clipboard!"
 fi
+
+_notify "${passwd}" "${passwd}" "${clipboard_text}"
diff --git a/sh/tools/translate b/sh/tools/translate
--- a/sh/tools/translate
+++ b/sh/tools/translate
@@ -21,6 +21,36 @@ _usage()
     exit 1
 }
 
+_notify() {
+    #output messages through the notification system, prints to
+    #stdout in the worst escenario
+    [ -z "${1}" ] && return 1
+    if [ X"${TERM}" = X"linux" ] || [ -z "${TERM}" ]; then
+        kill -9 $(pgrep notify-osd) >/dev/null 2>&1
+        if ! DISPLAY=:0 notify-send -t 1000 "${1}" "${3}"; then
+            if command -v "gxmessage" 2>/dev/null; then
+                font="Monaco 9"
+                DISPLAY=:0 gxmessage "${font:+-fn "$font"}" "${1}" "ok"
+            else
+                font="fixed"
+                DISPLAY=:0 xmessage "${font:+-fn "$font"}" "${1}" "ok"
+            fi
+        fi
+    else
+        printf "%s\\n" "${2}"
+    fi
+    case "${3}" in
+        *clipboard*)
+            #dumping xclip's stdout to the bitbucket works around xclip's
+            #failure to properly daemonize
+            #https://sourceforge.net/p/xclip/patches/9/
+            printf "%s" "${2}" | xclip -selection clipboard -i >/dev/null 2>&1 || \
+            printf "%s" "${2}" | xsel -bi 2>/dev/null || \
+            printf "%s" "${2}" | pbcopy 2>/dev/null   || :
+            ;;
+    esac
+}
+
 _translate()
 {
     [ -z "${1}" ] && return 1
@@ -29,17 +59,16 @@ _translate()
     _translate__page="$(curl -s -i --user-agent "" -d "sl=${sl}" -d "tl=${tl}"      \
                            -d "client=t"  -d "ie=UTF-8" -d "oe=UTF-8" --data-urlencode \
                            "text=${_translate__phrase}" http://translate.google.com/translate_a/t)"
-    _translate__result="$(printf "%s\\n" "${_translate__page}" | tail -1 | cut -d\" -f2)"
+    _translate__result="$(printf "%s" "${_translate__page}" | tail -1 | cut -d\" -f2)"
 
-    if command -v "xclip" >/dev/null 2>&1; then
-        if [ ! -t 1 ] || [ -z "${DISPLAY}" ] ; then
-            printf "%s\\n" "${_translate__result}"
-        else
-            printf "%s" "${_translate__result}" | xclip -selection clipboard; xclip -o -selection clipboard; printf "\\n"
-        fi
+    if [ -z "${_translate__result}" ];then
+       _translate__result="Translation api timeout"
     else
-        printf "%s\\n" "${_translate__result}"
+        _translate__clipboard_text="Copied to clipboard!"
     fi
+
+    _notify "${_translate__result}" "${_translate__result}" \
+            "${_translate__clipboard_text}"
 }
 
 if [ ! -t 0 ]; then
diff --git a/sh/tools/uimg b/sh/tools/uimg
--- a/sh/tools/uimg
+++ b/sh/tools/uimg
@@ -12,33 +12,54 @@ _usage()
     exit 1
 }
 
+_notify() {
+    #output messages through the notification system, prints to
+    #stdout in the worst escenario
+    [ -z "${1}" ] && return 1
+    if [ X"${TERM}" = X"linux" ] || [ -z "${TERM}" ]; then
+        kill -9 $(pgrep notify-osd) >/dev/null 2>&1
+        if ! DISPLAY=:0 notify-send -t 1000 "${1}" "${3}"; then
+            if command -v "gxmessage" 2>/dev/null; then
+                font="Monaco 9"
+                DISPLAY=:0 gxmessage "${font:+-fn "$font"}" "${1}" "ok"
+            else
+                font="fixed"
+                DISPLAY=:0 xmessage "${font:+-fn "$font"}" "${1}" "ok"
+            fi
+        fi
+    else
+        printf "%s\\n" "${2}"
+    fi
+    case "${3}" in
+        *clipboard*)
+            #dumping xclip's stdout to the bitbucket works around xclip's
+            #failure to properly daemonize
+            #https://sourceforge.net/p/xclip/patches/9/
+            printf "%s" "${2}" | xclip -selection clipboard -i >/dev/null 2>&1 || \
+            printf "%s" "${2}" | xsel -bi 2>/dev/null || \
+            printf "%s" "${2}" | pbcopy 2>/dev/null   || :
+            ;;
+    esac
+}
+
 _uimg()
 {
     for _uimg__img; do
         if [ -f "${_uimg__img}" ] ; then
             case "${_uimg__img}" in
                 *.jpg|*.JPG|*.jpeg|*.png|*.PNG)
-                    if command -v "xclip" >/dev/null 2>&1; then
-                        if [ ! -t 1 ] || [ -z "${DISPLAY}" ]; then
-                            curl -s -F "image=@${_uimg__img}"                   \
+                    _uimg__url="$( curl -s -F "image=@${_uimg__img}"               \
                                 -F "key=486690f872c678126a2c09a9e196ce1b"          \
                                 http://imgur.com/api/upload.xml |                  \
                                 egrep -o "<original_image>(.)*</original_image>" | \
-                                egrep -o "http://i.imgur.com/[^<]*"
-                        else
-                            curl -s -F "image=@${_uimg__img}"                   \
-                                -F "key=486690f872c678126a2c09a9e196ce1b"          \
-                                http://imgur.com/api/upload.xml |                  \
-                                egrep -o "<original_image>(.)*</original_image>" | \
-                                egrep -o "http://i.imgur.com/[^<]*" | xclip -selection clipboard; xclip -o -selection clipboard
-                        fi
+                                egrep -o "http://i.imgur.com/[^<]*")"
+                    if [ -z "${_uimg__url}" ];then
+                        _uimg__url="http://imgur.com api timeout"
                     else
-                        curl -s -F "image=@${_uimg__img}"                   \
-                            -F "key=486690f872c678126a2c09a9e196ce1b"          \
-                            http://imgur.com/api/upload.xml |                  \
-                            egrep -o "<original_image>(.)*</original_image>" | \
-                            egrep -o "http://i.imgur.com/[^<]*"
-                    fi ;;
+                        _uimg__clipboard_text="Copied to clipboard!"
+                    fi
+                    _notify "${_uimg__url}" "${_uimg__url}" "${_uimg__clipboard_text}"
+                    ;;
                 *)  printf "%s\\n" "'${_uimg__img}' is not a valid image file" >&2 ;;
             esac
         else
diff --git a/sh/tools/weather b/sh/tools/weather
--- a/sh/tools/weather
+++ b/sh/tools/weather
@@ -30,16 +30,19 @@ _notify() {
                 DISPLAY=:0 xmessage "${font:+-fn "$font"}" "${1}" "ok"
             fi
         fi
-        case "${3}" in
-            *clipboard*)
-                printf "%s\\n" "${2}" | xclip -selection clipboard 2>/dev/null
-                printf "%s\\n" "${2}" | xsel -bi 2>/dev/null
-                printf "%s\\n" "${2}" | pbcopy 2>/dev/null
-                ;;
-        esac
     else
         printf "%s\\n" "${2}"
     fi
+    case "${3}" in
+        *clipboard*)
+            #dumping xclip's stdout to the bitbucket works around xclip's
+            #failure to properly daemonize
+            #https://sourceforge.net/p/xclip/patches/9/
+            printf "%s" "${2}" | xclip -selection clipboard -i >/dev/null 2>&1 || \
+            printf "%s" "${2}" | xsel -bi 2>/dev/null || \
+            printf "%s" "${2}" | pbcopy 2>/dev/null   || :
+            ;;
+    esac
 }
 
 _weather() {
