general cleanup

diff --git a/sh/tools/share-backup b/sh/tools/share-backup
--- a/sh/tools/share-backup
+++ b/sh/tools/share-backup
@@ -17,6 +17,8 @@
 #
 #Run: share-backup stop, to stop sharing"
 
+upstream_url_httpd='https://raw.github.com/chilicuil/learn/master/python/simple-httpd'
+
 _basename() {
     [ -z "${1}" ] && return 1 || _basename__name="${1}"
     [ -z "${2}" ] || _basename__suffix="${2}"
@@ -72,9 +74,18 @@ if [ X"${1}" = X"stop" ]; then
 fi
 
 if ! command -v "simple-httpd" >/dev/null 2>&1; then
-    printf "%s\\n" "$(_basename "${0}"): simple-httpd was not found!" >&2
-    printf "%s\\n" "download it from: https://raw.github.com/chilicuil/learn/master/python/simple-httpd" >&2
-    exit 1
+    wget -q "${upstream_url_httpd}" -O- > /tmp/simple-httpd 2>/dev/null || \
+    wget -q --no-check-certificate "${upstream_url_httpd}" -O- > /tmp/simple-httpd 2>/dev/null || \
+    curl -s -f -L "${upstream_url_httpd}" > /tmp/simple-httpd 2>/dev/null || \
+    curl -s -f -L -k "${upstream_url_httpd}" > /tmp/simple-httpd 2>/dev/null || {
+        printf "%s\\n" "$(_basename "${0}"): simple-httpd was not found!" >&2
+        printf "%s\\n" "download it from ${upstream_url_httpd}" >&2
+        exit 1
+    }
+
+    httpd="python /tmp/simple-httpd"
+else
+    httpd="simple-httpd"
 fi
 
 for arg; do #parse options
@@ -148,9 +159,9 @@ printf "%s\\n"
 printf "%s\\n" "Run: $(_basename "${0}") stop, to stop sharing"
 
 if [ -d "${files}" ]; then
-    eval simple-httpd -p "${port}" --username="${user}" \
+    eval "${httpd}" -p "${port}" --username="${user}" \
         --password="${passwd}" "${ssl_opts}" "${files}"/* >/dev/null 2>&1 &
 else
-    eval simple-httpd -p "${port}" --username="${user}" \
+    eval "${httpd}" -p "${port}" --username="${user}" \
         --password="${passwd}" "${ssl_opts}" "${files}" >/dev/null 2>&1 &
 fi
