tools/share-backup: update upstream url

diff --git a/sh/tools/share-backup b/sh/tools/share-backup
--- a/sh/tools/share-backup
+++ b/sh/tools/share-backup
@@ -17,7 +17,7 @@
 #
 #Run: share-backup stop, to stop sharing"
 
-upstream_url_httpd='https://raw.github.com/chilicuil/learn/master/python/simple-httpd'
+upstream_url_httpd='https://raw.githubusercontent.com/chilicuil/learn/master/python/tools/simple-httpd'
 
 _basename() {
     [ -z "${1}" ] && return 1 || _basename__name="${1}"
@@ -73,22 +73,7 @@ if [ X"${1}" = X"stop" ]; then
         { printf "%s\\n" "No instance found" >&2; exit 1; }
 fi
 
-if ! command -v "simple-httpd" >/dev/null 2>&1; then
-    wget -q "${upstream_url_httpd}" -O- > /tmp/simple-httpd 2>/dev/null || \
-    wget -q --no-check-certificate "${upstream_url_httpd}" -O- > /tmp/simple-httpd 2>/dev/null || \
-    curl -s -f -L "${upstream_url_httpd}" > /tmp/simple-httpd 2>/dev/null || \
-    curl -s -f -L -k "${upstream_url_httpd}" > /tmp/simple-httpd 2>/dev/null || {
-        printf "%s\\n" "$(_basename "${0}"): simple-httpd was not found!" >&2
-        printf "%s\\n" "download it from ${upstream_url_httpd}" >&2
-        exit 1
-    }
-
-    httpd="python /tmp/simple-httpd"
-else
-    httpd="simple-httpd"
-fi
-
-for arg; do #parse options
+for arg in "${@}"; do #parse options
     case "${arg}" in
         -h|--help) _usage && exit ;;
         -u) if [ "${#}" -gt "1" ]; then
@@ -121,6 +106,21 @@ for arg; do #parse options
         -*) _die "$(_basename "${0}"): unrecognized option '${arg}'" ;;
     esac
 done
+
+if ! command -v "simple-httpd" >/dev/null 2>&1; then
+    wget -q "${upstream_url_httpd}" -O- > /tmp/simple-httpd 2>/dev/null || \
+    wget -q --no-check-certificate "${upstream_url_httpd}" -O- > /tmp/simple-httpd 2>/dev/null || \
+    curl -s -f -L "${upstream_url_httpd}" > /tmp/simple-httpd 2>/dev/null || \
+    curl -s -f -L -k "${upstream_url_httpd}" > /tmp/simple-httpd 2>/dev/null || {
+        printf "%s\\n" "$(_basename "${0}"): simple-httpd was not found!" >&2
+        printf "%s\\n" "download it from ${upstream_url_httpd}" >&2
+        exit 1
+    }
+
+    httpd="python /tmp/simple-httpd"
+else
+    httpd="simple-httpd"
+fi
 
 exec 9> /tmp/"$(_basename "${0}")".lock #verify only one instance is running
 [ X"${LOGNAME}" = X"root" ] && chmod 666 /tmp/"$(_basename "${0}")".lock
