sh/tools/staticus: refactor _update()

diff --git a/sh/tools/staticus b/sh/tools/staticus
--- a/sh/tools/staticus
+++ b/sh/tools/staticus
@@ -224,50 +224,51 @@ _update() {
     _u__current_file="$(cd "$(dirname "${0}")" && pwd)/${progname}"
     _u__current_version_long="$(awk -F\" \
         '/VERSION=/{print $2;exit}' "${_u__current_file}" 2>/dev/null)"
-    _u__current_version="$(printf "%s" "${_u__current_version_long}" | awk \
-        '{gsub(/[\.:]/,"");gsub(/-/,"");print;exit}' 2>/dev/null)"
-    [ -z "${_u__current_version}" ] && printf "%s\\n%s\\n%s\\n"    \
+    _u__current_version="$(printf "%s\\n" "${_u__current_version_long}" | \
+        awk '{gsub(/[\.:]/,"");gsub(/-/,"");print;exit}' 2>/dev/null)"
+    [ -z "${_u__current_version}" ] && printf "%s\\n%s\\n%s\\n"           \
         "ERROR: Failed to detect current version, please update manually" \
-        "${progname}         = ${_u__current_file}"                 \
+        "${progname}         = ${_u__current_file}"                       \
         "${progname} version = ${_u__current_version}" >&2 && return 1
 
-    command -v "wget" >/dev/null 2>&1 || command -v "curl" >/dev/null 2>&1 || { \
-    printf "%s\\n" "ERROR: Install either 'wget' or 'curl' to update within the program" >&2
-    return 1; }
+    command -v "wget" >/dev/null 2>&1 || command -v "curl" >/dev/null 2>&1 || \
+        { printf "%s\\n" "ERROR: Install either 'wget' or 'curl' to upgrade" >&2; return 1; }
 
-    _u__error_msg="$(wget -q -O- --no-check-certificate \
-    https://raw.githubusercontent.com/javier-lopez/learn/master/sh/tools/${progname} \
-        > "/tmp/${progname}.${$}" 2>&1 || curl -s  \
-    https://raw.githubusercontent.com/javier-lopez/learn/master/sh/tools/${progname} \
-    > "/tmp/${progname}.${$}" 2>&1)"   || { printf "%s\\n%s\\n" \
+    _u__url="https://raw.githubusercontent.com/javier-lopez/learn/master/sh/tools/${progname}"
+    _u__tmpfile="/tmp/${progname}.${$}.update"
+
+    _u__error_msg="$(wget -q -O- --no-check-certificate "${_u__url}" \
+        > "${_u__tmpfile}" 2>&1   || curl -s "${_u__url}"  \
+        > "${_u__tmpfile}" 2>&1)" || { printf "%s\\n%s\\n" \
         "ERROR: Failed to fetch update, please try later or update manually" \
         "${_u__error_msg}" >&2; return 1; }
 
     _u__update_version_long="$(awk -F\" \
-        '/VERSION=/{print $2;exit}' "/tmp/${progname}.${$}" 2>/dev/null)"
+        '/VERSION=/{print $2;exit}' "${_u__tmpfile}" 2>/dev/null)"
     _u__update_version="$(printf "%s" "${_u__update_version_long}" | awk \
         '{gsub(/[\.:]/,"");gsub(/-/,"");print;exit}' 2>/dev/null)"
-    [ -z "${_u__update_version}" ] && _u__update_version="0"
+    [ -n "${_u__update_version}" ] || _u__update_version="0"
 
     if [ "${_u__current_version}" -lt "${_u__update_version}" ]; then
         printf "%s %s\\n" "Updating from version" \
             "${_u__current_version_long} to ${_u__update_version_long} ..."
-        chmod +x "/tmp/${progname}.${$}"
-        if ! mv -f "/tmp/${progname}.${$}" "${_u__current_file}" 2>/dev/null; then
+        chmod +x "${_u__tmpfile}"
+        if ! mv -f "${_u__tmpfile}" "${_u__current_file}" 2>/dev/null; then
             printf "%s\\n" "ERROR: no write permissions on ${_u__current_file}" >&2
             printf "%s\\n" "INFO : trying with sudo ..." >&2
             if command -v "sudo" >/dev/null 2>&1; then
-                sudo mv "/tmp/${progname}.${$}" "${_u__current_file}" || return 1
+                sudo mv "${_u__tmpfile}" "${_u__current_file}" || return 1
             else
                 printf "%s\\n" "ERROR: sudo isn't available, exiting ..." >&2
-                rm -rf "/tmp/${progname}.${$}"; return 1
+                rm -rf "${_u__tmpfile}"
+                return 1
             fi
         fi
         printf "%s %s\\n" "${progname} is up-to-date (${_u__update_version_long})"
         return 0
     fi
     printf "%s %s\\n" "${progname} is up-to-date (${_u__current_version_long})"
-    rm -rf "/tmp/${progname}.${$}"
+    rm -rf "${_u__tmpfile}"
 }
 
 _show_version() {
