sh/*: define and use the $progname variable

diff --git a/sh/tools/vim-show b/sh/tools/vim-show
--- a/sh/tools/vim-show
+++ b/sh/tools/vim-show
@@ -6,9 +6,10 @@
 #this
 #code
 #...
+progname="$(expr "${0}" : '.*/\([^/]*\)')"
 
 _usage() {
-    printf "Usage: %s\\n" "$(expr "${0}" : '.*/\([^/]*\)') script"
+    printf "Usage: %s\\n" "${progname} script"
 }
 
 _die() {
@@ -26,7 +27,7 @@ fi
 for arg in "${@}"; do #parse options
     case "${arg}" in
         -h|--help) _usage && exit ;;
-        -*) _die "$(expr "${0}" : '.*/\([^/]*\)'): unrecognized option '${arg}'" ;;
+        -*) _die "${progname}: unrecognized option '${arg}'" ;;
     esac
 done
 
@@ -34,11 +35,10 @@ script="${1}"
 
 if command -v "${script}" >/dev/null 2>&1; then
     [ -z "${EDITOR}" ] && { printf "%s\\n" \
-        "$(expr "${0}" : '.*/\([^/]*\)'): variable EDITOR was not found" >&2
+        "${progname}: variable EDITOR was not found" >&2
         exit 1; }
     ${EDITOR} "$(command -v "${script}" 2>/dev/null)"
 else
-    printf "$(expr "${0}" : '.*/\([^/]*\)'): %s\\n" \
-        "'${script}' was not found in \$PATH" >&2
+    printf "${progname}: %s\\n" "'${script}' was not found in \$PATH" >&2
     exit 1
 fi
