lib: cleanup

diff --git a/sh/lib b/sh/lib
--- a/sh/lib
+++ b/sh/lib
@@ -12,16 +12,19 @@
 #[+] must provide an example
 
 _addcron()
-{
+{   #adds cron job, returns 1 on error
     [ -z "$1" ] && return 1
     crontab -l | { cat; echo "$@"; } | crontab -
 }
+#==================================================== Example ====
+#_addcron "* * * * * /path/task"
+#=================================================================
 
 _animbarcui()
 {   #prints a bar of o@o moving
     [ -z "$1" ] && { printf "%4s\n" ""; return 1; }
-    pid=$1
-    animation_state=1
+    local pid=$1
+    local animation_state=1
 
     if [ ! "$(ps -p $pid -o comm=)" ]; then
         printf "%4s\n" ""
@@ -32,7 +35,7 @@ _animbarcui()
     local c=0; j=0;
 
     exec < /dev/tty
-    oldstty=$(stty -g)
+    local oldstty=$(stty -g)
     stty raw -echo min 0
     echo -en "\033[6n" > /dev/tty
     IFS=';' read -r -d R -a pos
@@ -121,8 +124,8 @@ _animbarcui()
 _animcui()
 {
     [ -z "$1" ] && { printf "%5s\n" ""; return 1; }
-    pid="$1"
-    animation_state=1
+    local pid="$1"
+    local animation_state=1
 
     if [ ! "$(ps -p $pid -o comm=)" ]; then
         printf "%5s\n" ""
@@ -163,8 +166,8 @@ _animcui()
 _animrotate()
 {   #shows an animation as long as a process is in memory
     [ -z "$1" ] && return 1
-    pid=$1
-    animation_state=1
+    local pid=$1
+    local animation_state=1
     echo -e -n "    "
 
     while [ "`ps -p $pid -o comm=`" ]; do
@@ -205,6 +208,26 @@ _animrotate()
 #==================================================== Example ====
 #echo -n "[+] tar" && _animrotate $(pidof tar)
 #=================================================================
+
+_cidr2mask()
+{
+  local i mask=""
+  local full_octets=$(($1/8))
+  local partial_octet=$(($1%8))
+
+  for ((i=0;i<4;i+=1)); do
+    if [ $i -lt $full_octets ]; then
+      mask+=255
+    elif [ $i -eq $full_octets ]; then
+      mask+=$((256 - 2**(8-$partial_octet)))
+    else
+      mask+=0
+    fi
+    test $i -lt 3 && mask+=.
+  done
+
+  echo $mask
+}
 
 _arch()
 {   #check for system arch, returns [64|32]
@@ -251,11 +274,26 @@ _cmd()
     echo "    $ $@"
     "$@"
 
-    status=$?
+    local status=$?
     [ "$status" != 0 ] && exit $status || return
 }
 #==================================================== Example ====
 #_cmd rm file
+#=================================================================
+
+_cmdsudo()
+{   #print && execute a command, exits if command fails
+    [ -z "$1" ] && return 0
+    local serr=$RANDOM
+
+    echo "    $ sudo $@"
+    echo "$sudopwd" | $sudocmd "$@" > /tmp/$serr.out 2>&1
+
+    local status=$?
+    [ "$status" != 0 ] && { cat /tmp/$serr.out; rm /tmp/$serr.out; exit $status; } || { rm /tmp/$serr.out; return; }
+}
+#==================================================== Example ====
+#_cmdsudo rm /file
 #=================================================================
 
 _decode64()
@@ -264,22 +302,8 @@ _decode64()
     echo "$1" | base64 --decode
 }
 #==================================================== Example ====
-string=$(_decode64 $string)
-[ -z "$string" ] && echo "fail, empty string"
-#=================================================================
-
-_cmdsudo()
-{   #print && execute a command, exits if command fails
-    [ -z "$1" ] && return 0
-
-    echo "    $ sudo $@"
-    echo "$sudopwd" | $sudocmd "$@" > /tmp/serr.out 2>&1
-
-    status=$?
-    [ "$status" != 0 ] && { cat /tmp/serr.out; rm /tmp/serr.out; exit $status; } || return
-}
-#==================================================== Example ====
-#_cmdsudo rm /file
+#string=$(_decode64 $string)
+#[ -z "$string" ] && echo "fail, empty string"
 #=================================================================
 
 _die()
@@ -296,15 +320,32 @@ _die()
 #[ -z "$var" ] && _die "error msg"
 #=================================================================
 
+_dirname()
+{   #returns string containing dirname on success, 1 on fail
+
+    #http://www.linuxmisc.com/12-unix-web-servers/d31beb238f7b5a6b.htm
+    if [ -z "$1" ]; then
+        return 1;
+    else
+        local dir="${1%${1##*/}}"
+        [ "${dir:=./}" != "/" ] && dir="${dir%?}"
+        echo "$dir"
+    fi
+}
+#==================================================== Example ====
+#_dirname /path/file #returns /path
+#=================================================================
+
 _distro()
 {   #return distro name in a lower string
 
-    DIST_INFO="/etc/lsb-release"
+    local DIST_INFO="/etc/lsb-release"
     if [ -r $DIST_INFO ]; then
         . $DIST_INFO
     fi
 
     if [ -z $DISTRIB_ID ]; then
+        local DISTRIB_ID="Unknown";
         if [ -f /etc/arch-release ]; then
             DISTRIB_ID="Arch"
         elif [ -r /etc/knoppix-version ]; then
@@ -342,8 +383,6 @@ _distro()
             DISTRIB_ID="YellowDog Linux"
         elif [ -f /etc/zenwalk-version  ]; then
             DISTRIB_ID="Zenwalk"
-        else
-            DISTRIB_ID="Unknown"
         fi
     fi
 
@@ -351,22 +390,6 @@ _distro()
 }
 #==================================================== Example ====
 #distro=$(_distro)
-#=================================================================
-
-_dirname()
-{   #returns string containing dirname on success, 1 on fail
-
-    #http://www.linuxmisc.com/12-unix-web-servers/d31beb238f7b5a6b.htm
-    if [ -z "$1" ]; then
-        return 1;
-    else
-        local dir="${1%${1##*/}}"
-        [ "${dir:=./}" != "/" ] && dir="${dir%?}"
-        echo "$dir"
-    fi
-}
-#==================================================== Example ====
-#_dirname /path/file #returns /path
 #=================================================================
 
 _download()
@@ -405,16 +428,6 @@ _download()
 #[ "$FILE" -eq 1 ] && echo error || echo "done: $FILE"
 #=================================================================
 
-_encode64()
-{
-    [ -z "$1" ] && echo ""
-    echo "$1" | base64
-}
-#==================================================== Example ====
-string=$(_encode64 $string)
-[ -z "$string" ] && echo "fail, empty string"
-#=================================================================
-
 _email()
 {   #send email, return 0 on success, 1 otherwise
     #requires: libio-socket-ssl-perl, libnet-ssleay-perl and sendemail
@@ -440,8 +453,29 @@ _email()
 #[ $(_mail $FROM $TO $TITLE $MESSAGE $SERVER $USER $PASSWD) -eq 0 ] && echo "send" || echo "error"
 #=================================================================
 
-_existuser()
+_encode64()
 {
+    [ -z "$1" ] && echo ""
+    echo "$1" | base64
+}
+#==================================================== Example ====
+#string=$(_encode64 $string)
+#[ -z "$string" ] && echo "fail, empty string"
+#=================================================================
+
+_existaptproxy()
+{   #test if an apt proxy exist on the local network, return 0 on sucess, 1 otherwise
+    avahi-browse -a  -t | grep -qs apt-cacher-ng && return 0
+    return 1
+}
+#==================================================== Example ====
+#if ! _existaptproxy; then
+    #echo "no apt proxy was found, setting up one ..."
+#fi
+#=================================================================
+
+_existuser()
+{   #test if an user exists on the system, return 0 on sucess, 1 otherwise
     if id -u $1 >/dev/null 2>&1; then
         return 0
     else
@@ -449,16 +483,10 @@ _existuser()
     fi
 }
 #==================================================== Example ====
-#if ! _existuser user; then
-    #echo "user exit ... "
+#if _existuser user; then
+    #echo "user was found ..."
 #fi
 #=================================================================
-
-_existaptproxy()
-{
-    avahi-browse -a  -t | grep -qs apt-cacher-ng && return 0
-    return 1
-}
 
 _fullpath()
 {   #return full path of the argument, return string on success, 1 on fail
@@ -466,7 +494,7 @@ _fullpath()
         return 1;
     else
         if [ `expr substr ${1:-a} 1 2` != "/" ]; then
-            full_file=`pwd`"/"$1
+            local full_file=`pwd`"/"$1
         fi
     fi
     echo $full_file
@@ -475,12 +503,40 @@ _fullpath()
 #_fullpath file #returns /path/file
 #=================================================================
 
+_getcol()
+{   #return an int with the col cursor position
+
+    #http://stackoverflow.com/questions/2575037/how-to-get-the-cursor-position-in-bash
+    exec < /dev/tty
+    local oldstty=$(stty -g)
+    stty raw -echo min 0
+    # on my system, the following line can be replaced by the line below it
+    echo -en "\033[6n" > /dev/tty
+    # tput u7 > /dev/tty    # when TERM=xterm (and relatives)
+    IFS=';' read -r -d R -a pos
+    stty $oldstty
+    # change from one-based to zero based so they work with: tput cup $row $col
+    local col=$((${pos[1]} - 1))
+    echo $col
+}
+#==================================================== Example ====
+#printf "%s" "Hi"
+#col=$(_getcol)
+#printf "%s" " - $col characters"
+#=================================================================
+
+_getfs()
+{
+    [ -z "$1" ] && return 1
+    udevadm info -q all -n "$1" | grep -i ID_FS_TYPE | cut -f2 -d'='
+}
+
 _getopt()
 {   #define vars for cli arguments
-    var=""
-    wantarg=0
+    local var=""
+    local wantarg=0
     for $(( i=1; i<=$#; i+=1 )); do
-        lastvar=$var
+        local lastvar=$var
         var=${!i}
         if [ "$var" = "" ]; then
             continue
@@ -488,9 +544,9 @@ _getopt()
         echo \ $var | grep -q -- '='
         if [ $? -eq 0 ]; then
             ## -*param=value
-            var=$(echo \ $var | sed -r s/'^[ ]*-*'/''/)
-            myvar=${var%=*}
-            myval=${var#*=}
+            local var=$(echo \ $var | sed -r s/'^[ ]*-*'/''/)
+            local myvar=${var%=*}
+            local myval=${var#*=}
             eval "${myvar}"="'$myval'"
         else
             echo \ $var | grep -E -q -- '^[ ]*-'
@@ -498,7 +554,7 @@ _getopt()
                 ## -*param$
                 var=$(echo \ $var | sed -r s/'^[ ]*-*'/''/)
                 eval "${var}"=1
-                wantarg=1
+                local wantarg=1
             else
                 echo \ $var | grep -E -- '^[ ]*-'
                 if [ $? -eq 0 ]; then
@@ -527,63 +583,6 @@ _getopt()
 #OIFS=$IFS; IFS=$(echo -e "\n"); _getopt $@; IFS=$OIFS
 ##./getopts --foo=bar -v -n 10 blah -one='last arg'
 #echo -e " foo:\t$foo v:\t$v n:\t$n blah:\t$blah one:\t$one "
-#=================================================================
-
-_getcol()
-{   #return an int with the col cursor position
-
-    #http://stackoverflow.com/questions/2575037/how-to-get-the-cursor-position-in-bash
-    exec < /dev/tty
-    oldstty=$(stty -g)
-    stty raw -echo min 0
-    # on my system, the following line can be replaced by the line below it
-    echo -en "\033[6n" > /dev/tty
-    # tput u7 > /dev/tty    # when TERM=xterm (and relatives)
-    IFS=';' read -r -d R -a pos
-    stty $oldstty
-    # change from one-based to zero based so they work with: tput cup $row $col
-    local col=$((${pos[1]} - 1))
-    echo $col
-}
-#==================================================== Example ====
-printf "%s" "Hi"
-col=$(_getcol)
-printf "%s" " - $col characters"
-#=================================================================
-
-_getfs()
-{
-    [ -z "$1" ] && return 1
-    udevadm info -q all -n "$1" | grep -i ID_FS_TYPE | cut -f2 -d'='
-}
-
-_getrow()
-{   #return an int with the col cursor position
-
-    #http://stackoverflow.com/questions/2575037/how-to-get-the-cursor-position-in-bash
-    exec < /dev/tty
-    oldstty=$(stty -g)
-    stty raw -echo min 0
-    # on my system, the following line can be replaced by the line below it
-    echo -en "\033[6n" > /dev/tty
-    # tput u7 > /dev/tty    # when TERM=xterm (and relatives)
-    IFS=';' read -r -d R -a pos
-    stty $oldstty
-    # change from one-based to zero based so they work with: tput cup $row $col
-    local row=$((${pos[0]:2} - 1))    # strip off the esc-[
-    echo $row
-}
-#==================================================== Example ====
-row=$(_getrow)
-printf "%s" "$row"
-#=================================================================
-
-_getuuid()
-{
-    [ -z "$1" ] && return 1
-    udevadm info -q all -n "$1" | grep -i uuid | egrep "^S:" | cut -f3 -d'/'
-}
-#==================================================== Example ====
 #=================================================================
 
 _getpasswd()
@@ -660,6 +659,35 @@ _getroot()
 #echo "$sudopwd" | $sudocmd rm file
 #=================================================================
 
+_getrow()
+{   #return an int with the col cursor position
+
+    #http://stackoverflow.com/questions/2575037/how-to-get-the-cursor-position-in-bash
+    exec < /dev/tty
+    local oldstty=$(stty -g)
+    stty raw -echo min 0
+    # on my system, the following line can be replaced by the line below it
+    echo -en "\033[6n" > /dev/tty
+    # tput u7 > /dev/tty    # when TERM=xterm (and relatives)
+    IFS=';' read -r -d R -a pos
+    stty $oldstty
+    # change from one-based to zero based so they work with: tput cup $row $col
+    local row=$((${pos[0]:2} - 1))    # strip off the esc-[
+    echo $row
+}
+#==================================================== Example ====
+row=$(_getrow)
+printf "%s" "$row"
+#=================================================================
+
+_getuuid()
+{
+    [ -z "$1" ] && return 1
+    udevadm info -q all -n "$1" | grep -i uuid | egrep "^S:" | cut -f3 -d'/'
+}
+#==================================================== Example ====
+#=================================================================
+
 _inarray()
 {   #look for a value in an array, returns 0 on success, 1 otherwise
     [ -z "$1" ] && return 1
@@ -676,11 +704,29 @@ _inarray()
 #_inarray $name ${names[@]} && echo found!
 #=================================================================
 
+_internetavailable()
+{   #check for internet connection, returns 0 on success, 1 otherwise
+    wget --tries=3 --timeout=5 http://www.google.com -O /tmp/index.google > /dev/null 2>&1
+
+    if [ -s /tmp/index.google ]; then
+        rm /tmp/index.google
+        return 0
+    else
+        rm /tmp/index.google
+        return 1
+    fi
+}
+#==================================================== Example ====
+#if ! _internetavailable; then
+    #echo "You must have an Internet connection to run this script" >&2
+    #exit 1
+#fi
+#=================================================================
+
 _isalphanum()
 { #check for alphanum strings, return 0 if all upper+lower+digits, 1 otherwise
-
   # Remove all unacceptable chars
-  compressed="$(echo $1 | sed -e 's/[^[:alnum:]]//g')"
+  local compressed="$(echo $1 | sed -e 's/[^[:alnum:]]//g')"
 
   [ "$compressed" != "$input" ] && return 1 || return 0
 }
@@ -709,21 +755,6 @@ _isarray()
     #echo "vararray is not an array"
 #fi
 #=================================================================
-
-_isip4valid()
-{   #return 0 if parameter is a valid ip4 address, non-zero otherwise
-    #https://groups.google.com/forum/#!original/comp.unix.shell/NDu-kAL5cHs/7Zpc6Q2Hu5YJ
-    case "$*" in
-        ""|*[!0-9.]*|*[!0-9]) return 1 ;;
-    esac
-
-    local IFS=.  ## local is bash-specific
-    set -- $*
-
-    [ $# -eq 4 ] &&
-        [ ${1:-666} -le 255 ] && [ ${2:-666} -le 255 ] &&
-        [ ${3:-666} -le 255 ] && [ ${4:-666} -le 254 ]
-}
 
 _islivecd()
 {   #detect a livecd system, return 0 on success, 1 otherwise
@@ -796,25 +827,6 @@ _lock()
 }
 #==================================================== Example ====
 #_lock $0
-#=================================================================
-
-_networkup()
-{   #check for internet connection, returns 0 on success, 1 otherwise
-    wget --tries=3 --timeout=5 http://www.google.com -O /tmp/index.google > /dev/null 2>&1
-
-    if [ -s /tmp/index.google ]; then
-        rm /tmp/index.google
-        return 0
-    else
-        rm /tmp/index.google
-        return 1
-    fi
-}
-#==================================================== Example ====
-#if ! _networkup; then
-    #echo "You must have an Internet connection to run this script" >&2
-    #exit 1
-#fi
 #=================================================================
 
 _notify()
@@ -991,7 +1003,7 @@ _strreplace()
 #echo $world #prints "world"
 #=================================================================
 
-_strtolower()
+_str2lower()
 {   #convert a string to lower string
     [ -z "$1" ] && return 1
     echo $@ | tr '[:upper:]' '[:lower:]'
@@ -1058,13 +1070,31 @@ _usage()
 #esac
 #=================================================================
 
-_xmessage()
-{
-    MESSAGE="$PROGNAME: $*"
-    echo "$MESSAGE" | fold -s -w ${COLUMNS:-80} >&2
-    if [ -n "$DISPLAY" ] && which xmessage > /dev/null 2>&1; then
-        echo "$MESSAGE" | fold -s -w ${COLUMNS:-80} | xmessage -center -file -
-    fi
+_validinterface()
+{   #return 0 if parameter is a valid network interface, 1 otherwise
+    [ -z "$1" ] && return 1
+    ip addr | grep -qs "$1" && return 0
+    return 1
+}
+#===================================================== Example ====
+#if ! _validinterface $interface
+    #echo "$(basename $0): not valid interface $interface"
+#fi
+#=================================================================
+
+_validip4()
+{   #return 0 if parameter is a valid ip4 address, non-zero otherwise
+    #https://groups.google.com/forum/#!original/comp.unix.shell/NDu-kAL5cHs/7Zpc6Q2Hu5YJ
+    case "$*" in
+        ""|*[!0-9.]*|*[!0-9]) return 1 ;;
+    esac
+
+    local IFS=.  ## local is bash-specific
+    set -- $*
+
+    [ $# -eq 4 ] &&
+        [ ${1:-666} -le 255 ] && [ ${2:-666} -le 255 ] &&
+        [ ${3:-666} -le 255 ] && [ ${4:-666} -le 254 ]
 }
 
 _waitfor()
@@ -1122,4 +1152,16 @@ _waitfor()
 }
 #==================================================== Example ====
 #_waitfor tar -jxpf file.tar.bz2
+#=================================================================
+
+_xmessage()
+{   #prints a message using xmessage || gxmessage
+    MESSAGE="$PROGNAME: $*"
+    echo "$MESSAGE" | fold -s -w ${COLUMNS:-80} >&2
+    if [ -n "$DISPLAY" ] && which xmessage > /dev/null 2>&1; then
+        echo "$MESSAGE" | fold -s -w ${COLUMNS:-80} | xmessage -center -file -
+    fi
+}
+#==================================================== Example ====
+#_xmessage "Notice ..."
 #=================================================================
