lib: new functions, _addcron, xmessage

diff --git a/sh/lib b/sh/lib
--- a/sh/lib
+++ b/sh/lib
@@ -11,6 +11,12 @@
 #[+] must not print errors
 #[+] must provide an example
 
+_addcron()
+{
+    [ -z "$1" ] && return 1
+    crontab -l | { cat; echo "$@"; } | crontab -
+}
+
 _animbarcui()
 {   #prints a bar of o@o moving
     [ -z "$1" ] && { printf "%4s\n" ""; return 1; }
@@ -263,14 +269,14 @@ string=$(_decode64 $string)
 #=================================================================
 
 _cmdsudo()
-{   #print current command, exits on fail
+{   #print && execute a command, exits if command fails
     [ -z "$1" ] && return 0
 
     echo "    $ sudo $@"
-    echo "$sudopwd" | $sudocmd "$@"
+    echo "$sudopwd" | $sudocmd "$@" > /tmp/serr.out 2>&1
 
     status=$?
-    [ "$status" != 0 ] && exit $status || return
+    [ "$status" != 0 ] && { cat /tmp/serr.out; rm /tmp/serr.out; exit $status; } || return
 }
 #==================================================== Example ====
 #_cmdsudo rm /file
@@ -1051,6 +1057,15 @@ _usage()
   #-h | --help | h | help ) _usage;;
 #esac
 #=================================================================
+
+_xmessage()
+{
+    MESSAGE="$PROGNAME: $*"
+    echo "$MESSAGE" | fold -s -w ${COLUMNS:-80} >&2
+    if [ -n "$DISPLAY" ] && which xmessage > /dev/null 2>&1; then
+        echo "$MESSAGE" | fold -s -w ${COLUMNS:-80} | xmessage -center -file -
+    fi
+}
 
 _waitfor()
 {   #wait for a program, shows an animation
