add bin-dpkg-rdeps: deps in a debian/ubuntu way for binaries

diff --git a/sh/lib b/sh/lib
--- a/sh/lib
+++ b/sh/lib
@@ -2,10 +2,16 @@
 #functions, copy and paste them in your own scripts
 
 #https://github.com/chilicuil/learn/blob/master/sh/lib
-#if you have more please send your push request!
+#if you have more or can improve the current ones please send your push request!
+
+#new functions:
+#[+] must be self contained, with no dependencies on other functions
+#[+] they can depend on exotic cli commands thought
+#[+] they must follow the general style (name convention, return comment, indentation, etc)
+#[+] an example must be provided
 
 _arch()
-{
+{   #check for the system arch, returns [64|32]
     local arch
     [ -z $MACHTYPE ] && arch=$(uname -m) || arch=$(echo $MACHTYPE | cut -d- -f1)
 
@@ -20,13 +26,13 @@ _arch()
 
     echo $arch
 }
-#==================================================== Sample use =
+#==================================================== Example ====
 arch=$(_arch)
 echo $arch
-#==================================================== Sample use =
+#=================================================================
 
-_checkinternet()
-{   #returns 0 on success, 1 otherwise
+_internetlink()
+{   #check for internet connection, returns 0 on success, 1 otherwise
     wget --tries=3 --timeout=5 http://www.google.com -O /tmp/index.google > /dev/null 2>&1
 
     if [ -s /tmp/index.google ]; then
@@ -37,16 +43,15 @@ _checkinternet()
         return 1
     fi
 }
-#==================================================== Sample use =
-if ! _checkinternet; then
+#==================================================== Example ====
+if ! _internetlink; then
     echo "You must be connected to run this script" >&2
     exit 1
 fi
-#==================================================== Sample use =
+#=================================================================
 
 _cleanup()
-{
-    #clean tmp files, exit with no parameters
+{   #clean tmp files, exit with no parameters
     stty echo
     echo
     echo "[+] cleanup ..."
@@ -54,27 +59,25 @@ _cleanup()
 
     [ -z $1 ] && exit
 }
-#==================================================== Sample use =
+#==================================================== Example ====
 trap _cleanup SIGINT SIGTERM #trap ctrl-c
 _cleanup 1
-#==================================================== Sample use =
+#=================================================================
 
 _cmd()
-{
-    #prints current command, exits if fails
+{   #print current command, exits on fail
     echo "[+] $@"
     $@
 
     status=$?
     [ $status != 0 ] && exit $status || return
 }
-#===================================================== Sample use =
+#==================================================== Example ====
 _cmd rm file
-#===================================================== Sample use =
+#=================================================================
 
 _die()
-{
-    #prints a stacktrace, a msg and exits with 1
+{   #print a stacktrace with a msg, exits with 1
     local frame=0
     while caller $frame; do
         ((frame++));
@@ -83,28 +86,64 @@ _die()
     echo "$*"
     exit 1
 }
-#==================================================== Sample use =
-[ -z "$var" ] && _die "$errmsg"
-#==================================================== Sample use =
+#==================================================== Example ====
+[ -z "$var" ] && _die "error msg"
+#=================================================================
 
 _dirname()
-{
-    #returns dirnames, faster than basename
+{   #`basename` faster clone, return string on success, 1 on fail
 
     #http://www.linuxmisc.com/12-unix-web-servers/d31beb238f7b5a6b.htm
-    local dir="${1%${1##*/}}"
-    [ "${dir:=./}" != "/" ] && dir="${dir%?}"
-    echo "$dir"
+    if [ -z $1 ]; then
+        return 1;
+    else
+        local dir="${1%${1##*/}}"
+        [ "${dir:=./}" != "/" ] && dir="${dir%?}"
+        echo "$dir"
+    fi
 }
-#==================================================== Sample use =
-_dirname file
-#==================================================== Sample use =
+#==================================================== Example ====
+_dirname /path/file #returns file
+#=================================================================
+
+_download()
+{   #download files, return local location, 1 on fail
+    #requires, *liburi-perl*
+    local urll="$1"
+    local prot=$(echo "$urll" | cut -d: -f1)
+    if [ "$prot" == "magnet" ]; then
+        return 1 #not supported   
+    fi
+    local path=$( echo "$urll" | perl -MURI -le 'chomp($urll = <>); print URI->new($urll)->path' )
+    local fn=$(basename "$path")
+    local ext="${fn##*.}"    
+
+    if [ "$ext" == "torrent" ]; then
+        local file=$(aria2c -q --bt-stop-timeout=120 --seed-time=0 --follow-torrent=mem --on-bt-download-complete /bin/echo "$urll")
+        [ -z $file ] && return 1  
+        return ${file[2]}
+    fi
+
+    case "$ext" in
+        mp4|ogv|mpg|flv|avi|mkv|mov|wmv|webm|3gpp)
+            local file=$(aria2c -q --bt-stop-timeout=120 --seed-time=0 --follow-torrent=mem --on-download-complete /bin/echo "$urll")
+            [ -z $file ] && return 1  
+            return ${file[2]}         
+            ;;
+        *)
+            return 1
+            ;;
+    esac
+}
+#==================================================== Example ====
+FILE=$(_download $URL)
+[ "$FILE" -eq 1 ] && echo error || echo "done: $FILE"
+#=================================================================
 
 _fullpath()
-{
-    #returns full path of the argument, exits with no parameters
+{   #return full path of the argument, return string on success, 1 on fail
     if [ -z $1 ]; then
-        exit;
+        return 1;
     else
         if [ `expr substr ${1:-a} 1 2` != "/" ]; then
             full_file=`pwd`"/"$1
@@ -112,13 +151,12 @@ _fullpath()
     fi
     echo $full_file
 }
-#==================================================== Sample use =
-_fullpath file
-#==================================================== Sample use =
+#==================================================== Example ====
+_fullpath file #returns /path/file
+#=================================================================
 
 _getopt()
-{
-    #define vars for cli arguments
+{   #define vars for cli arguments
     var=""
     wantarg=0
     for (( i=1; i<=$#; i+=1 )); do
@@ -165,15 +203,14 @@ _getopt()
         fi
     done
 }
-#===================================================== Sample use =
+#==================================================== Example ====
 OIFS=$IFS; IFS=$(echo -e "\n"); _getopt $@; IFS=$OIFS
 #./getopts --foo=bar -v -n 10 blah -one='last arg' 
 echo -e " foo:\t$foo v:\t$v n:\t$n blah:\t$blah one:\t$one "
-#===================================================== Sample use =
+#=================================================================
 
 _getpasswd()
-{
-    #define vars with passwords
+{   #define vars with passwords
     if [ -n "$1" ]
     then
         local option=`tr '[:upper:]' '[:lower:]' <<< $1`
@@ -190,16 +227,15 @@ _getpasswd()
         echo
     fi
 }
-#==================================================== Sample use =
+#==================================================== Example ====
 _getpasswd
 echo $passwd
 _getpasswd config
 echo $configpasswd
-#==================================================== Sample use =
+#=================================================================
 
 _getroot()
-{
-    #gets sudo's password, define $sudopasswd and $sudocmd
+{   #get sudo's password, define $sudopasswd and $sudocmd
 
     local tmp_path="/tmp"; local sudotest; local insudoers;
 
@@ -242,21 +278,20 @@ _getroot()
         fi
     fi
 }
-#==================================================== Sample use =
+#==================================================== Example ====
 _getroot
 echo "$sudopwd" | $sudocmd rm file
-#==================================================== Sample use =
+#=================================================================
 
 _isalphanum()
-{
-  # validate arg: returns 0 if all upper+lower+digits, 1 otherwise
+{ #check for alphanum strings, return 0 if all upper+lower+digits, 1 otherwise
 
   # Remove all unacceptable chars
   compressed="$(echo $1 | sed -e 's/[^[:alnum:]]//g')"
 
   [ "$compressed" != "$input" ] && return 1 || return 0
 }
-#==================================================== Sample use =
+#==================================================== Example ====
 echo -n "Enter input: "
 read input
 if ! _isalphanum "$input" ; then
@@ -266,26 +301,24 @@ else
     echo "Input is valid."
 fi
 exit 0
-#==================================================== Sample use =
+#=================================================================
 
 _islivecd()
-{
+{   #detect a livecd system, return 0 on success, 1 otherwise
     grep -qs boot=live /proc/cmdline && return 0
     grep -qs boot=casper /proc/cmdline && return 0
     return 1
 }
-#==================================================== Sample use =
+#==================================================== Example ====
 if ! _islivecd ; then
     echo "Live cd detected"
 else
     echo "Non LiveCd detected"
 fi
-exit 0
+#=================================================================
 
-#==================================================== Sample use =
 _inarray ()
-{
-    #checks if a value exists in an array, returns 0 on success, 1 otherwise
+{   #look for a value in an array, returns 0 on success, 1 otherwise
     [ -n "$1" ] || { echo "$FUNCNAME: requires at least 1 param"; exit 1; }
 
     local needle="$1" element
@@ -296,15 +329,15 @@ _inarray ()
     done
     return 1
 }
-#==================================================== Sample use =
+#==================================================== Example ====
 _inarray $name ${names[@]} && echo found!
-#==================================================== Sample use =
+#=================================================================
 
 _isnum()
-{   #returns 0 on success, 1 otherwise
+{   #look for a number, returns 0 on success, 1 otherwise
     echo "$@" | grep -q -v "[^0-9]"
 }
-#==================================================== Sample use =
+#==================================================== Example ====
 echo -n "Enter input: "
 read input
 if ! _isnum "$input" ; then
@@ -314,20 +347,47 @@ else
     echo "Input is valid."
 fi
 exit 0
-#==================================================== Sample use =
+#=================================================================
 
 _lower()
-{
-    #returns lower string
+{   #convert a string to lower string
     echo $@ | tr '[:upper:]' '[:lower:]' 
 }
-#==================================================== Sample use =
+#==================================================== Example ====
 string="FOO BAR"
-_upper $string
-#==================================================== Sample use =
+lower=$(_lower $string)
+#=================================================================
+
+_mail()
+{   #send mail, return 0 on success, 1 otherwise
+    #requires: *libio-socket-ssl-perl* and *libnet-ssleay-perl* on ubuntu for gmail
+    case $1 in
+        gmail)
+            sendemail -f "$1" -t "$2" -u "$3" -m "$4" -s smtp.gmail.com:587 -o tls=yes -xu "$5" -xp "$6" > /dev/null 2>&1
+            ;;
+        *)
+            sendemail -f "$1" -t "$2" -u "$3" -m "$4" -s "$5" -xu "$6" -xp "$7" > /dev/null 2>&1
+            ;;
+    esac
+
+    if [ $? -eq 0 ]; then
+        return 0
+    else
+        return 1
+    fi
+}
+#==================================================== Example ====
+FROM="foo@gmail.com"; TO="bar@foo.com"; TITLE="hi"; MSG="how are you?"
+USER="foo"; PASSWD="secret"
+[ $(_mail gmail $FROM $TO $TITLE $MESSAGE $USER $PASSWD) -eq 0 ] && echo "send" || echo "error"
+
+FROM="foo@custom.com"; TO="bar@foo.com"; TITLE="hi"; MSG="how are you?"
+SERVER="smpt.custom.com:port"; USER="foo"; PASSWD="secret"
+[ $(_mail $FROM $TO $TITLE $MESSAGE $SERVER $USER $PASSWD) -eq 0 ] && echo "send" || echo "error"
+#=================================================================
 
 _notify()
-{
+{   #notify a msg
     if [[ $TERM == "linux" ]] || [[ $TERM == "dumb" ]]; then
         notify-send -t 3000 "${@}"
     else
@@ -340,12 +400,44 @@ _notify()
         done
     fi
 }
-#==================================================== Sample use =
+#==================================================== Example ====
 _notify "You need html2text" "\$ sudo apt-get install html2text"
-#==================================================== Sample use =
+#=================================================================
+
+_printtime()
+{  #format seconds to a pretty string
+    NUM=$1
+    MIN=0
+    HOUR=0
+    DAY=0
+    if((NUM>59));then
+        ((SEC=NUM%60))
+        ((NUM=NUM/60))
+        if((NUM>59));then
+            ((MIN=NUM%60))
+            ((NUM=NUM/60))
+            if((NUM>23));then
+                ((HOUR=NUM%24))
+                ((DAY=NUM/24))
+            else
+                ((HOUR=NUM))
+            fi
+        else
+            ((MIN=NUM))
+        fi
+    else
+        ((SEC=NUM))
+    fi
+    echo "$DAY"d "$HOUR"h "$MIN"m "$SEC"s
+}
+#==================================================== Example ====
+SECONDS=12345
+_printtime $SECONDS #prints "0d 3h 25m 49s"
+#=================================================================
 
 _realpath()
-{
+{   #convert relative to real paths
+
     #http://www.makkintosshu.com/journal/a-realpath-implementation-in-bash
     local success=true
 
@@ -386,7 +478,7 @@ _realpath()
 
     $success
 }
-#==================================================== Sample use =
+#==================================================== Example ====
 relative_path="../Shared/"
 absolute_path="$(_realpath "$relative_path")"
 if [ $? -eq 0 ]; then
@@ -394,11 +486,32 @@ if [ $? -eq 0 ]; then
 else
 	echo "'$relative_path' does not exist!"
 fi
-#==================================================== Sample use =
+#=================================================================
+
+_refarray()
+{   #exports an array to another
+    #http://ihaveabackup.net/2012/01/29/a-workaround-for-passing-arrays-in-bash/
+    local varname="$1"
+    local export_as="$2"
+    local code=$(declare -p "$varname")
+    echo ${code/$varname/$export_as}
+}
+#==================================================== Example ====
+dump() {
+    eval $(ref_array "$1" array)
+    local key
+
+    for key in "${!array[@]}"; do
+        printf "Key: %s, value: %s\n" "$key" "${array[$key]}"
+    done
+}
+
+declare -A PERSON=([name]="John Doe" [age]=22)
+dump PERSON
+#=================================================================
 
 _rotate()
-{
-    #shows an animation as long as a process is in memory
+{   #shows an animation as long as a process is in memory
     pid=$1
     animation_state=1
 
@@ -436,13 +549,12 @@ _rotate()
         sleep 1
     done
 }
-#==================================================== Sample use =
+#==================================================== Example ====
 _rotate $(pidof tar)
-#==================================================== Sample use =
+#=================================================================
 
 _uploadimg()
-{   
-    #returns url, 1 on error
+{   #uploads an image, returns url on success, 1 otherwise
     for img
     do
         if [ -f "$img" ] ; then
@@ -481,37 +593,35 @@ _uploadimg()
         fi
     done
 }
-#==================================================== Sample use =
-_upload_img "$@"
-#==================================================== Sample use =
+#==================================================== Example ====
+_upload_img file.png
+#=================================================================
 
 _upper()
-{
-    #returns upper string
+{   #returns upper string
     echo $@ | tr '[:lower:]' '[:upper:]'
 }
-#==================================================== Sample use =
+#==================================================== Example ====
 string="foo bar"
-_upper $string
-#==================================================== Sample use =
+upper=$(_upper $string)
+#=================================================================
 
 _usage()
-{
+{   #prints an usage msg and exits with 0
     echo "Usage: `basename $0` [OPTION] FILE"
     echo "  -a   description"
     echo "  -b   description" 
     echo "  -c   description" 
     exit 0
 }
-#===================================================== Sample use =
+#===================================================== Example ====
 case $1 in
   -h | --help | h | help ) _usage;;
 esac
-#===================================================== Sample use =
+#=================================================================
 
 _waitfor()
-{
-    #wait for a program, shows an animation
+{   #wait for a program, shows an animation
     status=$?
     [ $status != 0 ] && exit $status
 
@@ -526,12 +636,12 @@ _waitfor()
         echo -e "\b\b\b\b\b done"
     fi
 }
-#==================================================== Sample use =
+#==================================================== Example ====
 _waitfor tar -jxpf file.tar.bz2
-#==================================================== Sample use =
+#=================================================================
 
 _yesno()
-{
+{   #prints a yes/no dialog, returns 1 on yes, 0 otherwise
     [ -n "$1" ] || { echo "$FUNCNAME: requires a question"; exit 1; }
     [ -z "$2"    ] && echo -ne "$1 (y/n): "
     [ "$2" = yes ] && echo -ne "$1 (Y/n): "
@@ -547,8 +657,8 @@ _yesno()
         return 1
     fi
 }
-#==================================================== Sample use =
+#==================================================== Example ====
 _yesno "Do you want to continue?" #default to 'no'
 _yesno "Do you want to continue?" yes #default behavior
 _yesno "Do you want to continue?" no  #default behavior
-#==================================================== Sample use =
+#=================================================================
