apply guideline: https://github.com/chilicuil/learn/blob/master/sh/guideline.md, this was a huge commit

diff --git a/sh/is/apt-proxy b/sh/is/apt-proxy
--- a/sh/is/apt-proxy
+++ b/sh/is/apt-proxy
@@ -12,9 +12,9 @@ _header()
 
 _whereis()
 {
-    [ -z "$1" ] && return 1
-    [ -n "$2" ] && return 1
-    if ! command -v "$1" 2>/dev/null; then
+    [ -z "${1}" ] && return 1
+    [ -n "${2}" ] && return 1
+    if ! command -v "${1}" 2>/dev/null; then
         return 1
     fi
 }
@@ -25,38 +25,35 @@ _existaptproxy()
     return 1
 }
 
-_handscui()
-{   #waiting animation
-    [ -z "$1" ] && { printf "%5s\n" ""; return 1; }
-    pid="$1"
-    animation_state=1
+_animcui()
+{   #wait animation
+    [ -z "${1}" ] && { printf "%5s\n" ""; return 1; }
 
-    if [ ! "$(ps -p $pid -o comm=)" ]; then
+    if ! printf "%s" "$(pidof "${1}")" | grep "[0-9].*" >/dev/null; then
         printf "%5s\n" ""
-        return
+        return 1;
     fi
 
-    printf "%s" "      "
+    _animcui_var_animation_state="1"
 
-    while [ "`ps -p $pid -o comm=`" ]; do
+    if [ ! "$(ps -p "$(pidof "${1}")" -o comm= 2>/dev/null)" ]; then
+        printf "%5s\n" ""
+        return 1
+    fi
+
+    printf "%5s" ""
+
+    while [ "$(ps -p "$(pidof "${1}")" -o comm= 2>/dev/null)" ]; do
         printf "%b" "\b\b\b\b\b"
-        case $animation_state in
-            1)
-                printf "%s" '\o@o\'
-                animation_state=2
-                ;;
-            2)
-                printf "%s" '|o@o|'
-                animation_state=3
-                ;;
-            3)
-                printf "%s" '/o@o/'
-                animation_state=4
-                ;;
-            4)
-                printf "%s" '|o@o|'
-                animation_state=1
-                ;;
+        case "${_animcui_var_animation_state}" in
+            1) printf "%s" '\o@o\'
+               _animcui_var_animation_state="2" ;;
+            2) printf "%s" '|o@o|'
+               _animcui_var_animation_state="3" ;;
+            3) printf "%s" '/o@o/'
+               _animcui_var_animation_state="4" ;;
+            4) printf "%s" '|o@o|'
+               _animcui_var_animation_state="1" ;;
         esac
         sleep 1
     done
@@ -64,77 +61,107 @@ _handscui()
 }
 
 _getroot()
-{   #get sudo's password, define $sudopasswd and $sudocmd
-
-    local tmp_path="/tmp"; local sudotest; local insudoers;
-
-    if [ ! X"$LOGNAME" = X"root" ]; then
-        printf "%s\\n" "Detecting user $LOGNAME (non-root) ..."
+{   #get sudo's password, define $sudopwd and $sudocmd
+    if [ ! X"${LOGNAME}" = X"root" ]; then
+        printf "%s\\n" "Detecting user ${LOGNAME} (non-root) ..."
         printf "%s\\n" "Checking if sudo is available ..."
-        sudotest=`type sudo >/dev/null 2>/dev/null; printf "%s\\n" "$?"`
 
-        if [ X"$sudotest" = X"0" ]; then
+        if command -v "sudo" >/dev/null 2>&1; then
             sudo -K
-            if [ -e "$tmp_path/sudo.test" ]; then
-                rm -f "$tmp_path/sudo.test"
+
+            if [ -n "${sudopwd}" ]; then
+                # password check
+                _getroot_var_test="$(printf "%s\\n" "${sudopwd}" | sudo -S ls 2>&1)"
+                _getroot_var_status="${?}"
+                _getroot_var_not_allowed="$(printf "%s" "${_getroot_var_test}" | \
+                                         grep -i "sudoers")"
+
+                if [ -n "${_getroot_var_not_allowed}" ]; then
+                    printf "%s %s\\n" "You're not allowed to use sudo," \
+                    "get in contact with your local administrator"
+                    exit
+                fi
+
+                if [ X"${_getroot_var_status}" != X"0" ]; then
+                    sudopwd=""
+                    printf "%s\\n" "Incorrect preseed password"
+                    exit
+                else
+                    sudocmd="sudo -S"
+                fi
+                printf "%s\\n" "    - all set ..."
+                return
             fi
-            while [ -z "$sudopwd" ]; do
-                printf "%s" "   - enter sudo-password: "
+
+            i=0 ; while [ "${i}" -lt "3" ]; do
+                i="$(expr ${i} + 1)"
+                printf "%s" "   - enter sudo password: "
                 stty -echo
                 read sudopwd
                 stty echo
 
                 # password check
-                printf "%s\\n" "$sudopwd" | sudo -S touch "$tmp_path/sudo.test" > "$tmp_path/sudo.output" 2>&1
-                insudoers=$(grep -i "sudoers" "$tmp_path/sudo.output")
-                if [ -n "$insudoers" ]; then
-                    printf "%s\\n" "$sudopwd" | sudo -S rm "$tmp_path/sudo.output" > /dev/null 2>&1
+                _getroot_var_test="$(printf "%s\\n" "${sudopwd}" | sudo -S ls 2>&1)"
+                _getroot_var_status="${?}"
+                _getroot_var_not_allowed="$(printf "%s" "${_getroot_var_test}" | \
+                                         grep -i "sudoers")"
+
+                if [ -n "${_getroot_var_not_allowed}" ]; then
+                    printf "\\n%s %s\\n" "You're not allowed to use sudo," \
+                    "get in contact with your local administrator"
                     exit
                 fi
 
-                if [ ! -e "$tmp_path/sudo.test" ]; then
+                printf "\\n"
+                if [ X"${_getroot_var_status}" != X"0" ]; then
                     sudopwd=""
+                else
+                    sudocmd="sudo -S"
+                    break
                 fi
             done
 
-            sudocmd="/usr/bin/sudo -S"
-
-            printf "%s\\n" "$sudopwd" | $sudocmd rm -f "$tmp_path/sudo.test" > /dev/null 2>&1
-            printf "\\n"
+            if [ -z "${sudopwd}" ]; then
+                printf "%s\\n" "Failed authentication"
+                exit
+            fi
         else
-            printf "%s\\n" "You're not root and sudo isn't available. Please run this script as root!"
+            printf "%s %s\\n" "You're not root and sudo isn't available." \
+            "Please run this script as root!"
             exit
         fi
     fi
 }
 
 _cmdsudo()
-{   #print && execute a command, exits if command fails
-    [ -z "$1" ] && return 1
-    _cmdsudo_var_serr=$$
+{   #print && execute a command, exit on fail
+    [ -z "${1}" ] && return 1
 
-    printf "%s " "    $ $@"
-    printf "\\n"
-    printf "%s\\n" "$sudopwd" | $sudocmd eval "$@" > /tmp/"$_cmdsudo_var_serr".out 2>&1
+    printf "%s \\n" "    $ sudo ${*}"
+    _cmdsudo_var_output="$(printf "%s\\n" "${sudopwd}" | ${sudocmd} sh -c "eval ${*}" 2>&1)"
+    _cmdsudo_var_status="${?}"
 
-    _cmdsudo_var_status=$?
-    [ X"$_cmdsudo_var_status" != X"0" ] && { cat /tmp/"$_cmdsudo_var_serr".out; \
-        rm -rf /tmp/"$_cmdsudo_var_serr".out; exit $_cmdsudo_var_status; } \
-        || { rm -rf /tmp/"$_cmdsudo_var_serr".out; return $_cmdsudo_var_status; }
+    if [ X"${_cmdsudo_var_status}" != X"0" ]; then
+        printf "> %s:%s\\n" "${*}" "${_cmdsudo_var_output}"
+        printf "\\n"
+        exit "${_cmdsudo_var_status}"
+    else
+        return "${_cmdsudo_var_status}";
+    fi
 }
 
 _waitforsudo()
-{
-    [ -z "$1" ] && return 1
+{   #print, execute and wait for a command to finish
+    [ -z "${1}" ] && return 1
 
-    printf "%s " "    $ sudo $@..."
-    printf "%s\\n" "$sudopwd" | $sudocmd $@ > /dev/null 2>&1 &
+    printf "%s " "    $ sudo ${@} ..."
+    printf "%s\\n" "${sudopwd}" | ${sudocmd} sh -c "eval ${*}" >/dev/null 2>&1 &
     sleep 1s
 
-    if [ "$1" = DEBIAN_FRONTEND=noninteractive ]; then
-        _handscui $(pidof $2)
+    if [ X"${1}" = X"DEBIAN_FRONTEND=noninteractive" ]; then
+        _animcui "${2}"
     else
-        _handscui $(pidof $1)
+        _animcui "${1}"
     fi
 }
 
@@ -149,17 +176,17 @@ if ! _whereis avahi-browse >/dev/null; then
 fi
 
 if _existaptproxy; then
-    apt_proxy_server=$(avahi-browse -a -t -r -p | grep apt-cacher-ng | grep = | cut -d";" -f8)
-    printf "%s\\n" "[+] exists an apt-get proxy in the network at $apt_proxy_server, using it ..."
+    apt_proxy_server="$(avahi-browse -a -t -r -p | grep apt-cacher-ng | grep = | cut -d";" -f8)"
+    printf "%s\\n" "[+] exists an apt-get proxy in the network at ${apt_proxy_server}, using it ..."
     [ ! -f /usr/share/squid-deb-proxy-client/apt-avahi-discover ] && _waitforsudo apt-get install --no-install-recommends -y squid-deb-proxy-client
 else
     printf "%s\\n" "[+] no apt-get proxy found, installing one locally ..."
     _waitforsudo apt-get install --no-install-recommends -y squid-deb-proxy-client apt-cacher-ng
     [ ! -f /etc/avahi/services/apt-cacher-ng.service ] && _waitforsudo wget http://javier.io/mirror/apt-cacher-ng.service -O /etc/avahi/services/apt-cacher-ng.service
-    if [ -d "$HOME"/misc/ubuntu/proxy/apt-cacher-ng/ ]; then
+    if [ -d "${HOME}"/misc/ubuntu/proxy/apt-cacher-ng/ ]; then
         printf "%s\\n" "[+] exporting files ..."
         _cmdsudo rm -rf /var/cache/apt-cacher-ng
-        _cmdsudo ln -s "$HOME"/misc/ubuntu/proxy/apt-cacher-ng/ /var/cache/apt-cacher-ng
+        _cmdsudo ln -s "${HOME}"/misc/ubuntu/proxy/apt-cacher-ng/ /var/cache/apt-cacher-ng
     fi
 fi
 
diff --git a/sh/is/fix b/sh/is/fix
--- a/sh/is/fix
+++ b/sh/is/fix
@@ -5,9 +5,9 @@
 #===================================================
 
 #Don't forget update this when adding new functions
-usage()
+_usage()
 {
-    printf "%s\\n" "Usage: `expr "$0" : '.*/\([^/]*\)'` module"
+    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') module"
     printf "%s\\n"
     printf "%s\\n" "  apache            Moves /etc/init.d/apache2.1 to apache2"
     printf "%s\\n" "  ipw2200           Restart the ipw2200 module"
@@ -21,14 +21,13 @@ usage()
 
 _exec()
 {
-    status=$?
-    if [ "$status" != 0 ]; then
-        exit $status
+    status="${?}"
+    if [ X"${status}" != X"0" ]; then
+        exit "${status}"
     fi
-    printf "%s\\n" "[+] $@"
-    $@
+    printf "%s\\n" "[+] ${@}"
+    ${@}
 }
-
 
 _apache ()
 {
@@ -72,34 +71,17 @@ _webcam()
     _exec sudo chmod o+rw /dev/video0
 }
 
-if [ "$#" != 0 ]; then
-    case $1 in
-        apache)
-        _apache
-        ;;
-        ipw2200)
-        _ipw2200
-        ;;
-        wl)
-        _wl
-        ;;
-        iwlagn)
-        _iwlagn
-        ;;
-        mpd)
-        _mpd
-        ;;
-        webcam)
-        _webcam
-        ;;
-        -h | --help)
-        usage
-        ;;
-        *)
-        printf "%s\\n" "Error, unknown option: $1"
-        usage
-        ;;
+if [ X"${#}" != X"0" ]; then
+    case "${1}" in
+        apache)    _apache  ;;
+        ipw2200)   _ipw2200 ;;
+        wl)        _wl      ;;
+        iwlagn)    _iwlagn  ;;
+        mpd)       _mpd     ;;
+        webcam)    _webcam  ;;
+        -h|--help) _usage   ;;
+        *)         printf "%s\\n" "Error, unknown option: ${1}"; usage ;;
     esac
 else
-    usage
+    _usage
 fi
diff --git a/sh/is/share-backups b/sh/is/share-backups
--- a/sh/is/share-backups
+++ b/sh/is/share-backups
@@ -1,45 +1,50 @@
 #! /usr/bin/env sh
 
-PASSWD=$(date +%s | sha256sum | base64 | head -c 8)
+PASSWD="$(date +%s | sha256sum | base64 | head -c 8)"
 USER="guest"
 PORT="26769"
 BACKUP_DIR="/path/backup"
 CERT="/path/server.pem"
 
-if [ "$1" = stop ] ; then
-    ID=$(ps aux | grep [s]imple | awk '{ print $2 }')
-    [ -n "$ID" ] && { kill -9 $ID; printf "%s\\n" "Stopped"; } || printf "%s\\n" "No instance found"
+if [ X"$1" = X"stop" ]; then
+    ID="$(ps aux | grep [s]imple | awk '{ print $2 }')"
+    [ -n "$ID" ] && { kill -9 "${ID}"; printf "%s\\n" "Stopped"; } || printf "%s\\n" "No instance found"
     exit
 fi
 
 _basename()
 {
-    [ -z "$1" ] && return 0
-    expr "$1" : '.*/\([^/]*\)'
+    [ -z "${1}" ] && return 1
+    case "${1}" in
+        /*|*/*) expr "${1}" : '.*/\([^/]*\)' ;;
+        *) printf "%s\\n" "${1}";;
+    esac
 }
 
-exec 9> /tmp/$(_basename $0).lock #verify only one instance is running
-if ! flock -n 9  ; then                #http://mywiki.wooledge.org/BashFAQ/045
-    printf "%s\\n" "$(_basename $0): another instance is running";
+exec 9> /tmp/$(_basename ${0}).lock #verify only one instance is running
+if ! flock -n 9; then               #http://mywiki.wooledge.org/BashFAQ/045
+    printf "%s\\n" "$(_basename ${0}): another instance is running";
     exit 1
 fi
 
-[ -f "$CERT" ] && SSL_OPTS="--ssl --certificate=$CERT"
+[ -f "${CERT}" ] && SSL_OPTS="--ssl --certificate=${CERT}"
 
-if [ -f /usr/local/bin/simple-httpd ] ; then
+#TODO 29-03-2014 18:09 >> remote fixed path
+if [ -f /usr/local/bin/simple-httpd ]; then
     printf "%s\\n" "Starting simple.server..."
-    printf "%s\\n" "  address: all interfaces"
-    printf "%s\\n" "  port: $PORT"
-    printf "%s\\n" "  authentication"
-    printf "%s\\n" "    username: $USER"
-    printf "%s\\n" "    password: $PASSWD"
-    printf "%s\\n" "    ssl: $SSL_OPTS"
+    printf "%s\\n" "  address   : all interfaces"
+    printf "%s\\n" "  port      : ${PORT}"
+    printf "%s\\n"
+    printf "%s\\n" "  username: ${USER}"
+    printf "%s\\n" "  password: ${PASSWD}"
+    printf "%s\\n" "  ssl     : ${SSL_OPTS}"
     printf "%s\\n" "  serving:"
-    printf "%s\\n" "    $BACKUP_DIR"
+    printf "%s\\n" "    ${BACKUP_DIR}"
 
-    printf "%s\\n" "Run: $(_basename $0) stop, to stop sharing"
-    nohup simple-httpd -p $PORT --username=$USER --password=$PASSWD $SSL_OPTS $BACKUP_DIR &
+    printf "%s\\n" "Run: $(_basename ${0}) stop, to stop sharing"
+    nohup simple-httpd -p "${PORT}" --username="${USER}" --password="${PASSWD}" "${SSL_OPTS}" "${BACKUP_DIR}" &
 else
-    printf "%s\\n" "No /usr/local/bin/simple-httpd found, download it at: https://raw.github.com/chilicuil/learn/master/python/simple-httpd"
+    printf "%s\\n" "Error: simple-httpd was not found!"
+    printf "%s\\n" "Info : download it at: https://raw.github.com/chilicuil/learn/master/python/simple-httpd"
     exit 1
 fi
diff --git a/sh/tools/compress b/sh/tools/compress
--- a/sh/tools/compress
+++ b/sh/tools/compress
@@ -9,225 +9,218 @@
 
 _basename()
 {
-    [ -z "$1" ] && return 1
-    case $1 in
-        /*|*/*) expr "$1" : '.*/\([^/]*\)' ;;
-        *) printf "%s\\n" "$1";;
+    [ -z "${1}" ] && return 1
+    case "${1}" in
+        /*|*/*) expr "${1}" : '.*/\([^/]*\)' ;;
+        *) printf "%s\\n" "${1}";;
     esac
 }
 
 _usage()
 {
-    printf "%s\\n" "Usage: `_basename $0` [-s] FILES ... FILE.[tar.gz,tar.bz2,zip...]"
+    printf "%s\\n" "Usage: $(_basename ${0}) [-s] FILES ... FILE.[tar.gz,tar.bz2,zip...]"
     printf "%s\\n" "           -s       quiet mode"
     exit 0
 }
 
-[ "$#" -lt 2 ] && _usage
+[ "${#}" -lt "2" ] && _usage
 
 _compress()
 {
     i=0
     for COMPRESS_FILE; do :; done
     for FILE; do
-        i=$(expr $i + 1);
-        [ "$#" -eq $i ] && continue
-        [ ! -r "$FILE" ] && { printf "%s\\n" "$(_basename $0): "$FILE" does not exist or is not readable"; exit 1; }
-        FILES="$FILE""|""$FILES"
+        i="$(expr "${i}" + 1)"
+        [ "${#}" -eq "${i}" ] && continue
+        [ ! -r "${FILE}" ] && { printf "%s\\n" "$(_basename ${0}): ${FILE} does not exist or is not readable"; exit 1; }
+        FILES="${FILE}""|""${FILES}"
     done
 
-    FILES_FORMAT="$(printf "%s" "$FILES" | sed 's:|: :g')"
-    OLDIFS="$IFS"
+    FILES_FORMAT="$(printf "%s" "${FILES}" | sed 's:|: :g')"
+    OLDIFS="${IFS}"
     IFS="|"
 
-    if [ -z "$SFLAG" ]; then
-        case "$COMPRESS_FILE" in
+    if [ -z "${SFLAG}" ]; then
+        case "${COMPRESS_FILE}" in
             #TODO 15-02-2014 01:02 >> add _exec function which prints and executes current command
             *.deb|*.udeb)
-                printf "%s " "[+] ar rv $COMPRESS_FILE $FILES_FORMAT"
+                printf "%s " "[+] ar rv ${COMPRESS_FILE} ${FILES_FORMAT}"
                 printf "\\n"
-                ar rv "$COMPRESS_FILE" $FILES
+                ar rv "${COMPRESS_FILE}" ${FILES}
                 ;;
             *.tar.bz2|*.tbz|*.tbz2)
-                printf "%s " "[+] tar cvf - $FILES_FORMAT | bzip2 > $COMPRESS_FILE"
+                printf "%s " "[+] tar cvf - ${FILES_FORMAT} | bzip2 > ${COMPRESS_FILE}"
                 printf "\\n"
-                tar cvf - $FILES | bzip2 > "$COMPRESS_FILE"
+                tar cvf - ${FILES} | bzip2 > "${COMPRESS_FILE}"
                 ;;
             *.tar.gz|*.tgz)
-                printf "%s " "[+] tar cvf - $FILES_FORMAT | gzip > $COMPRESS_FILE"
+                printf "%s " "[+] tar cvf - ${FILES_FORMAT} | gzip > ${COMPRESS_FILE}"
                 printf "\\n"
-                tar cvf - $FILES | gzip > "$COMPRESS_FILE"
+                tar cvf - ${FILES} | gzip > "${COMPRESS_FILE}"
                 ;;
             *.bz2)
-                local x=0
-                for FILE in $FILES; do
-                    x=$(expr $x + 1)
+                x="0"
+                for FILE in ${FILES}; do
+                    x="$(expr "${x}" + 1)"
                 done
-                [ $x -gt 1 ] && { printf "%s\\n" "$(_basename $0): bz2 files can only be compressed one by one, use tar.bz2 if you require to compress several files at the same time"; exit 1; }
+                [ "${x}" -gt "1" ] && { printf "%s\\n" "$(_basename ${0}): bz2 files can only be compressed one by one, use tar.bz2 if you require to compress several files at the same time"; exit 1; }
                 true
-                printf "%s " "[+] bzip2 -cv $FILES_FORMAT | dd of=$COMPRESS_FILE"
+                printf "%s " "[+] bzip2 -cv ${FILES_FORMAT} | dd of=${COMPRESS_FILE}"
                 printf "\\n"
-                bzip2 -cv $FILES | dd of="$COMPRESS_FILE"
+                bzip2 -cv ${FILES} | dd of="${COMPRESS_FILE}"
                 ;;
             *.rar)
-                printf "%s " "[+] rar a $COMPRESS_FILE $FILES_FORMAT"
+                printf "%s " "[+] rar a ${COMPRESS_FILE} ${FILES_FORMAT}"
                 printf "\\n"
-                rar a "$COMPRESS_FILE" $FILES
+                rar a "${COMPRESS_FILE}" ${FILES}
                 ;;
             *.gz)
-                local x=0
-                for FILE in $FILES; do
-                    x=$(expr $x + 1)
+                x="0"
+                for FILE in ${FILES}; do
+                    x="$(expr "${x}" + 1)"
                 done
-                [ $x -gt 1 ] && { printf "%s\\n" "$(_basename $0): gz files can only be compressed one by one, use tar.gz if you require to compress several files at the same time"; exit 1; }
+                [ "${x}" -gt "1" ] && { printf "%s\\n" "$(_basename ${0}): gz files can only be compressed one by one, use tar.gz if you require to compress several files at the same time"; exit 1; }
                 true
-                printf "%s " "[+] gzip -cv $FILES_FORMAT | dd of=$COMPRESS_FILE"
+                printf "%s " "[+] gzip -cv ${FILES_FORMAT} | dd of=${COMPRESS_FILE}"
                 printf "\\n"
-                gzip -cv $FILES | dd of="$COMPRESS_FILE"
+                gzip -cv ${FILES} | dd of="${COMPRESS_FILE}"
                 ;;
             *.tar)
-                printf "%s " "[+] tar cvf $COMPRESS_FILE $FILES_FORMAT"
+                printf "%s " "[+] tar cvf ${COMPRESS_FILE} ${FILES_FORMAT}"
                 printf "\\n"
-                tar cvf "$COMPRESS_FILE" $FILES
+                tar cvf "${COMPRESS_FILE}" ${FILES}
                 ;;
             *.zip|*.xpi)
-                printf "%s " "[+] zip -r $COMPRESS_FILE $FILES_FORMAT"
+                printf "%s " "[+] zip -r ${COMPRESS_FILE} ${FILES_FORMAT}"
                 printf "\\n"
-                zip -r "$COMPRESS_FILE" $FILES
+                zip -r "${COMPRESS_FILE}" ${FILES}
                 ;;
             *.7z)
-                printf "%s " "[+] 7z a $COMPRESS_FILE $FILES_FORMAT"
+                printf "%s " "[+] 7z a ${COMPRESS_FILE} ${FILES_FORMAT}"
                 printf "\\n"
-                7z a "$COMPRESS_FILE" $FILES
+                7z a "${COMPRESS_FILE}" ${FILES}
                 ;;
             *.tar.lzma)
-                printf "%s " "[+] tar cvf - $FILES_FORMAT | lzma > $COMPRESS_FILE"
+                printf "%s " "[+] tar cvf - ${FILES_FORMAT} | lzma > ${COMPRESS_FILE}"
                 printf "\\n"
-                tar cvf - $FILES | lzma > "$COMPRESS_FILE"
+                tar cvf - ${FILES} | lzma > "${COMPRESS_FILE}"
                 ;;
             *.tar.xz)
-                printf "%s " "[+] tar cvf - $FILES_FORMAT | xz > $COMPRESS_FILE"
+                printf "%s " "[+] tar cvf - ${FILES_FORMAT} | xz > ${COMPRESS_FILE}"
                 printf "\\n"
-                tar cvf - $FILES | xz > "$COMPRESS_FILE"
+                tar cvf - ${FILES} | xz > "${COMPRESS_FILE}"
                 ;;
             *.jar)
-                printf "%s " "[+] jar cvf $COMPRESS_FILE $FILES_FORMAT"
+                printf "%s " "[+] jar cvf ${COMPRESS_FILE} ${FILES_FORMAT}"
                 printf "\\n"
-                jar cvf "$COMPRESS_FILE" $FILES
+                jar cvf "${COMPRESS_FILE}" ${FILES}
                 ;;
             *.iso)
-                printf "%s " "[+] 7z a $COMPRESS_FILE $FILES_FORMAT"
+                printf "%s " "[+] 7z a ${COMPRESS_FILE} ${FILES_FORMAT}"
                 printf "\\n"
-                7z a "$COMPRESS_FILE" $FILES
+                7z a "${COMPRESS_FILE}" ${FILES}
                 ;;
             *)
-                printf "%s\\n" "'$COMPRESS_FILE' is not a valid compressed file"
+                printf "%s\\n" "'${COMPRESS_FILE}' is not a valid compressed file"
                 ;;
         esac
     else
-        case "$COMPRESS_FILE" in
+        case "${COMPRESS_FILE}" in
             *.deb|*.udeb)
-                printf "%s " "[+] ar r $COMPRESS_FILE $FILES_FORMAT"
+                printf "%s " "[+] ar r ${COMPRESS_FILE} ${FILES_FORMAT}"
                 printf "\\n"
-                ar r "$COMPRESS_FILE" $FILES
+                ar r "${COMPRESS_FILE}" ${FILES}
                 ;;
             *.tar.bz2|*.tbz|*.tbz2)
-                printf "%s " "[+] tar cf - $FILES_FORMAT | bzip2 > $COMPRESS_FILE"
+                printf "%s " "[+] tar cf - ${FILES_FORMAT} | bzip2 > ${COMPRESS_FILE}"
                 printf "\\n"
-                tar cf - $FILES | bzip2 > "$COMPRESS_FILE"
+                tar cf - ${FILES} | bzip2 > "${COMPRESS_FILE}"
                 ;;
             *.tar.gz|*.tgz)
-                printf "%s " "[+] tar cf - $FILES_FORMAT | gzip > $COMPRESS_FILE"
+                printf "%s " "[+] tar cf - ${FILES_FORMAT} | gzip > ${COMPRESS_FILE}"
                 printf "\\n"
-                tar cf - $FILES | gzip > "$COMPRESS_FILE"
-                _exec "tar cf - "$FILES" | gzip > "$COMPRESS_FILE""
+                tar cf - ${FILES} | gzip > "${COMPRESS_FILE}"
                 ;;
             *.bz2)
-                local x=0
-                for FILE in $FILES; do
-                    x=$(expr $x + 1)
+                x="0"
+                for FILE in ${FILES}; do
+                    x="$(expr "${x}" + 1)"
                 done
-                [ $x -gt 1 ] && { printf "%s\\n" "$(_basename $0): bz2 files can only be compressed one by one, use tar.bz2 if you require to compress several files at the same time"; exit 1; }
+                [ "${x}" -gt "1" ] && { printf "%s\\n" "$(_basename ${0}): bz2 files can only be compressed one by one, use tar.bz2 if you require to compress several files at the same time"; exit 1; }
                 true
-                printf "%s " "[+] bzip2 -c $FILES_FORMAT | dd of=$COMPRESS_FILE"
+                printf "%s " "[+] bzip2 -c ${FILES_FORMAT} | dd of=${COMPRESS_FILE}"
                 printf "\\n"
-                bzip2 -c $FILES | dd of="$COMPRESS_FILE"
+                bzip2 -c ${FILES} | dd of="${COMPRESS_FILE}"
                 ;;
             *.rar)
-                printf "%s " "[+] rar a $COMPRESS_FILE $FILES_FORMAT"
+                printf "%s " "[+] rar a ${COMPRESS_FILE} ${FILES_FORMAT}"
                 printf "\\n"
-                rar a "$COMPRESS_FILE" $FILES
+                rar a "${COMPRESS_FILE}" ${FILES}
                 ;;
             *.gz)
-                local x=0
-                for FILE in $FILES; do
-                    x=$(expr $x + 1)
+                x="0"
+                for FILE in ${FILES}; do
+                    x="$(expr "${x}" + 1)"
                 done
-                [ $x -gt 1 ] && { printf "%s\\n" "$(_basename $0): gz files can only be compressed one by one, use tar.gz if you require to compress several files at the same time"; exit 1; }
+                [ "${x}" -gt "1" ] && { printf "%s\\n" "$(_basename ${0}): gz files can only be compressed one by one, use tar.gz if you require to compress several files at the same time"; exit 1; }
                 true
-                printf "%s " "[+] gzip -c $FILES_FORMAT | dd of=$COMPRESS_FILE"
+                printf "%s " "[+] gzip -c ${FILES_FORMAT} | dd of=${COMPRESS_FILE}"
                 printf "\\n"
-                gzip -c $FILES | dd of="$COMPRESS_FILE"
+                gzip -c ${FILES} | dd of="${COMPRESS_FILE}"
                 ;;
             *.tar)
-                printf "%s " "[+] tar cf $COMPRESS_FILE $FILES_FORMAT"
+                printf "%s " "[+] tar cf ${COMPRESS_FILE} ${FILES_FORMAT}"
                 printf "\\n"
-                tar cf "$COMPRESS_FILE" $FILES
+                tar cf "${COMPRESS_FILE}" ${FILES}
                 ;;
             *.zip|*.xpi)
-                printf "%s " "[+] zip -r $COMPRESS_FILE $FILES_FORMAT"
+                printf "%s " "[+] zip -r ${COMPRESS_FILE} ${FILES_FORMAT}"
                 printf "\\n"
-                zip -r "$COMPRESS_FILE" $FILES
+                zip -r "${COMPRESS_FILE}" ${FILES}
                 ;;
             *.7z)
-                printf "%s " "[+] 7z a $COMPRESS_FILE $FILES_FORMAT"
+                printf "%s " "[+] 7z a ${COMPRESS_FILE} ${FILES_FORMAT}"
                 printf "\\n"
-                7z a "$COMPRESS_FILE" $FILES
+                7z a "${COMPRESS_FILE}" ${FILES}
                 ;;
             *.tar.lzma)
-                printf "%s " "[+] tar cf - $FILES_FORMAT | lzma > $COMPRESS_FILE"
+                printf "%s " "[+] tar cf - ${FILES_FORMAT} | lzma > ${COMPRESS_FILE}"
                 printf "\\n"
-                tar cf - $FILES | lzma > "$COMPRESS_FILE"
+                tar cf - ${FILES} | lzma > "${COMPRESS_FILE}"
                 ;;
             *.tar.xz)
-                printf "%s " "[+] tar cf - $FILES_FORMAT | xz > $COMPRESS_FILE"
+                printf "%s " "[+] tar cf - ${FILES_FORMAT} | xz > ${COMPRESS_FILE}"
                 printf "\\n"
-                tar cf - $FILES | xz > "$COMPRESS_FILE"
+                tar cf - ${FILES} | xz > "${COMPRESS_FILE}"
                 ;;
             *.jar)
-                printf "%s " "[+] jar cf $COMPRESS_FILE $FILES_FORMAT"
+                printf "%s " "[+] jar cf ${COMPRESS_FILE} ${FILES_FORMAT}"
                 printf "\\n"
-                jar cf "$COMPRESS_FILE" $FILES
+                jar cf "${COMPRESS_FILE}" ${FILES}
                 ;;
             *.iso)
-                printf "%s " "[+] 7z a $COMPRESS_FILE $FILES_FORMAT"
+                printf "%s " "[+] 7z a ${COMPRESS_FILE} ${FILES_FORMAT}"
                 printf "\\n"
-                7z a "$COMPRESS_FILE" $FILES
+                7z a "${COMPRESS_FILE}" ${FILES}
                 ;;
             *)
-                printf "%s\\n" "'$COMPRESS_FILE' is not a valid compressed file"
+                printf "%s\\n" "'${COMPRESS_FILE}' is not a valid compressed file"
                 ;;
         esac
     fi
-    IFS="$OLDIFS"
+    IFS="${OLDIFS}"
 }
 
 while getopts ":s:" option; do
-    case $option in
-        s)
-          SFLAG=yes
-          shift 1; _compress "$@"
-          exit 0
-          ;;
-        :)
-          printf "%s\\n" "Option -$OPTARG requires an argument"
-          _usage
-          ;;
-        \?)
-          printf "%s\\n" "Invalid option: -$OPTARG"
-          _usage
-          ;;
+    case "${option}" in
+        s) SFLAG="yes"
+           shift 1; _compress "${@}"
+           exit 0 ;;
+        :) printf "%s\\n" "Option -${OPTARG} requires an argument"
+           _usage ;;
+        \?) printf "%s\\n" "Invalid option: -${OPTARG}"
+           _usage ;;
     esac
 done
 
-_compress "$@"
+_compress "${@}"
diff --git a/sh/tools/mkpass b/sh/tools/mkpass
--- a/sh/tools/mkpass
+++ b/sh/tools/mkpass
@@ -2,20 +2,20 @@
 #description: create a secure password with 8 chars by default
 #usage: mkpass [LENGTH]
 
-if [ ! "$1" ]; then
-    mkpasswd_length=8
+if [ ! "${1}" ]; then
+    mkpasswd_length="8"
 else
     #isnum?
     #http://stackoverflow.com/questions/806906/how-do-i-test-if-a-variable-is-a-number-in-bash
-    case $1 in
-        ''|*[!0-9]*) printf "%s\\n" "Error, not a number: $1"; exit 1;;
-        *) mkpasswd_length=$1;;
+    case "${1}" in
+        ''|*[!0-9]*) printf "%s\\n" "Error, not a number: ${1}"; exit 1;;
+        *) mkpasswd_length="${1}";;
     esac
 fi
 
 if command -v "xclip" >/dev/null 2>/dev/null; then
     #http://unix.stackexchange.com/questions/28503/how-can-i-send-stdout-to-multiple-commands
-    strings /dev/urandom | grep -o '[[:alnum:]]' | head -n $mkpasswd_length | tr -d '\n' | tee /dev/fd/2 | xclip; printf "\\n"
+    strings /dev/urandom | grep -o '[[:alnum:]]' | head -n "${mkpasswd_length}" | tr -d '\n' | tee /dev/fd/2 | xclip; printf "\\n"
 else
-    strings /dev/urandom | grep -o '[[:alnum:]]' | head -n $mkpasswd_length | tr -d '\n'; printf "\\n"
+    strings /dev/urandom | grep -o '[[:alnum:]]' | head -n "${mkpasswd_length}" | tr -d '\n'; printf "\\n"
 fi
diff --git a/sh/tools/movietime b/sh/tools/movietime
--- a/sh/tools/movietime
+++ b/sh/tools/movietime
@@ -17,160 +17,154 @@ _usage()
 {
     # Help message.
     printf "\\n"
-    printf "%s\\n" "   $prog disables screen blanking and screensaver to allow viewing a video.  Running the program again will enable them.  If the 'resumetime' variable is set after that time $prog will resume normal powersaving values." | fmt -c -w 76
+    printf "%s\\n" "   ${prog} disables screen blanking and screensaver to allow viewing a video.  Running the program again will enable them.  If the 'resumetime' variable is set after that time ${prog} will resume normal powersaving values." | fmt -c -w 76
     printf "\\n"
 
     # Display current values of power management and movietime.
-    suspinhtest=$(ps aux | grep -v grep | grep $suspinhscript)
-    suspinhval=$([ -n "$suspinhtest" ] && printf "%s\\n" "Disabled" || printf "%s\\n" "Desktop settings")
+        suspinhtest="$(pgrep -f "${suspinhscript}")"
+        suspinhval="$([ -n "${suspinhtest}" ] && printf "%s\\n" "Disabled" || printf "%s\\n" "Desktop settings")"
 
-    # DPMS disabled information
-    printf "%s\\n" "   ${txtbld}Current settings ${txtrst}(in minutes, 0 = disabled):"
-    if [ X"$dispdpms" = X"Disabled" ]; then
-      printf "%s\\n" "   DPMS:         $dispdpms"
-      printf "%s\\n" "   Suspend:      $suspinhval"
+        # DPMS disabled information
+        printf "%s\\n" "   ${txtbld}Current settings ${txtrst}(in minutes, 0 = disabled):"
+        if [ X"${dispdpms}" = X"Disabled" ]; then
+          printf "%s\\n" "   DPMS:         ${dispdpms}"
+          printf "%s\\n" "   Suspend:      ${suspinhval}"
+        fi
+
+        # DPMS enabled information
+        if [ X"${dispdpms}" = X"Enabled" ]; then
+          printf "%s\\n" "   DPMS:         ${dispdpms}"
+          printf "%s\\n" "   DPMS times:   Blank: ${dispblank}; Standby: ${dispstand}; Suspend: ${dispsusp}; Offtime: ${dispoff}"
+          printf "%s\\n" "   Suspend:      ${suspinhval}"
+        fi
+        printf "\\n"
+        printf "%s\\n" "   ${txtbld}${prog} settings${txtrst}:"
+        printf "%s\\n" "   Resume after: ${resumetimehr} hours"
+        printf "\\n"
+        exit 0
+    }
+
+    _ismonitorattached()
+    {
+        xrandr | grep "^VGA" | grep " connected" >/dev/null && return 0
+        xrandr | grep "^HDMI" | grep " connected" >/dev/null && return 0
+        return 1
+    }
+
+    _arch()
+    {   #check for system arch, returns [64|32]
+        if [ -z "${MACHTYPE}" ]; then
+            _arch_var_arch="$(uname -m)"
+        else
+            _arch_var_arch="$(printf "%s" "${MACHTYPE}" | cut -d- -f1)"
+        fi
+
+        case "${_arch_var_arch}" in
+            x86_64) _arch_var_arch="64" ;;
+            i686)   _arch_var_arch="32" ;;
+            *)      return 1 ;;
+        esac
+
+        printf "%s" "${_arch_var_arch}"
+    }
+
+    if ! command -v "xdotool" >/dev/null; then
+        _die "You need to install xdotool: $ sudo apt-get install xdotool"
     fi
 
-    # DPMS enabled information
-    if [ X"$dispdpms" = X"Enabled" ]; then
-      printf "%s\\n" "   DPMS:         $dispdpms"
-      printf "%s\\n" "   DPMS times:   Blank: ${dispblank}; Standby: ${dispstand}; Suspend: ${dispsusp}; Offtime: ${dispoff}"
-      printf "%s\\n" "   Suspend:      $suspinhval"
-    fi
-    printf "\\n"
-    printf "%s\\n" "   ${txtbld}$prog settings${txtrst}:"
-    printf "%s\\n" "   Resume after: $resumetimehr hours"
-    printf "\\n"
-    exit 0
-}
+    resumetime="0"
 
-_ismonitorattached()
-{
-    xrandr | grep "^VGA" | grep " connected" >/dev/null && return 0
-    xrandr | grep "^HDMI" | grep " connected" >/dev/null && return 0
-    return 1
-}
+    [ X"${resumetime}" = X"0" ] && resumetime="1440" # Re-enable resume after a full day
 
-_arch()
-{   #check for system arch, returns [64|32]
-    if [ -z "$MACHTYPE" ]; then
-        _arch_var_arch=$(uname -m)
-    else
-        _arch_var_arch=$(printf "%s" "$MACHTYPE" | cut -d- -f1)
-    fi
-
-    case "$_arch_var_arch" in
-        x86_64) _arch_var_arch="64" ;;
-        i686)   _arch_var_arch="32" ;;
-        *)      return 1 ;;
+    # Check that values for 'resumetime' are numbers
+    case "${resumetime}" in
+        ''|*[!0-9]*) printf "%s\\n" "Error, ${resumetime} is not a number";exit 1;;
     esac
 
-    printf "%s" "$_arch_var_arch"
-}
+    # Name of suspend script
+    tmploc="${HOME}"
+    suspinhscript="${tmploc}"/."movietime-suspend-inhibit"
 
-if ! command -v "xdotool" >/dev/null; then
-    _die "You need to install xdotool: $ sudo apt-get install xdotool"
-fi
+    # Program name from it's filename.
+    prog="${0##*/}"
 
-resumetime=0
+    # Text color variables
+    txtbld="$(tput bold)"             # Bold
+    bldred="${txtbld}$(tput setaf 1)" # red
+    txtrst="$(tput sgr0)"             # Reset
+    warn="${bldred}*${txtrst}"
 
-[ X"$resumetime" = X"0" ] && resumetime=1440 # Re-enable resume after a full day
+    # Check that Xorg server is running
+    if [ -z "$(pgrep "X")" ]; then
+      printf "%s\\n" "${warn} The Xorg server is not running."
+      exit
+    fi
 
-# Check that values for 'resumetime' are numbers
-case $resumetime in
-    ''|*[!0-9]*) printf "%s\\n" "Error, $resumetime is not a number";exit 1;;
-esac
+    # Check if user is regular user
+    if [ X"$(whoami)" = X"root" ]; then
+      printf "%s\\n" "${warn} You are the root user, must be a regular user."
+      exit
+    fi
 
-# Name of suspend script
-tmploc="$HOME"
-suspinhscript="$tmploc"/."movietime-suspend-inhibit"
+    # Current DPMS times (in minutes)
+    dispdpms="$(xset -q  | awk '/DPMS is/ { printf $3 }')" # Enab. or Disb.
+    dispstand="$(xset -q | awk '/^  Standby: / { printf $2/60 }')"
+    dispsusp="$(xset -q  | awk '/^  Standby: / { printf $4/60 }')"
+    dispoff="$(xset -q   | awk '/^  Standby: / { printf $6/60 }')"
+    dispblank="$(xset -q | awk '/^  timeout: / { printf $2/60 }')"
 
-# Program name from it's filename.
-prog=${0##*/}
+    # Resume time in hours
+    resumetimehr="$(printf "%s\\n" "scale=1;${resumetime}/60" | bc)"
 
-# Text color variables
-txtund=$(tput sgr 0 1)          # Underline
-txtbld=$(tput bold)             # Bold
-bldblu=${txtbld}$(tput setaf 4) #  blue
-bldwht=${txtbld}$(tput setaf 7) #  white
-bldred=${txtbld}$(tput setaf 1) #  red
-txtrst=$(tput sgr0)             # Reset
-info=${bldwht}*${txtrst}        # Feedback
-pass=${bldblu}*${txtrst}
-warn=${bldred}*${txtrst}
+    # Display help
+    case "${1}" in
+      -h|--help|h|help)         _usage;;
+      [a-g,i-z,A-G,I-Z,0-9,-]*) _usage;;
+    esac
 
-# Check that Xorg server is running
-if [ -z "$(ps aux | grep /usr/bin/X)" ]; then
-  printf "%s\\n" "$warn The Xorg server is not running."
-  exit
-fi
+    # Suspend inhibit script (must be run as seperate process)
+    suspinhibit () {
+        printf "%s\\n" '#!/usr/bin/env sh
+        for time in $(seq 1 '${resumetime}'); do
+        # Simulate user activity every minute
+        xdotool keydown Shift_L keyup Shift_L
+        #dbus-send --print-reply --type=method_call --dest=org.freedesktop.ScreenSaver /ScreenSaver org.freedesktop.ScreenSaver.SimulateUserActivity
+        sleep 60
+        done'
+    }
 
-# Check if user is regular user
-if [ X"$(whoami)" = X"root" ]; then
-  printf "%s\\n" "$warn You are the root user, must be a regular user."
-  exit
-fi
-
-# Current DPMS times (in minutes)
-dispdpms=$(xset -q  | awk '/DPMS is/ { printf $3 }') # Enab. or Disb.
-dispstand=$(xset -q | awk '/^  Standby: / { printf $2/60 }')
-dispsusp=$(xset -q  | awk '/^  Standby: / { printf $4/60 }')
-dispoff=$(xset -q   | awk '/^  Standby: / { printf $6/60 }')
-dispblank=$(xset -q | awk '/^  timeout: / { printf $2/60 }')
-
-# Resume time in hours
-resumetimehr=$(printf "%s\\n" "scale=1;${resumetime}/60" | bc)
-
-# Display help
-case $1 in
-  -h|--help|h|help) _usage;;
-  [a-g,i-z,A-G,I-Z,0-9,-]*) _usage;;
-esac
-
-# Suspend inhibit script (must be run as seperate process)
-suspinhibit () {
-    printf "%s\\n" '#!/usr/bin/env sh
-    for time in $(seq 1 '$resumetime'); do
-    # Simulate user activity every minute
-    xdotool keydown Shift_L keyup Shift_L
-    #dbus-send --print-reply --type=method_call --dest=org.freedesktop.ScreenSaver /ScreenSaver org.freedesktop.ScreenSaver.SimulateUserActivity
-    sleep 60
-    done'
-}
-
-# Toggle powersaving
-if [ X"$dispdpms" = X"Enabled" ] && [ -z "$suspinhtest" ]; then
-  # Disable blanking, screen power saving
-  xset s off; xset -dpms
-  # Create script in tmp
-  suspinhibit > "$suspinhscript"
-  # Make script executable
-  chmod +x "$suspinhscript"
-  # Run script
-  "$suspinhscript" &> /dev/null &
+    # Toggle powersaving
+    if [ X"${dispdpms}" = X"Enabled" ] && [ -z "${suspinhtest}" ]; then
+      # Disable blanking, screen power saving
+      xset s off; xset -dpms
+      # Create script in tmp
+      suspinhibit > "${suspinhscript}"
+      # Make script executable
+      chmod +x "${suspinhscript}"
+      # Run script
+      "${suspinhscript}" > /dev/null 2>&1 &
 
   if _ismonitorattached; then
-      if [ -f /usr/local/bin/lights/$(_arch)/lights ]; then
+      if [ -f /usr/local/bin/lights/"$(_arch)"/lights ]; then
           #TODO 13-02-2014 01:30 >> only run when connected
-          /usr/local/bin/lights/$(_arch)/lights > /dev/null 2>&1 &
+          /usr/local/bin/lights/"$(_arch)"/lights > /dev/null 2>&1 &
       else
-          printf "%s\\n" "To enjoy fully the movietime experience install: /usr/local/bin/lights/"$_arch"/lights"
+          printf "%s\\n" "To enjoy fully the movietime experience install: /usr/local/bin/lights/${_arch}/lights"
           printf "%s\\n" "  https://github.com/chilicuil/learn/tree/master/java"
       fi
   fi
 
-  printf "%s\\n" "[+] $prog started"
+  printf "%s\\n" "[+] ${prog} started"
 else
   # Enable blanking, screen power saving
   xset s on; xset +dpms
   # Kill script
-  if [ -n $suspinhtest ]; then
-    kill -9 $(ps -aef | awk '/movietime-susp/ {if ($0 !~ "awk" ) print $2}') &> /dev/null
-    ps aux | grep [l]ights.jar >/dev/null
-    if [ "$?" -eq 0 ]; then
-        kill -s 9 $(ps -aef | awk '/lights.jar/ {if ($0 !~ "awk" ) print $2}')
+  if [ -z "${suspinhtest}" ]; then
+    kill -9 "$(pgrep -f "movietime-susp")" > /dev/null 2>&1
+    if pgrep -f "lights.jar" >/dev/null 2>&1; then
+        kill -9 "$(pgrep -f "lights.jar")" > /dev/null 2>&1
     fi
-    rm -rf "$suspinhscript"
+    rm -rf "${suspinhscript}"
     printf "%s\\n" "[-] $prog stopped"
   fi
 fi
diff --git a/sh/tools/rm_ b/sh/tools/rm_
--- a/sh/tools/rm_
+++ b/sh/tools/rm_
@@ -13,15 +13,15 @@
 
 #If you improve it, drop me an email, <m@javier.io>
 
-trash_dir=""$HOME"/.local/share/Trash"
+trash_dir="${HOME}"/.local/share/Trash
 
-if [ $# -eq 0 ] ; then # let 'rm' ouptut the usage error
+if [ "${#}" -eq "0" ] ; then # let 'rm' ouptut the usage error
     exec rm  #our shell is replaced by /bin/rm, keeping original status unmodified
 fi
 
 _usage()
 {
-    printf "%b\\n" "Usage: $(expr "$0" : '.*/\([^/]*\)') [OPTION]... FILE..."
+    printf "%b\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [OPTION]... FILE..."
     printf "%b\\n" "Wrapper for the \`rm' command, compatible with nautilus|pcmanfm file managers\n"
     printf "%b\\n" "  -l [PATTERN]   list archived files, use -ll and -lll to increase verbosity"
     printf "%b\\n" "  -c [PATTERN]   remove permanently archived files"
@@ -29,7 +29,7 @@ _usage()
     printf "%b\\n" "  -y             say yes to all questions"
     printf "%b\\n" "  -f             remove instead of archive files \`rm' is executed directly"
     printf "%b\\n" "  -h             shows this message, use --help to obtain \`rm' help"
-    printf "%b\\n" "\n$(expr "$0" : '.*/\([^/]*\)') deletes directories and files with no distintion therefore no -r option is needed\n"
+    printf "%b\\n" "\n$(expr "${0}" : '.*/\([^/]*\)') deletes directories and files with no distintion therefore no -r option is needed\n"
 
     printf "%b\\n" "Last version is available in: <https://github.com/chilicuil/learn/tree/master/sh/tools/rm_>"
     printf "%b\\n" "Report bugs to m@javier.io"
@@ -38,42 +38,38 @@ _usage()
 #http://www.makkintosshu.com/journal/a-realpath-implementation-in-bash
 _realpath()
 {
-    _realpath_var_success=true
-    _realpath_var_path="$1"
+    _realpath_var_success="true"
+    _realpath_var_path="${1}"
 
     # make sure the string isn't empty as that implies something in further logic
-    if [ -z "$_realpath_var_path" ]; then
-        _realpath_var_success=false
+    if [ -z "${_realpath_var_path}" ]; then
+        _realpath_var_success="false"
     else
         # start with the file name (sans the trailing slash)
         _realpath_var_path="${_realpath_var_path%/}"
 
         # if we stripped off the trailing slash and were left with nothing, that means we're in the root directory
-        if [ -z "$_realpath_var_path" ]; then
-            _realpath_var_path="/"
-        fi
+        [ -z "${_realpath_var_path}" ] && _realpath_var_path="/"
 
         # get the basename of the file (ignoring '.' & '..', because they're really part of the path)
         _realpath_var_file_basename="${_realpath_var_path##*/}"
-        if [ X"$_realpath_var_file_basename" = X"." ] || [ X"$_realpath_var_file_basename" = X".." ]; then
+        if [ X"${_realpath_var_file_basename}" = X"." ] || [ X"${_realpath_var_file_basename}" = X".." ]; then
             _realpath_var_file_basename=""
         fi
 
         # extracts the directory component of the full path, if it's empty then assume '.' (the current working directory)
-        _realpath_var_directory="${_realpath_var_path%$_realpath_var_file_basename}"
-        if [ -z "$_realpath_var_directory" ]; then
-            _realpath_var_directory='.'
-        fi
+        _realpath_var_directory="${_realpath_var_path%${_realpath_var_file_basename}}"
+        [ -z "${_realpath_var_directory}" ] && _realpath_var_directory="."
 
         # attempt to change to the directory
-        if ! \cd "$_realpath_var_directory" >/dev/null 2>/dev/null; then
-            _realpath_var_success=false
+        if ! \cd "${_realpath_var_directory}" >/dev/null 2>/dev/null; then
+            _realpath_var_success="false"
         fi
 
-        if $_realpath_var_success; then
+        if "${_realpath_var_success}"; then
             # does the filename exist?
-            if [ -n "$_realpath_var_file_basename" ] && [ ! -e "$_realpath_var_file_basename" ]; then
-                _realpath_var_success=false
+            if [ -n "${_realpath_var_file_basename}" ] && [ ! -e "${_realpath_var_file_basename}" ]; then
+                _realpath_var_success="false"
             fi
 
             # get the absolute path of the current directory & change back to previous directory
@@ -88,63 +84,70 @@ _realpath()
             fi
 
             # output the absolute path
-            printf "%s\\n" "$_realpath_var_abs_path"
+            printf "%s\\n" "${_realpath_var_abs_path}"
         fi
     fi
 
-    $_realpath_var_success
+    "${_realpath_var_success}"
 }
 
 #http://www.linuxmisc.com/12-unix-web-servers/d31beb238f7b5a6b.htm
 _dirname()
-{
-    local dir="${1%${1##*/}}"
-    [ X"${dir:=./}" != X"/" ] && dir="${dir%?}"
-    printf "%s\\n" "$dir"
+{   #returns string containing dirname on success, 1 on fail
+    [ -z "${1}" ] && return 1
+
+    case "${1}" in
+        /*|*/*) #http://www.linuxselfhelp.com/gnu/autoconf/html_chapter/autoconf_10.html
+            dir=$(expr "x${1}" : 'x\(.*\)/[^/]*' \| '.'      : '.')
+            printf "%s\\n" "${dir}"
+            ;;
+        *) printf "%s\\n" ".";;
+    esac
 }
 
 _list()
 {
-    #files_in_trash=("$trash_dir"/info/*.trashinfo)
-    files_in_trash=$(find "$trash_dir"/info/ -name "*.trashinfo" | wc -l)
+    #files_in_trash="("$trash_dir"/info/*.trashinfo)"
+    files_in_trash="$(find "${trash_dir}"/info/ -name "*.trashinfo" | wc -l)"
 
-    if [ X"$files_in_trash" = X"0" ]; then
-        printf "%s\\n" "$(expr "$0" : '.*/\([^/]*\)'): Nothing to list" >&2 ; exit 1
+    if [ X"${files_in_trash}" = X"0" ]; then
+        printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): Nothing to list" >&2 ; exit 1
     fi
 
-    #OLDIFS="$IFS"; IFS=$'\n' #fix case where files have spaces
-    OLDIFS="$IFS"; IFS='
+    OLDIFS="${IFS}"; IFS='
    ' #fix case where files have spaces
-    for data_in_trashinfo in $(find "$trash_dir"/info -name "*.trashinfo" -print0 | sort -z | xargs -0 grep -A 1 -Hri "path.*$1" \
-        | sed -e 's:^:|:g' -e 's:\.trashinfo.*=:|:g' | tr -d '\n'| sed -e 's:--:\n:g' | sed -e 's: :%%%%%:g'); do
+    for data_in_trashinfo in $(find "${trash_dir}"/info -name "*.trashinfo" -print0 \
+        | sort -z | xargs -0 grep -A 1 -Hri "path.*$1" \
+        | sed -e 's:^:|:g' -e 's:\.trashinfo.*=:|:g'   \
+        | tr -d '\n'| sed -e 's:--:\n:g' | sed -e 's: :%%%%%:g'); do
 
-        datetime=$(printf "%s\\n" "$data_in_trashinfo" | cut -d\| -f5)
-        general_date=$(printf "%s\\n" "$datetime" | cut -dT -f1)
-        detail_date=$(printf "%s\\n" "$datetime" | cut -dT -f2)
-        name=$(printf "%s\\n" "$data_in_trashinfo" | cut -d\| -f3 | sed -e 's:%%%%%: :g')
-        real_file=$(printf "%s\\n" "$data_in_trashinfo" | cut -d\| -f2 | sed -e 's:%%%%%: :g' | sed -e 's:\/info\/:\/files\/:g')
-        [ -e "$real_file" ] && size=$(du -sh "$real_file" | awk '{print $1}') || size="0.0K"
+        datetime="$(printf "%s\\n" "${data_in_trashinfo}" | cut -d\| -f5)"
+        general_date="$(printf "%s\\n" "${datetime}" | cut -dT -f1)"
+        detail_date="$(printf "%s\\n" "${datetime}" | cut -dT -f2)"
+        name="$(printf "%s\\n" "${data_in_trashinfo}" | cut -d\| -f3 | sed -e 's:%%%%%: :g')"
+        real_file="$(printf "%s\\n" "${data_in_trashinfo}" | cut -d\| -f2 | sed -e 's:%%%%%: :g' | sed -e 's:\/info\/:\/files\/:g')"
+        [ -e "${real_file}" ] && size="$(du -sh "${real_file}" | awk '{print $1}')" || size="0.0K"
 
-        if [ -d "$real_file" ] ; then
-            if [ "$verboselist" -gt 1 ]; then
-                some="$(ls "$real_file" | wc -l | sed 's/[^[:digit:]]//g')"
-                printf "%b\\n" "$some\t$size\t$general_date $detail_date $name/"
-                if [ "$verboselist" -gt 2 ]; then
-                    find "$real_file" | sed -e "s:$trash_dir/files::g" | sed -e 's:^:\t\t|_ ..:g'
+        if [ -d "${real_file}" ] ; then
+            if [ "${verboselist}" -gt "1" ]; then
+                some="$(ls "${real_file}" | wc -l | sed 's/[^[:digit:]]//g')"
+                printf "%b\\n" "${some}\t${size}\t${general_date} ${detail_date} ${name}/"
+                if [ "${verboselist}" -gt "2" ]; then
+                    find "${real_file}" | sed -e "s:${trash_dir}/files::g" | sed -e 's:^:\t\t|_ ..:g'
                 fi
             else
-                printf "%s\\n" "$name/"
+                printf "%s\\n" "${name}/"
             fi
         else
-            if [ "$verboselist" -gt 1 ]; then
-                some=1
-                printf "%b\\n" "$some\t$size\t$general_date $detail_date $name"
+            if [ "${verboselist}" -gt "1" ]; then
+                some="1"
+                printf "%b\\n" "${some}\t${size}\t${general_date} ${detail_date} ${name}"
             else
-                printf "%s\\n" "$name"
+                printf "%s\\n" "${name}"
             fi
         fi
     done
-    IFS="$OLDIFS"
+    IFS="${OLDIFS}"
 }
 
 _archive()
@@ -152,32 +155,30 @@ _archive()
     #TODO 08-08-2011 01:19 => report nautilus bug: recovering foo/1, foo/bar/1, foo/bar/rar/1
     #                         gives foo/1 foo/bar/1.2 foo/bar/rar/1.3
 
-    mkdir -p "$trash_dir"/files #ensure directories exist
-    mkdir -p "$trash_dir"/info #ensure directories exist
+    mkdir -p "${trash_dir}"/files #ensure directories exist
+    mkdir -p "${trash_dir}"/info #ensure directories exist
 
-    for file
-    do
-        if [ -e "$file" ] ; then
-            archive="$trash_dir/files/${file##*/}"
-            trashinfo="$trash_dir/info/${file##*/}.trashinfo"
+    for file; do
+        if [ -e "${file}" ] ; then
+            archive="${trash_dir}/files/${file##*/}"
+            trashinfo="${trash_dir}/info/${file##*/}.trashinfo"
 
-            num=2
+            num="2"
 
-            while [ -e "$archive" ]; do
-                archive="$trash_dir/files/${file##*/}.$num"
-                trashinfo="$trash_dir/info/${file##*/}.$num.trashinfo"
-                #num+=1
-                num=$(expr $num + 1)
+            while [ -e "${archive}" ]; do
+                archive="${trash_dir}/files/${file##*/}.${num}"
+                trashinfo="${trash_dir}/info/${file##*/}.${num}.trashinfo"
+                num="$(expr "${num}" + 1)"
             done
 
             #put $file & $trashinfo vars between "" to capture spaces
-            printf "%s\\n" "[Trash Info]"                         >  "$trashinfo"
-            printf "%s\\n" "Path=$(_realpath "$file")"             >> "$trashinfo"
-            printf "%s\\n" "DeletionDate=$(date +%Y-%m-%dT%T)"    >> "$trashinfo"
+            printf "%s\\n" "[Trash Info]"                      >  "${trashinfo}"
+            printf "%s\\n" "Path=$(_realpath "${file}")"       >> "${trashinfo}"
+            printf "%s\\n" "DeletionDate=$(date +%Y-%m-%dT%T)" >> "${trashinfo}"
 
-            mv "$file" "$archive" || rm -rf "$archive" "$trashinfo"
+            mv "${file}" "${archive}" || rm -rf "${archive}" "${trashinfo}"
         else
-            rm "$file"
+            rm "${file}"
         fi
     done
 }
@@ -186,117 +187,119 @@ _recover()
 {
     #TODO 08-08-2011 05:39 => "*" matchs nothing
 
-    _list "$1"
+    _list "${1}"
 
-    if [ -z "$yflag" ]; then
+    if [ -z "${yflag}" ]; then
         printf "%s" "Recover this items from trash? (Y/n) "
-        answer=y
+        answer="y"
         read answer
     else
-        answer=y
+        answer="y"
     fi
 
-    if [ ! X"$answer" = X"y" ]; then
+    if [ ! X"${answer}" = X"y" ]; then
         printf "%s\\n" "Nothing done" && exit 0
     else
-        OLDIFS="$IFS"; IFS='
+        OLDIFS="${IFS}"; IFS='
         ' #fix case where files have spaces
-        for data_in_trashinfo in $(find "$trash_dir"/info -name "*.trashinfo" -print0 | sort -z | xargs -0 grep -A 1 -Hri "path.*$1" \
-            | sed -e 's:^:|:g' -e 's:\.trashinfo.*=:|:g' | tr -d '\n'| sed -e 's:--:\n:g' | sed -e 's: :%%%%%:g'); do
+        for data_in_trashinfo in $(find "${trash_dir}"/info -name "*.trashinfo" -print0 \
+            | sort -z | xargs -0 grep -A 1 -Hri "path.*$1" \
+            | sed -e 's:^:|:g' -e 's:\.trashinfo.*=:|:g'   \
+            | tr -d '\n'| sed -e 's:--:\n:g' | sed -e 's: :%%%%%:g'); do
 
-            datetime=$(printf "%s\\n" "$data_in_trashinfo" | cut -d\| -f5)
-            general_date=$(printf "%s\\n" "$datetime" | cut -dT -f1)
-            detail_date=$(printf "%s\\n" "$datetime" | cut -dT -f2)
-            name=$(printf "%s\\n" "$data_in_trashinfo" | cut -d\| -f3 | sed -e 's:%%%%%: :g')
-            real_file=$(printf "%s\\n" "$data_in_trashinfo" | cut -d\| -f2 | sed -e 's:%%%%%: :g' | sed -e 's:\/info\/:\/files\/:g')
+            datetime="$(printf "%s\\n" "${data_in_trashinfo}" | cut -d\| -f5)"
+            general_date="$(printf "%s\\n" "${datetime}" | cut -dT -f1)"
+            detail_date="$(printf "%s\\n" "${datetime}" | cut -dT -f2)"
+            name="$(printf "%s\\n" "${data_in_trashinfo}" | cut -d\| -f3 | sed -e 's:%%%%%: :g')"
+            real_file="$(printf "%s\\n" "${data_in_trashinfo}" | cut -d\| -f2 | sed -e 's:%%%%%: :g' | sed -e 's:\/info\/:\/files\/:g')"
 
-            info_file="$trash_dir/info/${real_file##*/}.trashinfo"
-            file_file="$trash_dir/files/${real_file##*/}"
+            info_file="${trash_dir}/info/${real_file##*/}.trashinfo"
+            file_file="${trash_dir}/files/${real_file##*/}"
 
-            if [ ! -d $(_dirname "$name") ]; then
-                printf "%s\\n" "mkdir -p $(_dirname $name)"
+            if [ ! -d "$(_dirname "${name}")" ]; then
+                printf "%s\\n" "mkdir -p $(_dirname "${name}")"
             fi
 
-            if [ -e "$name" ]; then
-                mv "$file_file" "$name.$general_date-$detail_date.saved"
-                rm "$info_file"
+            if [ -e "${name}" ]; then
+                mv "${file_file}" "${name}.${general_date}-${detail_date}.saved"
+                rm "${info_file}"
             else
-                mv "$file_file" "$name"
-                rm "$info_file"
+                mv "${file_file}" "${name}"
+                rm "${info_file}"
             fi
         done
-        IFS="$OLDIFS"
+        IFS="${OLDIFS}"
     fi
     exit
 }
 
 _clean()
 {
-    _list "$1"
+    _list "${1}"
 
-    if [ -z "$yflag" ]; then
+    if [ -z "${yflag}" ]; then
         printf "%s" "Empty this items from trash? (Y/n) "
-        answer=y
+        answer="y"
         read answer
     else
-        answer=y
+        answer="y"
     fi
 
-    if [ ! X"$answer" = X"y" ]; then
+    if [ ! X"${answer}" = X"y" ]; then
         printf "%s\\n" "Nothing done" && exit 0
     else
-        OLDIFS="$IFS"; IFS='
+        OLDIFS="${IFS}"; IFS='
         ' #fix case where files have spaces
-        for data_in_trashinfo in $(find "$trash_dir"/info -name "*.trashinfo" -print0 | sort -z | xargs -0 grep -A 1 -Hri "path.*$1" \
-            | sed -e 's:^:|:g' -e 's:\.trashinfo.*=:|:g' | tr -d '\n'| sed -e 's:--:\n:g' | sed -e 's: :%%%%%:g'); do
+        for data_in_trashinfo in $(find "$trash_dir"/info -name "*.trashinfo" -print0 \
+            | sort -z | xargs -0 grep -A 1 -Hri "path.*$1" \
+            | sed -e 's:^:|:g' -e 's:\.trashinfo.*=:|:g'   \
+            | tr -d '\n'| sed -e 's:--:\n:g' | sed -e 's: :%%%%%:g'); do
 
-            real_file=$(printf "%s\\n" "$data_in_trashinfo" | cut -d\| -f2 | sed -e 's:%%%%%: :g' | sed -e 's:\/info\/:\/files\/:g')
-            info_file="$trash_dir/info/${real_file##*/}.trashinfo"
-            file_file="$trash_dir/files/${real_file##*/}"
+            real_file="$(printf "%s\\n" "${data_in_trashinfo}" | cut -d\| -f2 | sed -e 's:%%%%%: :g' | sed -e 's:\/info\/:\/files\/:g')"
+            info_file="${trash_dir}/info/${real_file##*/}.trashinfo"
+            file_file="${trash_dir}/files/${real_file##*/}"
 
-            rm -rf "$info_file"
-            rm -rf "$file_file"
-            #printf "%s\\n" "rm: $info_file"
-            #printf "%s\\n" "rm: $file_file"
+            rm -rf "${info_file}"
+            rm -rf "${file_file}"
         done
-        IFS="$OLDIFS"
+        IFS="${OLDIFS}"
     fi
 }
 
-verboselist=0
+verboselist="0"
 while getopts ":fluhcry" options
 do
-    case $options in
-        f) exec rm -r "$@"                          ;;
-        l) verboselist=$(expr $verboselist + 1)     ;;  # list verbose level 1-3
-        u) shift $(expr $OPTIND - 1); _recover "$@" ;;  # remove the -u
-        h) _usage                                   ;;
-        c) shift $(expr $OPTIND - 1); _clean "$@"   ;;  # remove the -c
-        r)                                          ;;
-        y) yflag=yes                                ;;
-        *) exec rm "$@"                             ;;  # send the rest to rm
+    case "${options}" in
+        f) exec rm -r "${@}"                              ;;
+        l) verboselist="$(expr "${verboselist}" + 1)"     ;;  # list verbose level 1-3
+        u) shift "$(expr "${OPTIND}" - 1)"; _recover "${@}" ;;  # remove the -u
+        h) _usage                                         ;;
+        c) shift "$(expr "${OPTIND}" - 1)"; _clean "${@}"   ;;  # remove the -c
+        r)                                                ;;
+        y) yflag="yes"                                    ;;
+        *) exec rm "${@}"                                 ;;  # send the rest to rm
     esac
 done
 
-shift $(expr $OPTIND - 1)
+shift "$(expr "${OPTIND}" - 1)"
 
-if [ $verboselist -gt 0 ]; then
-    _list "$@"
+if [ "${verboselist}" -gt "0" ]; then
+    _list "${@}"
     exit 0
 fi
 
 # Make sure that the $trash_dir exists
-if [ ! -d "$trash_dir" ] ; then
-    if [ ! -w "$HOME" ] ; then
-        printf "%s\\n" "$(expr "$0" : '.*/\([^/]*\)') failed: can't create $trash_dir in $HOME" >&2
+if [ ! -d "${trash_dir}" ] ; then
+    if [ ! -w "${HOME}" ] ; then
+        printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)') failed: can't create ${trash_dir} in ${HOME}" >&2
         exit 1
     fi
-    mkdir -p "$trash_dir"/expunged
-    mkdir -p "$trash_dir"/files
-    mkdir -p "$trash_dir"/info
-    chmod -R 700 "$trash_dir"
+    mkdir -p "${trash_dir}"/expunged
+    mkdir -p "${trash_dir}"/files
+    mkdir -p "${trash_dir}"/info
+    chmod -R 700 "${trash_dir}"
 fi
 
-_archive "$@"
+_archive "${@}"
 
 exit 0
diff --git a/sh/tools/screenshot b/sh/tools/screenshot
--- a/sh/tools/screenshot
+++ b/sh/tools/screenshot
@@ -4,47 +4,61 @@
 #             otherwise use the full name provided and add a .png sufix
 #usage: screenshot [-s] [output]
 
-_notify ()
+_notify()
 {
-    [ X"$TERM" = X"linux" ] && notify-send -t 1000 "${@}" || printf "%s\\n" "${@}"
+    [ -z "${1}" ] && return 1
+    [ -z "${2}" ] && return 1
+    if [ X"${TERM}" = X"linux" ] || [ -z "${TERM}" ]; then
+        if ! DISPLAY=:0 notify-send -t 1000 "${1}"  "${2}"; then
+            if command -v "gxmessage" 2>/dev/null; then
+                font="Monaco 9"
+                gxmessage "${font:+-fn "$font"}" "${1} ${2}" "got it"
+            else
+                font="fixed"
+                xmessage "${font:+-fn "$font"}" "${1} ${2}" "got it"
+            fi
+        fi
+    else
+        printf "%s: %s\\n" "${1}" "${2}"
+    fi
 }
 
 _screenshot()
 {
-    [ -z "$1" ] && return 0
+    [ -z "${1}" ] && return 0
 
     if command -v "scrot" >/dev/null; then
         _screenshot_var_bin="scrot"
-        [ -n "$flag_select" ] && _screenshot_var_opt="-s" || _screenshot_var_opt=""
+        [ -n "${flag_select}" ] && _screenshot_var_opt="-s" || _screenshot_var_opt=""
     elif command -v "gnome-screenshot" >/dev/null; then
         _screenshot_var_bin="gnome-screenshot"
-        [ -n "$flag_select" ] && _screenshot_var_opt="-a" || _screenshot_var_opt=""
+        [ -n "${flag_select}" ] && _screenshot_var_opt="-a" || _screenshot_var_opt=""
     elif command -v "import" >/dev/null; then
         _screenshot_var_bin="import"
-        [ -n "$flag_select" ] && _screenshot_var_opt=""   || _screenshot_var_opt="-window root"
+        [ -n "${flag_select}" ] && _screenshot_var_opt=""   || _screenshot_var_opt="-window root"
     else
         _notify "[-] Error" "install either scrot, gnome-screenshot or imagemagick"
         exit 1
     fi
 
-    eval "$_screenshot_var_bin $_screenshot_var_opt $1"
+    eval "${_screenshot_var_bin} ${_screenshot_var_opt} ${1}"
 }
 
-if [ $# -eq 0 ]; then
-    file=$HOME/`</dev/urandom tr -dc A-Za-z0-9 | head -c 8`.png
+if [ "${#}" -eq "0" ]; then
+    file="${HOME}"/$(</dev/urandom tr -dc A-Za-z0-9 | head -c 8).png
 else
-    for var in "$@"; do #parse options
+    for var in "${@}"; do #parse options
         case "${var}" in
             -s) flag_select="y"; shift; ;;
         esac
     done
-    [ -z "$1" ] && file=$HOME/`</dev/urandom tr -dc A-Za-z0-9 | head -c 8`.png || file="$1".png
+    [ -z "${1}" ] && file="${HOME}"/$(</dev/urandom tr -dc A-Za-z0-9 | head -c 8).png || file="${1}".png
 fi
 
 _notify "[+] Screenshot" "in 3.., 2.., 1.., smile =)!"
 sleep 3
-kill $(ps -aef | awk '/notify-osd/ {if ($0 !~ "awk") print $2}') >/dev/null 2>/dev/null
+kill "$(pgrep notify-osd)" >/dev/null 2>/dev/null
 sleep .5
-[ -n "$flag_select" ] && _notify "[+] Select" "a rectangle to save"
-_screenshot "$file"
-[ -f "$file" ] && _notify "[+] Done" "$file" || _notify "[+] Error" "couldn't take screenshot"
+[ -n "${flag_select}" ] && _notify "[+] Select" "a rectangle to save"
+_screenshot "${file}"
+[ -f "${file}" ] && _notify "[+] Done" "${file}" || _notify "[+] Error" "couldn't take screenshot"
diff --git a/sh/tools/setup b/sh/tools/setup
--- a/sh/tools/setup
+++ b/sh/tools/setup
@@ -3,13 +3,13 @@
 #usage: setup [autocp|script]
 
 #example: setup script /path/file
-#[+] chmod +x dmenu-killall 
+#[+] chmod +x dmenu-killall
 #[+] sudo cp dmenu-killall /usr/local/bin
 
 #Don't forget update this when adding new functions
 _usage()
 {
-  printf "%s\\n" "$(expr "$0" : '.*/\([^/]*\)'): setup my common tasks"
+  printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): setup my common tasks"
   printf "\\n"
   printf "%s\\n" "  autocp            cp custom autocomplete file"
   printf "%s\\n" "  script            cp custom script to the path system"
@@ -19,24 +19,24 @@ _usage()
 
 _exec()
 {   #print current command, exits on fail
-    [ -z "$1" ] && return 0
+    [ -z "${1}" ] && return 0
 
-    printf "%s " "[+] $@"
+    printf "%s " "[+] ${@}"
     printf "\\n"
-    eval "$@"
+    eval "${@}"
 
-    local status=$?
-    [ X"$status" != X"0" ] && exit $status || return
+    _exec_var_status="${?}"
+    [ X"${_exec_var_status}" != X"0" ] && exit "${_exec_var_status}" || return
 }
 
 _script()
 {
 
-    [ -z "$1" ] && (printf "%s\\n" "$(expr "$0" : '.*/\([^/]*\)'): Missing argument, looking for a .sh|.py|.rb|etc script"; exit 1)
+    [ -z "${1}" ] && (printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): Missing argument, looking for a .sh|.py|.rb|etc script"; exit 1)
 
     for file; do
-        _exec chmod +x "$file"
-        _exec sudo cp "$file" /usr/local/bin
+        _exec chmod +x "${file}"
+        _exec sudo cp "${file}" /usr/local/bin
     done
 
     exit 0
@@ -44,32 +44,22 @@ _script()
 
 _autocp()
 {
-    [ -n "$1" ] || (printf "%s\\n" "$(expr "$0" : '.*/\([^/]*\)'): Missing parameter, looking for an .autocp file"; exit 1)
+    [ -n "${1}" ] || (printf "%s\\n" "$(expr "${0}" : '.*/\([^/]*\)'): Missing parameter, looking for an .autocp file"; exit 1)
 
     for file; do
-        _exec sudo cp "$file" /usr/share/bash-completion/completions/
+        _exec sudo cp "${file}" /usr/share/bash-completion/completions/
     done
     exit 0
 }
 
-if [ X"$#" != X"0" ]; then
-    case $1 in
-        script)
-        shift; _script $@
-        ;;
-        autocp)
-        shift; _autocp $@
-        ;;
-        -h | --help)
-        _usage
-        ;;
-        -v | --version)
-        printf "%s\\n" "$VERSION"
-        ;;
-        *)
-        printf "%s\\n" "Error, unknown option: $1"
-        _usage
-        ;;
+if [ X"${#}" != X"0" ]; then
+    case "${1}" in
+        script) shift; _script "${@}" ;;
+        autocp) shift; _autocp "${@}" ;;
+        -h | --help)    _usage ;;
+        -v | --version) printf "%s\\n" "${VERSION}" ;;
+        *) printf "%s\\n" "Error, unknown option: ${1}"
+           _usage ;;
     esac
 else
     _usage
diff --git a/sh/tools/whats b/sh/tools/whats
--- a/sh/tools/whats
+++ b/sh/tools/whats
@@ -5,26 +5,26 @@
 #example: whats dns
 #Domain Name System, internet system used...
 
-word="$1"
+word="${1}"
 
 _usage()
 {
-    printf "%s\\n" "Usage: `expr "$0" : '.*/\([^/]*\)'` word" >&2
+    printf "%s\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') word" >&2
     exit 0
 }
 
-[ -z "$word" ] && _usage
+[ -z "${word}" ] && _usage
 
 _whats()
 {
-    [ -z "$1" ] && (printf "%s\\n" "$0: Missing argument"; exit 1)
+    [ -z "${1}" ] && (printf "%s\\n" "${0}: Missing argument"; exit 1)
 
-    [ -n "$2" ] || more_than_one=1
+    [ -n "${2}" ] || more_than_one="1"
 
     for word; do
-        response=$(dig +short txt $word.wp.dg.cx)
-        printf "%s\\n" "$response"
-        if [ -z "$more_than_one" ]; then
+        response="$(dig +short txt ${word}.wp.dg.cx)"
+        printf "%s\\n" "${response}"
+        if [ -z "${more_than_one}" ]; then
             printf "\\n"
             printf "%s\\n" ":::::::::::::::::::::::::::::::::::::::::::::::::"
             printf "\\n"
@@ -32,4 +32,4 @@ _whats()
     done
 }
 
-_whats "$@"
+_whats "${@}"
