create-minos-{core,mozilla}-settings: add check, local settings exists

diff --git a/sh/is/create-minos-mozilla-settings b/sh/is/create-minos-mozilla-settings
--- a/sh/is/create-minos-mozilla-settings
+++ b/sh/is/create-minos-mozilla-settings
@@ -7,6 +7,7 @@
 
 trap _cleanup 15 #trap ctrl-c
 #trap _cleanup SIGINT SIGTERM #trap ctrl-c
+total_errors="0"
 
 _cmd() {
     #print current command, exits on fail
@@ -29,8 +30,18 @@ _cleanup() {
     [ -z ${1} ] && exit
 }
 
+_file_or_directory_exist() {
+    [ -z "${1}" ] && return 1
+    [ -f "${1}" ] && return 0
+    [ -d "${1}" ] && return 0
+    printf "\\n%s\\n" "WARNING: ${1} doesn't exists, skipping ..." >&2
+    total_errors="$((total_errors + 1))"
+    return 1
+}
+
 _create_minos_default_mozilla_settings() {
     [ -d mozilla-orig ] && _cmd rm -rf mozilla-orig
+    if _file_or_directory_exist "${HOME}"/.mozilla; then
     _cmd cp -r ~/.mozilla mozilla-orig
     _cmd mkdir mozilla-orig/tmp
     (cd mozilla-orig/firefox/*.default && \
@@ -65,7 +76,10 @@ _create_minos_default_mozilla_settings() {
     sed -i -e "/capability.policy.maonoscript.sites/ s;,.*;, \"addons.mozilla.org afx.ms ajax.aspnetcdn.com cdnjs.cloudflare.com code.jquery.com firstdata.com firstdata.lv flashgot.net gfx.ms google.com googleapis.com googlevideo.com gstatic.com hotmail.com informaction.com live.com live.net maone.net minos.io mootools.net mozilla.net msn.com noscript.net outlook.com passport.com passport.net passportimages.com paypal.com paypalobjects.com persona.org prototypejs.org securecode.com securesuite.net sfx.ms tinymce.cachefly.net vjs.zendcdn.net wlxrs.com yahoo.com yahooapis.com yandex.st yimg.com youtube.com ytimg.com about: about:addons about:blank about:blocked about:certerror about:config about:crashes about:home about:memory about:neterror about:plugins about:privatebrowsing about:sessionrestore about:srcdoc about:support blob: chrome: http://afx.ms http://firstdata.com http://firstdata.lv http://flashgot.net http://gfx.ms http://google.com http://googleapis.com http://googlevideo.com http://gstatic.com http://hotmail.com http://informaction.com http://live.com http://live.net http://maone.net http://minos.io http://mootools.net http://mozilla.net http://msn.com http://noscript.net http://outlook.com http://passport.com http://passport.net http://passportimages.com http://paypal.com http://paypalobjects.com http://persona.org http://prototypejs.org http://securecode.com http://securesuite.net http://sfx.ms http://wlxrs.com http://yahoo.com http://yahooapis.com http://yandex.st http://yimg.com http://youtube.com http://ytimg.com https://afx.ms https://firstdata.com https://firstdata.lv https://flashgot.net https://gfx.ms https://google.com https://googleapis.com https://googlevideo.com https://gstatic.com https://hotmail.com https://informaction.com https://live.com https://live.net https://maone.net https://minos.io https://mootools.net https://mozilla.net https://msn.com https://noscript.net https://outlook.com https://passport.com https://passport.net https://passportimages.com https://paypal.com https://paypalobjects.com https://persona.org https://prototypejs.org https://securecode.com https://securesuite.net https://sfx.ms https://wlxrs.com https://yahoo.com https://yahooapis.com https://yandex.st https://yimg.com https://youtube.com https://ytimg.com moz-safe-about: resource:\")\;;" mozilla-orig/firefox/*.default/prefs.js
 
     _cmd "find mozilla-orig/firefox/*.default/ -type f | xargs sed -i -e \"s/$(whoami)/muser/g\""; :
-    printf "%s\\n" "[+] New mozilla profile generated at: mozilla-orig/"
+    printf "\\n%s\\n" "[+] New mozilla profile generated at: mozilla-orig/"
+    fi
+
+    [ "${total_errors}" -gt "0" ] && printf "%s\\n" "[-] "${total_errors}" errors were found, see above to find more details" && return 1 || :
 }
 
 _create_minos_default_mozilla_settings
