create-minos-{core,mozilla}-settings: add check, local settings exists

diff --git a/sh/is/create-minos-core-settings b/sh/is/create-minos-core-settings
--- a/sh/is/create-minos-core-settings
+++ b/sh/is/create-minos-core-settings
@@ -9,6 +9,7 @@ trap _cleanup 15 #trap ctrl-c
 #trap _cleanup SIGINT SIGTERM #trap ctrl-c
 
 file_header="This file is part of the minos-core-settings package"
+total_errors="0"
 
 _usage() {
     printf "%b\\n" "Usage: $(expr "${0}" : '.*/\([^/]*\)') [directory]"
@@ -37,6 +38,15 @@ _cleanup() {
     [ -z ${1} ] && exit
 }
 
+_file_or_directory_exist() {
+    [ -z "${1}" ] && return 1
+    [ -f "${1}" ] && return 0
+    [ -d "${1}" ] && return 0
+    printf "\\n%s\\n" "WARNING: ${1} doesn't exists, skipping ..." >&2
+    total_errors="$((total_errors + 1))"
+    return 1
+}
+
 _create_minos_default_core_settings() {
     #$1 => target directory
     [ -z "${1}" ] && return 1
@@ -44,52 +54,62 @@ _create_minos_default_core_settings() {
     [ -d "${1}" ] && _cmd rm -rf "${1}"
     _cmd mkdir -p "${1}"
 
-    #echo
-    #_cmd cp ~/.minos/autostart "${1}"/etc.minos.autostart
-    #_cmd "sed -i 's:^#!/bin/sh:#!bin/sh\n\n#${file_header}' ${1}/etc.minos.autostart"
+    if _file_or_directory_exist ~/.bashrc; then
+        echo
+        _cmd "printf \"%s\\n\\n\" \"#${file_header}\" > \"${1}\"/etc##profile.d##minos-bash.sh"
+        _cmd "sed -n '/^#===/,/^#}1/p;/^#}1/q' ~/.bashrc | head -n -1 >> ${1}/etc##profile.d##minos-bash.sh"
+        _cmd "sed -n '/{2/,/^#}2/p;/^#}2/q' ~/.bashrc  | head -n -1 | sed 1d >> ${1}/etc##profile.d##minos-bash.sh"
+        _cmd "echo >> ${1}/etc##profile.d##minos-bash.sh"
+        _cmd "sed -n '/{3/,/^#}3/p;/^#}3/q' ~/.bashrc | head -n -1 | sed 1d >> ${1}/etc##profile.d##minos-bash.sh"
+        _cmd "sed -i '/^export PATH/d' ${1}/etc##profile.d##minos-bash.sh"
+        _cmd "sed -i 's:^#export PATH:export PATH:' ${1}/etc##profile.d##minos-bash.sh"
+        _cmd "sed -i '/GPGKEY/d' ${1}/etc##profile.d##minos-bash.sh"
+        _cmd "sed -i '/^#gpg/d' ${1}/etc##profile.d##minos-bash.sh"
+        _cmd "sed -i '/^#random vars/d' ${1}/etc##profile.d##minos-bash.sh"
+        _cmd "sed -i '/LC_ALL/d' ${1}/etc##profile.d##minos-bash.sh"
+    fi
 
-    echo
-    _cmd "printf \"%s\\n\\n\" \"#${file_header}\" > \"${1}\"/etc##profile.d##minos-bash.sh"
-    _cmd "sed -n '/^#===/,/^#}1/p;/^#}1/q' ${HOME}/.bashrc | head -n -1 >> ${1}/etc##profile.d##minos-bash.sh"
-    _cmd "sed -n '/{2/,/^#}2/p;/^#}2/q' ${HOME}/.bashrc  | head -n -1 | sed 1d >> ${1}/etc##profile.d##minos-bash.sh"
-    _cmd "echo >> ${1}/etc##profile.d##minos-bash.sh"
-    _cmd "sed -n '/{3/,/^#}3/p;/^#}3/q' ${HOME}/.bashrc | head -n -1 | sed 1d >> ${1}/etc##profile.d##minos-bash.sh"
-    _cmd "sed -i '/^export PATH/d' ${1}/etc##profile.d##minos-bash.sh"
-    _cmd "sed -i 's:^#export PATH:export PATH:' ${1}/etc##profile.d##minos-bash.sh"
-    _cmd "sed -i '/GPGKEY/d' ${1}/etc##profile.d##minos-bash.sh"
-    _cmd "sed -i '/^#gpg/d' ${1}/etc##profile.d##minos-bash.sh"
-    _cmd "sed -i '/^#random vars/d' ${1}/etc##profile.d##minos-bash.sh"
-    _cmd "sed -i '/LC_ALL/d' ${1}/etc##profile.d##minos-bash.sh"
+    if _file_or_directory_exist ~/.aliases; then
+        echo
+        _cmd "printf \"%s\\n\\n\" \"#${file_header}\" > \"${1}\"/etc##skel##.aliases"
+        _cmd "sed -n '/^\[/,/xdg-open/p;/xdg-open/q' ~/.aliases >> ${1}/etc##skel##.aliases"
+        _cmd "sed -n '/(gpg -d/p' ~/.aliases >> ${1}/etc##skel##.aliases"
+        _cmd "echo >> ${1}/etc##skel##.aliases"
+        _cmd "sed -n '/eix.exact=/p' ~/.aliases >> ${1}/etc##skel##.aliases"
+        _cmd "echo >> ${1}/etc##skel##.aliases"
+        _cmd "echo '# vim: set ts=8 sw=4 tw=0 ft=conf :' >> ${1}/etc##skel##.aliases"
+    fi
 
-    echo
-    _cmd "printf \"%s\\n\\n\" \"#${file_header}\" > \"${1}\"/etc##skel##.aliases"
-    _cmd "sed -n '/^\[/,/xdg-open/p;/xdg-open/q' ${HOME}/.aliases >> ${1}/etc##skel##.aliases"
-    _cmd "sed -n '/(gpg -d/p' ${HOME}/.aliases >> ${1}/etc##skel##.aliases"
-    _cmd "echo >> ${1}/etc##skel##.aliases"
-    _cmd "sed -n '/eix.exact=/p' ${HOME}/.aliases >> ${1}/etc##skel##.aliases"
-    _cmd "echo >> ${1}/etc##skel##.aliases"
-    _cmd "echo '# vim: set ts=8 sw=4 tw=0 ft=conf :' >> ${1}/etc##skel##.aliases"
+    if _file_or_directory_exist ~/.bash_profile; then
+        echo
+        _cmd "printf \"%s\\n\\n\" \"#${file_header}\" > \"${1}\"/etc##skel##.bash_profile"
+        _cmd "cat ~/.bash_profile >> ${1}/etc##skel##.bash_profile"
+    fi
 
-    echo
-    _cmd "printf \"%s\\n\\n\" \"#${file_header}\" > \"${1}\"/etc##skel##.bash_profile"
-    _cmd "cat ${HOME}/.bash_profile >> ${1}/etc##skel##.bash_profile"
+    if _file_or_directory_exist ~/.bashrc; then
+        echo
+        _cmd "printf \"%s\\n\\n\" \"#${file_header}\" > \"${1}\"/etc##skel##.profile.d##shundle.sh"
+        _cmd "printf \"%s\\n\\n\" \"#http://github.com/chilicuil/shundle\" >> \"${1}\"/etc##skel##.profile.d##shundle.sh"
+        _cmd "sed -n '/shundle/,\$p' ~/.bashrc >> ${1}/etc##skel##.profile.d##shundle.sh"
+    fi
 
-    echo
-    _cmd "printf \"%s\\n\\n\" \"#${file_header}\" > \"${1}\"/etc##skel##.profile.d##shundle.sh"
-    _cmd "printf \"%s\\n\\n\" \"#http://github.com/chilicuil/shundle\" >> \"${1}\"/etc##skel##.profile.d##shundle.sh"
-    _cmd "sed -n '/shundle/,\$p' ${HOME}/.bashrc >> ${1}/etc##skel##.profile.d##shundle.sh"
+    if _file_or_directory_exist ~/.tmux.conf; then
+        echo
+        _cmd "printf \"%s\\n\\n\" \"#${file_header}\" > \"${1}\"/etc##skel##.tmux.conf"
+        _cmd "cat ~/.tmux.conf >> ${1}/etc##skel##.tmux.conf"
+    fi
 
-    echo
-    _cmd "printf \"%s\\n\\n\" \"#${file_header}\" > \"${1}\"/etc##skel##.tmux.conf"
-    _cmd "cat ${HOME}/.tmux.conf >> ${1}/etc##skel##.tmux.conf"
+    if _file_or_directory_exist ~/.vimrc; then
+        echo
+        _cmd "printf \"%s\\n\\n\" \"\\\"${file_header}\" > \"${1}\"/etc##skel##.vimrc"
+        _cmd "cat ~/.vimrc >> ${1}/etc##skel##.vimrc"
+    fi
 
-    echo
-    _cmd "printf \"%s\\n\\n\" \"\\\"${file_header}\" > \"${1}\"/etc##skel##.vimrc"
-    _cmd "cat ${HOME}/.vimrc >> ${1}/etc##skel##.vimrc"
-
-    echo
-    _cmd "printf \"%s\\n\\n\" \"#${file_header}\" > \"${1}\"/etc##ssh##ssh_config"
-    _cmd "sed -n '/^Host \*$/,/^$/p;/^$/q' ${HOME}/.ssh/config >> ${1}/etc##ssh##ssh_config"
+    if _file_or_directory_exist ~/.ssh/config; then
+        echo
+        _cmd "printf \"%s\\n\\n\" \"#${file_header}\" > \"${1}\"/etc##ssh##ssh_config"
+        _cmd "sed -n '/^Host \*$/,/^$/p;/^$/q' ~/.ssh/config >> ${1}/etc##ssh##ssh_config"
+    fi
 
     echo
     _cmd "printf \"%s\\n\\n\" \"#${file_header}\" > \"${1}\"/etc##sudoers.d##minos-core"
@@ -113,7 +133,7 @@ _create_minos_default_core_settings() {
     cat > "${1}"/etc##update-motd.d##00-header <<'EOF'
 #!/bin/sh
 . /etc/os-release 2>/dev/null
-if [ -z "$VERSION_ID" ]; then
+if [ -z "${VERSION_ID}" ]; then
     printf "\\nWelcome to Minos (%s %s %s)\\n\\n" "$(uname -o)" "$(uname -r)" "$(uname -m)"
 else
     printf "\\nWelcome to Minos %s LTS (%s %s %s)\\n\\n" "$VERSION_ID" "$(uname -o)" "$(uname -r)" "$(uname -m)"
@@ -167,14 +187,16 @@ EOF
     _cmd "printf \"%s\\n\\n\" \"// ${file_header}\" > \"${1}\"/etc##apt##apt.conf.d##05disable-suggests"
     _cmd "printf \"%s\\n\" \"APT::Install-Suggests \\\"false\\\";\" >> \"${1}\"/etc##apt##apt.conf.d##05disable-suggests"
 
-    echo
-    _cmd "printf \"%s\\n\\n\" \";${file_header}\" > \"${1}\"/etc##gitconfig"
-    _cmd "cat ~/.gitconfig                        >>    ${1}/etc##gitconfig"
-    _cmd "sed -i '/^\[user\]$/,/^$/d'                   ${1}/etc##gitconfig"
-    _cmd "sed -i '/^\[github\]$/,/^$/d'                 ${1}/etc##gitconfig"
+    if _file_or_directory_exist ~/.gitconfig; then
+        echo
+        _cmd "printf \"%s\\n\\n\" \";${file_header}\" > \"${1}\"/etc##gitconfig"
+        _cmd "cat ~/.gitconfig                        >>    ${1}/etc##gitconfig"
+        _cmd "sed -i '/^\[user\]$/,/^$/d'                   ${1}/etc##gitconfig"
+        _cmd "sed -i '/^\[github\]$/,/^$/d'                 ${1}/etc##gitconfig"
+    fi
 
-    echo
-    printf "%s\\n" "[+] New minos core settings generated at: ${1}/"
+    printf "\\n%s\\n" "[+] New minos core settings generated at: ${1}/"
+    [ "${total_errors}" -gt "0" ] && printf "%s\\n" "[-] "${total_errors}" errors were found, see above to find more details" && return 1 || :
 
     cat > "${1}/README.md" << 'E=O=F'
 ## About
