add description

diff --git a/sh/is/update-firefox-nightly b/sh/is/update-firefox-nightly
--- a/sh/is/update-firefox-nightly
+++ b/sh/is/update-firefox-nightly
@@ -1,15 +1,16 @@
-#!/usr/bin/env bash
-#chilicuil <chilicuil@gmail.com> 2012
+#!/usr/bin/env sh
 #a simple script to update firefox nightly when the integrated updater doesn't work
 
-trap _cleanup SIGINT SIGTERM #trap ctrl-c
+trap _cleanup 0 15 #trap ctrl-c
+#trap _cleanup SIGINT SIGTERM #trap ctrl-c
 
 _cmd()
 {   #print current command, exits on fail
     [ -z "$1" ] && return 0
 
-    printf "%s\\n" "    $ $@"
-    $@
+    printf "%s " "    $ $@"
+    printf "\\n"
+    eval "$@"
 
     status=$?
     [ X"$status" != X"0" ] && exit $status || return
@@ -36,12 +37,13 @@ _cleanup()
     [ -z $1 ] && exit
 }
 
-notify ()
+_notify()
 {
     if [ X"$TERM" = X"linux" ]; then
         notify-send -t 3000 "${@}"
     else
-        printf "%s\\n" "${@}"
+        printf "%s " "$@"
+        printf "\\n"
     fi
 }
 
@@ -65,21 +67,21 @@ _arch()
     printf %s\\n "$arch"
 }
 
-_update-firefox32()
+_update_firefox32()
 {
     nightly=$(curl http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/ 2>&1 | grep -o -E 'href="([^"#]+)"' | cut -d'"' -f2 |  grep "linux-i686.tar.bz2")
     _cmd wget -c http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/"$nightly"
-    _cmd tar jxf firefox*bz2
+    _cmd "bzcat < firefox*bz2 | tar xf -"
     _cmd rm -rf firefox-* $HOME/.bin/firefox$arch
     _cmd mv firefox $HOME/.bin/firefox$arch
 }
 
 
-_update-firefox64()
+_update_firefox64()
 {
     nightly=$(curl http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/ 2>&1 | grep -o -E 'href="([^"#]+)"' | cut -d'"' -f2 | grep "linux-x86_64.tar.bz2")
     _cmd wget -c http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/"$nightly"
-    _cmd tar jxf firefox*bz2
+    _cmd "bzcat < firefox*bz2 | tar xf -"
     _cmd rm -rf firefox-* $HOME/.bin/firefox$arch
     _cmd mv firefox $HOME/.bin/firefox$arch
 }
@@ -88,10 +90,10 @@ arch=$(_arch)
 [ ! -f "$(whereis curl |awk '{print $2}')" ] && _die "curl was not found!"
 [ -d "$HOME/.bin/firefox$arch" ] && _cmd mkdir -p $HOME/.bin/firefox$arch
 
-if [ "$arch" -eq 32 ]; then
-    _update-firefox32
+if [ X"$arch" = X"32" ]; then
+    _update_firefox32
 else
-    _update-firefox64
+    _update_firefox64
 fi
 
-notify "[+] Done" "restart firefox to apply the update"
+_notify "[+]  Done" "restart firefox to apply the update"
